import type { Product } from "@/content/types";

/**
 * PENDING VERIFICATION: shown with a "Pending verification" badge and never
 * indexed until the business confirms they are publicly sold. See the product inventory §2.9–2.10.
 */

const FL = "https://fleetras.com";

export const fleetras: Product = {
  id: "fleetras",
  slug: "fleetras",
  name: "Fleetras",
  shortDescription: "Fleet dispatch and trip-cost tracking for city fleet operations, with costs worked out per kilometre.",
  longDescription:
    "Fleetras covers a ride from booking to cost: the office dispatches a driver and vehicle, the driver runs the trip from a phone, and the trip is costed with a cost per kilometre the moment it is finished.\n\n" +
    "Drivers record kilometres, fuel, Salik (Dubai road tolls), parking, fines and other expenses with receipt photos. Managers handle expense claims, manual kilometres, edits and cancellations in one approvals queue, and every correction stays on the trip record with the time and the person who made it.\n\n" +
    "GPS trackers in the vehicles send live position, mileage and alerts into each trip through the TrackSolid Pro platform, so trips can be checked against what the vehicle actually did. Reports break cost down by vehicle, driver and passenger and export to Excel or a print-ready report.\n\n" +
    "It runs in a desktop browser for the office and installs to the home screen on iPhone and Android for drivers. There is no public sign-up: an administrator creates every account.",
  tagline: "Every trip. Every dirham. Fully accounted.",
  category: "operations-it",
  subcategory: "fleet-logistics",
  primaryUseCase: "Fleet dispatch and trip costing",
  audience: ["Fleet and transport offices", "Transport managers", "Drivers", "Accounts teams"],
  platforms: ["web"],
  market: "UAE",
  status: "pending",
  websiteUrl: `${FL}/`,
  publisher: { name: "Fleetras (Dubai, United Arab Emirates)" },
  verification: {
    relationship: "pending",
    publicSale: "pending",
    notes:
      "Login-only site; accounts are created by an administrator. Footer and privacy policy state the platform is operated from Dubai, United Arab Emirates; no legal entity name is given. No pricing is published.",
  },
  howItWorks: [
    { title: "Assign", description: "Dispatch creates the trip with driver, vehicle, route, time and priority. The driver is notified on the spot and can accept, reject or ask for reassignment." },
    { title: "Drive", description: "The driver accepts, starts with GPS, picks up the passenger, pauses when needed and ends the trip. The phone shares its position only at those taps." },
    { title: "Submit", description: "Kilometres, fuel, Salik, parking and other costs are entered with receipts and sent for review. Kilometres typed in by hand may need a manager's approval." },
    { title: "Finish and cost", description: "The driver finishes and the trip is costed on the spot. Managers correct distance or expenses through the approvals queue, and the driver is told about the change." },
  ],
  benefits: [
    { title: "A cost on every trip", description: "Each trip gets an itemised cost and a cost per kilometre as soon as it is finished. Month-end figures come from the system instead of spreadsheets passed between the office, managers and drivers." },
    { title: "Formulas the accounts team already uses", description: "Fleetras applies the same formulas as a trip-wise vehicle cost workbook. Fuel recorded at the pump takes priority over the mileage estimate, and kilometre figures that look wrong are flagged for review." },
    { title: "Trips checked against the vehicle", description: "GPS tracker data is attached to the trip record, and the tracker fills in distance when no odometer reading is given. A replay shows the route, stops and idle time for any day." },
    { title: "A clear trail for financial records", description: "Every step from assigned to completed is recorded with a timestamp and the person who did it. Every change goes to an audit log, and every sign-in is recorded with device and address." },
    { title: "Each role sees only its own work", description: "Four roles, from Super Admin to Driver, are enforced on every action. Drivers are kept out of office data and see only their own trips, odometer readings and passengers." },
  ],
  useCases: [
    { title: "Running a city passenger fleet", description: "A transport office dispatches drivers to pick up passengers across Dubai, follows each trip live and has every ride costed in dirhams when it ends." },
    { title: "Closing the month without spreadsheets", description: "The accounts team pulls monthly trends and cost by vehicle, driver and passenger, then exports to Excel or prints a report for sign-off." },
    { title: "Reviewing driver expense claims", description: "A manager works through one queue of expense, manual-kilometre, edit and cancellation requests, approving or correcting each one with receipts attached." },
    { title: "Checking a disputed trip", description: "A manager replays the vehicle's route for the day, with start and end points, stops and idle time, next to the distance the driver submitted." },
  ],
  security: [
    { title: "Role-based permissions", description: "Permissions are checked on the server for every action, not just when a page loads. Trying to reach data or functions beyond your role is a breach of the terms." },
    { title: "Drivers kept separate", description: "Drivers cannot view office data. They see only their own trips, odometer readings and passengers." },
    { title: "Audit and sign-in logs", description: "Every change is written to an audit log so records can be traced. Every sign-in attempt is recorded with date, time, IP address, device and browser." },
    { title: "Session expiry", description: "The only cookie is an essential, encrypted sign-in cookie that web pages' scripts cannot read (HTTP-only). Sessions expire after eight hours or at sign-out, and old sessions are cleared automatically." },
    { title: "Password rules", description: "Passwords need upper case, lower case and a number, and resets go by email link. Passwords are hashed with a one-way algorithm and never stored in readable form." },
    { title: "Private receipts", description: "Uploaded receipts and photos are stored away from the public part of the website. They are shown only to signed-in users." },
    { title: "No data sales or ad tracking", description: "Fleetras states it does not sell personal data or share it with advertisers, and it uses no advertising or third-party analytics cookies." },
  ],
  faqs: [
    { question: "Who is Fleetras built for?", answer: "Fleet and transport offices running city fleets, described on the site as Dubai city operations. The office, transport managers and drivers all work in the same system, each with their own role." },
    { question: "How do I get an account?", answer: "There is no public sign-up. An administrator at your company creates each account, and you sign in with your work email. Companies that want to start using Fleetras are asked to get in touch to set up their company." },
    { question: "Does it need a separate app for drivers?", answer: "No store download is needed. Fleetras works in the browser on desktop and installs to the home screen on iPhone and Android, so drivers use their own phone." },
    { question: "How is the cost of a trip calculated?", answer: "Fuel cost is total km divided by the vehicle's mileage, multiplied by the fuel rate; fuel recorded at the pump overrides that estimate, and electric vehicles carry no fuel cost. Fuel, Salik, parking, fines and other expenses make the vehicle total, a share of fixed vehicle costs (allocations) is added to give the total cost, and dividing by total km gives the cost per km." },
    { question: "Is the driver's phone tracked all the time?", answer: "No. Personal devices are not tracked in the background. The driver app shares its GPS position only at the moments a driver taps start, pause, resume or end; continuous tracking comes from GPS units in company vehicles while they are in use." },
    { question: "What happens when a driver's figures are wrong?", answer: "The driver or office raises a request for an expense, manual kilometres, an edit or a cancellation, and it waits in one approvals queue. A manager approves, requests a correction or rejects it, the change is recorded on the trip, and the driver is told." },
    { question: "Can we bring in existing trips or take data out?", answer: "Yes. Trips can be imported from Excel, and reports can be filtered and exported to Excel or opened as a print-ready report." },
    { question: "How long are trip records kept?", answer: "Trip, expense and cost records are treated as financial records and kept as long as your company needs them, normally at least five years after the end of the financial year they relate to. Deleting a vehicle or driver also deletes its trips, so a warning is shown before you confirm." },
  ],
  featureCategories: [
    {
      slug: "trips",
      name: "Trips",
      description: "Dispatch, the driver app and the approvals queue that take a trip from booking to a finished, costed record.",
      body: [
        "Fleetras is one system for the office, the manager and the driver, covering everything between the booking and the invoice. Each trip moves through assign, drive, submit and finish, and every step is recorded with a timestamp and the person who did it.",
      ],
    },
    { slug: "costing", name: "Costing", description: "How each trip is costed: fuel from mileage and pump rate, itemised expenses, a share of fixed vehicle costs and a cost per kilometre." },
    { slug: "fleet", name: "Fleet and tracking", description: "The records of vehicles, drivers and passengers, live GPS from vehicle trackers, and the alerts they send." },
    { slug: "admin", name: "Reporting and administration", description: "Monthly reports and Excel exports, plus the four roles that decide what each person can see and do." },
  ],
  features: [
    {
      slug: "dispatch-and-live-trips",
      name: "Dispatch and assignment",
      summary: "Assign a driver and vehicle with pickup, destination, time and priority, and follow every trip from assigned to completed.",
      category: "trips",
      body: [
        "The office creates each trip with a driver, vehicle, pickup, destination, time and priority. The driver is notified straight away and can accept, reject or ask for reassignment from their phone.",
        "Every step from assigned to completed is recorded with a timestamp and the person who did it, and trips can also be imported from Excel.",
      ],
      problem: "When trips are booked by phone and logged in spreadsheets, nobody can say for certain who was sent, when they accepted, or where the trip stands.",
      howItWorks: [
        "Dispatch creates the trip with driver, vehicle, pickup, destination, time and priority.",
        "The driver is notified on the spot and accepts, rejects or requests reassignment from their phone.",
        "The driver runs the trip from the driver app, while the vehicle's GPS tracker reports its position.",
        "Each status change is logged with time and person until the trip is completed and costed.",
      ],
      capabilities: [
        "Trips carry a pickup, destination, time and priority set by the office.",
        "A driver and a vehicle are assigned to each trip, and the driver is notified immediately.",
        "Drivers can accept, reject or ask for reassignment instead of calling the office.",
        "Every step from assigned to completed is timestamped with the person who did it.",
        "Trips can be imported in bulk from Excel.",
      ],
      benefits: [
        "Dispatchers see whether each assignment has been accepted without chasing drivers.",
        "The trip history shows who did what and when, without piecing it together later.",
      ],
      audience: ["Transport managers", "Dispatchers"],
      faqs: [
        { question: "Who can dispatch trips?", answer: "Dispatching is part of the Transport Manager role, which also tracks vehicles, decides approval requests and manages drivers and guests." },
        { question: "Can a driver turn down a trip?", answer: "Yes. The driver can accept, reject or ask for reassignment from their phone, and the terms ask drivers to respond to assignments promptly." },
      ],
      relatedFeatures: ["driver-app", "live-vehicle-tracking", "notifications-and-alerts"],
      sources: [`${FL}/`, `${FL}/terms`],
      highlight: true,
      hasPage: true,
    },
    {
      slug: "driver-app",
      name: "Driver app on any phone",
      summary: "A driver app that installs to the home screen for starting trips, GPS check-ins, expenses and receipt photos.",
      category: "trips",
      body: [
        "Drivers use Fleetras from their own phone: it works in the browser and installs to the home screen on iPhone and Android. They sign in for the day and run their trips from there.",
        "Location is shared from the app only at the moments a driver taps start, pause, resume or end; personal devices are not tracked in the background.",
      ],
      problem: "Drivers on the road need to record trips and costs as they happen, without a separate device or a paper log to hand in later.",
      howItWorks: [
        "Accept the assignment from the phone.",
        "Start the trip with GPS, pick up the passenger and pause when needed.",
        "End the trip and enter kilometres, fuel, Salik, parking and other costs with receipts.",
        "Finish the trip so it is costed on the spot.",
      ],
      capabilities: [
        "The app runs in the phone's browser and installs to the home screen on iPhone and Android.",
        "Drivers sign in for the day and start, pause, resume and end trips with a tap.",
        "The phone's GPS position is captured only at start, pause, resume and end.",
        "Expenses are recorded with receipt photos while still on the road.",
        "Drivers see only their own trips, odometer readings and passengers.",
      ],
      benefits: [
        "No store download or company device is needed for drivers.",
        "Costs and receipts are captured during the trip instead of collected at month end.",
      ],
      audience: ["Drivers"],
      faqs: [
        { question: "Can drivers use the app while driving?", answer: "Fleetras' terms require drivers to stop safely before using the app for anything beyond a single tap to start or end a trip." },
        { question: "Does the app track my location in the background?", answer: "No. Location is shared only at the moments you tap start, pause, resume or end." },
      ],
      relatedFeatures: ["dispatch-and-live-trips", "finished-by-the-driver"],
      sources: [`${FL}/`, `${FL}/privacy`, `${FL}/terms`],
      hasPage: true,
    },
    {
      slug: "finished-by-the-driver",
      name: "Approvals and corrections",
      summary: "Drivers finish and cost their own trips; corrections go to one manager queue and are recorded on the trip.",
      category: "trips",
      body: [
        "Drivers finish and cost their own trips. Requests for expenses, manual kilometres, edits and cancellations wait in a single queue for a manager to decide.",
        "Every correction is recorded on the trip, and the driver is told when distance or expenses are changed.",
      ],
      problem: "Trip figures sometimes need correcting, and changes made quietly in a spreadsheet leave no record of who changed what or why.",
      howItWorks: [
        "The driver submits kilometres and expenses with receipts and finishes the trip.",
        "The trip is costed immediately.",
        "Expense, manual km, edit or cancellation requests go to the manager's approvals queue.",
        "The manager decides; the correction is recorded on the trip and the driver is notified.",
      ],
      capabilities: [
        "Expense claims, manual kilometres, trip edits and cancellations all wait in one queue.",
        "A manager can approve a submission, request a correction or reject it.",
        "Every correction is recorded on the trip it changes.",
        "Drivers are notified when their distance or expenses are changed.",
        "Approved figures are final unless corrected through the approval process.",
      ],
      benefits: [
        "Managers review exceptions in one place instead of checking every trip.",
        "Each corrected figure keeps its history, which matters for financial records.",
      ],
      audience: ["Transport managers", "Drivers"],
      faqs: [
        { question: "Do approved cost figures mean a driver will be reimbursed?", answer: "Not by themselves. Fleetras' terms say cost figures are for management purposes and do not create an entitlement to payment or reimbursement." },
        { question: "Do manually typed kilometres need approval?", answer: "They may. Manual kilometres are one of the request types that go to the approvals queue." },
      ],
      relatedFeatures: ["cost-per-kilometre", "driver-app"],
      sources: [`${FL}/`, `${FL}/terms`],
      hasPage: true,
    },
    {
      slug: "cost-per-kilometre",
      name: "Trip costing and cost per kilometre",
      summary: "Fuel, Salik, parking, fines and other expenses itemised on every trip, with a cost per km worked out automatically.",
      category: "costing",
      body: [
        "Fleetras applies the same formulas as a trip-wise vehicle cost workbook the moment the driver finishes a trip. Fuel recorded at the pump takes priority over the estimate, and electric vehicles carry no fuel cost.",
        "A share of each vehicle's maintenance, insurance, registration and depreciation costs (allocations) can be added, each company has a base currency, and kilometre figures that look wrong are flagged automatically for review.",
      ],
      problem: "Working out what each trip really cost usually means rebuilding a workbook by hand at month end from fuel slips, toll records and parking receipts.",
      howItWorks: [
        "Fuel cost = total km ÷ mileage × fuel rate.",
        "Vehicle total = fuel + Salik + parking + fines + other.",
        "Total cost = vehicle total + allocations.",
        "Cost per km = total cost ÷ total km.",
      ],
      capabilities: [
        "Fuel, Salik, parking, fines and other expenses are itemised on each trip.",
        "Fuel recorded at the pump takes priority over the mileage-based estimate.",
        "Electric vehicles carry no fuel cost in the calculation.",
        "Vehicle allocations for maintenance, insurance, registration and depreciation can be added to the total.",
        "Each company works in its own base currency.",
        "Kilometre figures that look wrong are flagged automatically for review.",
      ],
      benefits: [
        "The accounts team gets the same numbers its workbook would produce, without the manual work.",
        "Every trip carries a cost per km that can be compared across vehicles and drivers.",
      ],
      audience: ["Accounts teams", "Fleet managers"],
      faqs: [
        { question: "When is a trip costed?", answer: "The moment the driver finishes it. If a manager later corrects distance or expenses through approvals, the correction is recorded on the trip." },
        { question: "Does Fleetras handle maintenance costs?", answer: "Maintenance can be included as a vehicle allocation alongside insurance, registration and depreciation. The site does not describe maintenance scheduling or service records." },
      ],
      relatedFeatures: ["finished-by-the-driver", "reports-and-exports"],
      sources: [`${FL}/`],
      highlight: true,
      hasPage: true,
    },
    {
      slug: "live-vehicle-tracking",
      name: "Live vehicle tracking",
      summary: "GPS trackers send position, mileage and alerts into each trip through the TrackSolid Pro platform.",
      category: "fleet",
      body: [
        "GPS trackers in each vehicle send positions, mileage and alerts into the trip record through the TrackSolid Pro platform, so every trip can be checked against what the vehicle actually did.",
        "The odometer reading at the end of a trip sets the distance, and the tracker fills it in when no reading is given.",
      ],
      problem: "Without tracker data, the distance on a trip is whatever was written down, and there is no way to check it against the vehicle's actual route.",
      howItWorks: [
        "GPS units in company vehicles report position, speed, heading, ignition state, mileage and alerts.",
        "The data reaches Fleetras through the TrackSolid Pro platform and is attached to the trip record.",
        "At the end of a trip, the odometer reading sets the distance, or the tracker fills it in when no reading is given.",
        "Managers replay any day's route with stops and idle time alongside the trip.",
      ],
      capabilities: [
        "A live map shows each vehicle's position, speed, heading and ignition state, refreshed from its GPS unit.",
        "Distance is filled in from the tracker when the driver gives no odometer reading.",
        "Trip playback shows route history for any day with start and end points, stops and idle time.",
        "Speeding, harsh braking, SOS and offline alerts appear in the notification feed.",
        "Alerts when a vehicle enters or leaves a marked area (geofence) appear in the same feed.",
      ],
      benefits: [
        "Submitted distances can be checked against what the vehicle actually did.",
        "Speeding and harsh-driving alerts support road safety.",
      ],
      audience: ["Transport managers", "Fleet managers"],
      faqs: [
        { question: "Which tracking platform does Fleetras use?", answer: "Vehicle GPS data comes through the TrackSolid Pro platform, an outside vehicle-tracking provider that handles device data on Fleetras' instructions." },
        { question: "Is tracking always accurate?", answer: "Not guaranteed. Tracking depends on devices, mobile networks and satellite coverage, so positions may not be continuous or complete at every moment." },
      ],
      relatedFeatures: ["dispatch-and-live-trips", "cost-per-kilometre", "notifications-and-alerts"],
      sources: [`${FL}/`, `${FL}/privacy`, `${FL}/terms`],
      highlight: true,
      hasPage: true,
    },
    {
      slug: "fleet-registry",
      name: "Fleet registry",
      summary: "Vehicles, drivers and passengers with insurance, registration, licence and service expiries.",
      category: "fleet",
      body: [
        "The fleet registry holds vehicles, drivers and passengers, including insurance, registration, licence and service expiry dates.",
        "Retired vehicles and inactive drivers keep their history. Deleting a record is permanent, and Fleetras shows what will be removed with it before you confirm.",
      ],
      problem: "Vehicle documents, driver licences and passenger details tend to live in separate files, so expiry dates are easy to miss.",
      howItWorks: [
        "Add vehicles, drivers and passengers to the registry.",
        "Record insurance, registration, licence and service expiry dates on each record.",
        "Retire vehicles or mark drivers inactive while keeping their trip history.",
        "Before a permanent delete, review the linked records that would be removed with it.",
      ],
      capabilities: [
        "Vehicles, drivers and passengers are each kept as their own records.",
        "Insurance, registration, licence and service expiry dates are stored on the records.",
        "Driver records can hold employee ID, licence number and expiry, Emirates ID, joining date and duty status.",
        "Retired vehicles and inactive drivers keep their history.",
        "A delete preview shows what goes with a record before you confirm.",
      ],
      audience: ["Transport managers", "Fleet managers"],
      faqs: [
        { question: "Does Fleetras send expiry reminders?", answer: "The site lists expiry dates in the registry but does not say that it sends reminders about them." },
        { question: "What happens when I delete a driver or vehicle?", answer: "Deletion is permanent and also removes the trips recorded against it, so Fleetras shows what will go with it and warns you first. Retiring a vehicle or marking a driver inactive keeps the history instead." },
      ],
      relatedFeatures: ["reports-and-exports", "roles-and-permissions"],
      sources: [`${FL}/`, `${FL}/privacy`],
      hasPage: true,
    },
    {
      slug: "reports-and-exports",
      name: "Reports and exports",
      summary: "Monthly trends and cost by vehicle, driver and passenger, exportable to Excel or a print-ready report.",
      category: "admin",
      body: [
        "Reports show monthly trends and cost broken down by vehicle, driver and passenger, so month-end numbers come from the system rather than spreadsheets passed around.",
        "Records can be filtered and selected, then exported to Excel or opened as a print-ready report.",
      ],
      problem: "Month-end reporting often means merging spreadsheets from different people before anyone can see what the fleet cost.",
      howItWorks: [
        "Open the reports for the period you need.",
        "Filter and select the vehicles, drivers, passengers or trips to include.",
        "Export to Excel or open a print-ready report.",
      ],
      capabilities: [
        "Monthly trends show how fleet costs move over time.",
        "Cost is broken down by vehicle, driver and passenger.",
        "Records can be filtered and selected before export.",
        "Exports go to Excel, or open as a print-ready report.",
      ],
      audience: ["Accounts teams", "Transport managers", "Admins"],
      relatedFeatures: ["cost-per-kilometre"],
      sources: [`${FL}/`],
      hasPage: true,
    },
    {
      slug: "roles-and-permissions",
      name: "Four roles",
      summary: "Super Admin, Admin, Transport Manager and Driver: each sees only what their job needs.",
      category: "admin",
      body: [
        "Fleetras has four roles, and each person sees what their job needs and nothing more. Permissions are enforced on every action.",
        "Administrators create every account and can deactivate one at any time.",
      ],
      capabilities: [
        "Super Admin: runs the platform (companies, integrations, email and platform logs) and never sees fleet data",
        "Admin: runs the company profile, users, integrations, costs and every log",
        "Transport Manager: dispatches, tracks vehicles, decides approval requests and manages drivers and guests",
        "Driver: sees only their own trips, odometer readings and passengers",
      ],
      audience: ["Admins", "Transport managers"],
      faqs: [
        { question: "Can the platform operator see our fleet data?", answer: "The Super Admin role runs companies, integrations, email and platform logs, and the site states it never sees fleet data." },
      ],
      relatedFeatures: ["finished-by-the-driver"],
      sources: [`${FL}/`, `${FL}/terms`],
      hasPage: true,
    },
    {
      slug: "notifications-and-alerts",
      name: "Notifications and alerts",
      summary: "Assignment, approval and correction notices in the app and by email, plus vehicle alerts in one feed.",
      category: "fleet",
      body: [
        "Fleetras tells people what changed as it happens. Drivers are notified the moment a trip is assigned to them, and when a manager corrects their distance or expenses.",
        "Notices about assignments, approvals and corrections go out in the app and by email, through the email service your company configures. Alerts from the vehicle GPS units land in the same notification feed.",
      ],
      howItWorks: [
        "A trip is assigned, an approval is decided or a figure is corrected.",
        "The affected person is notified in the app and by email.",
        "Vehicle GPS units send driving and geofence (marked-area) alerts into the same feed.",
      ],
      capabilities: [
        "Assignment notices to drivers on the spot",
        "Approval and correction notices, in the app and by email",
        "Speeding, harsh braking, SOS and offline alerts",
        "Alerts when a vehicle enters or leaves a geofence (a marked area)",
      ],
      audience: ["Drivers", "Transport managers"],
      relatedFeatures: ["dispatch-and-live-trips", "finished-by-the-driver", "live-vehicle-tracking"],
      sources: [`${FL}/`, `${FL}/privacy`],
      hasPage: true,
    },
  ],
  productSolutions: [
    {
      slug: "month-end-trip-cost-accounting",
      name: "Clean trip costs at month end",
      summary: "Replace spreadsheets passed around at month end with trips that are costed, reviewed and traceable as they happen.",
      problem:
        "Fleetras is built for city fleets that need clean numbers at month end, without spreadsheets passed around between the office, managers and drivers, and it treats trip costs as financial records that need a clear trail.",
      body: [
        "Instead of collecting fuel slips and toll records after the fact, each trip is costed when the driver finishes it, and any later correction goes through a manager and stays on the record.",
      ],
      approach: [
        "Each trip is costed the moment the driver finishes it, using the same formulas as a trip-wise vehicle cost workbook",
        "Expenses are itemised per trip with receipt photos",
        "Corrections go through one approvals queue and are recorded on the trip",
        "Every step and every change is recorded with time and person in an audit log",
        "Reports break cost down by vehicle, driver and passenger and export to Excel or print",
      ],
      audience: ["Accounts teams", "Transport managers", "Fleet and transport offices"],
      faqs: [
        { question: "How long are the records kept?", answer: "Trip, expense and cost records are normally kept at least five years after the end of the financial year they relate to, as long as your company needs them for accounting, audit and legal purposes." },
      ],
      features: ["cost-per-kilometre", "finished-by-the-driver", "reports-and-exports", "driver-app"],
      sources: [`${FL}/`, `${FL}/privacy`],
    },
  ],
  productIntegrations: [
    {
      slug: "tracksolid-pro",
      name: "TrackSolid Pro GPS tracking",
      summary: "Vehicle GPS trackers send position, mileage and alerts into Fleetras trips through the TrackSolid Pro platform.",
      connects: "Fleetras connects the GPS trackers installed in company vehicles to its trip records through the TrackSolid Pro vehicle-tracking platform.",
      body: [
        "The tracker data lets every trip be checked against what the vehicle actually did. The tracking provider handles device data on Fleetras' instructions and under its own security commitments.",
      ],
      workflow: [
        "GPS units in company vehicles report position, speed, heading, ignition state, mileage and alerts",
        "TrackSolid Pro passes the data to Fleetras, where it is attached to the trip record",
        "Distance is filled from the tracker when the driver gives no odometer reading",
        "Route history can be played back for any day, with stops and idle time",
        "Speeding, harsh braking, SOS, offline and geofence (marked-area) alerts appear in the notification feed",
      ],
      faqs: [
        { question: "Who must tell drivers about tracking?", answer: "Your company is responsible for informing drivers that vehicles are tracked and for using the data only for operational, safety and cost-control purposes." },
      ],
      features: ["live-vehicle-tracking", "notifications-and-alerts", "cost-per-kilometre"],
      sources: [`${FL}/`, `${FL}/privacy`, `${FL}/terms`],
    },
  ],
  supportTopics: [
    {
      slug: "accounts-and-sign-in",
      name: "Accounts and sign-in",
      summary: "How Fleetras accounts are created by your administrator, how passwords and sessions work, and what to do if your account is misused.",
      body: ["There is no public sign-up: an administrator creates each account, and your role decides what you can see and do."],
      keyPoints: [
        "Sign in with your work email",
        "Passwords need upper case, lower case and a number; resets go by email link",
        "Sessions expire after eight hours",
        "Update your own name, contact details, photo and password from your profile page",
        "Tell your administrator at once if you suspect someone else is using your account",
      ],
      features: ["roles-and-permissions"],
      sources: [`${FL}/`, `${FL}/terms`, `${FL}/privacy`],
    },
    {
      slug: "recording-trips-and-expenses",
      name: "Recording trips and expenses (drivers)",
      summary: "The rules drivers follow when accepting trips, recording odometer readings and claiming expenses, and how managers review what they submit.",
      body: ["Fleetras' terms set out what drivers must do so that trip costs stay accurate, and how managers review submissions."],
      keyPoints: [
        "Accept or decline assignments promptly",
        "Record start and end odometer readings where requested",
        "Claim only genuine expenses for that trip, with a receipt where available",
        "Manually entered kilometres may need approval",
        "Managers can approve, request a correction or reject; approved figures are final unless corrected through approvals",
        "Stop safely before using the app beyond a single tap to start or end a trip",
      ],
      features: ["driver-app", "finished-by-the-driver", "cost-per-kilometre"],
      sources: [`${FL}/terms`],
    },
    {
      slug: "vehicle-tracking-and-privacy",
      name: "Vehicle tracking and driver privacy",
      summary: "What vehicle trackers and the driver app record, when location is captured, and who is responsible for telling drivers about it.",
      body: ["Tracking covers company vehicles while in use. Data comes from GPS units through an outside vehicle-tracking provider and is treated as part of the trip record."],
      keyPoints: [
        "Vehicle units report position, speed, heading, ignition, mileage and alerts",
        "Phones share location only when a driver taps start, pause, resume or end",
        "Your company must tell drivers that vehicles are tracked",
        "Drivers must not disconnect or tamper with tracking hardware",
        "Positions depend on devices, networks and satellites and may have gaps",
      ],
      features: ["live-vehicle-tracking", "driver-app"],
      sources: [`${FL}/privacy`, `${FL}/terms`],
    },
    {
      slug: "data-retention-and-rights",
      name: "Data retention and your rights",
      summary: "How long trip and account records are kept, what deleting a record removes, and how to make a data request under UAE law.",
      body: ["Trip, expense and cost records are financial records, normally kept at least five years after the financial year they relate to. Your company is usually the one responsible for your data (the data controller)."],
      keyPoints: [
        "Deleting a vehicle or driver also deletes its trips, and a warning is shown first",
        "Rights to access, correct, delete, object to and take your data elsewhere apply under UAE Federal Decree-Law No. 45 of 2021",
        "Raise requests with your company administrator first",
        "Data is mainly stored and processed in or from the UAE",
        "No advertising or third-party analytics cookies; data is not sold",
      ],
      features: ["fleet-registry"],
      sources: [`${FL}/privacy`],
    },
  ],
  sources: [`${FL}/`, `${FL}/privacy`, `${FL}/terms`],
  lastVerified: "2026-10-08",
};

const MM = "https://meeting.oxo1.com";

export const meetingmind: Product = {
  id: "meetingmind",
  slug: "meetingmind",
  name: "MeetingMind",
  shortDescription: "AI meeting analysis: summaries, action items and decisions, with an assistant you can ask about past meetings.",
  longDescription:
    "MeetingMind is an AI notetaker for teams that run on meetings. It sends a bot to your Google Meet calls, transcribes them, writes a summary with the decisions made, and assigns action items with owners and due dates.\n\n" +
    "Transcripts show who said what and when, stay in the language the meeting was held in, and can be searched, exported and shared. An assistant answers questions using only your past meetings and names the meeting each answer came from.\n\n" +
    "Owners, managers and members share one workspace, and each person's view changes with their role. On the Premium plan, four specialist modules (AI Project Manager, Client Intelligence, Sales Intelligence and Recruitment Analyzer) turn recurring meetings into insights for specific jobs.",
  tagline: "Your meetings, turned into decisions and done tasks.",
  category: "insights-research",
  secondaryCategories: ["hr-people"],
  subcategory: "meeting-intelligence",
  primaryUseCase: "Turning meetings into actions",
  audience: ["Teams that run on meetings", "Project teams", "Client-facing and sales teams", "Hiring teams"],
  platforms: ["web"],
  market: "Global",
  status: "pending",
  websiteUrl: `${MM}/`,
  verification: {
    relationship: "pending",
    publicSale: "pending",
    notes:
      "Landing page at meeting.oxo1.com names no operating company. Its pricing section says prices \"are set by your MeetingMind operator\", and its testimonial and headline numbers look like template content (not used).",
  },
  appUrl: `${MM}/signup`,
  howItWorks: [
    { title: "Create your workspace", description: "Sign up as the owner and your company workspace is ready straight away. No credit card is required to start." },
    { title: "Invite the bot", description: "Paste a Google Meet link; the bot joins the call and captures the audio, with nothing for the rest of the team to install." },
    { title: "Get notes, tasks and answers", description: "Summaries, decisions and action items appear on your dashboard, and the team can ask the assistant about anything said in past meetings." },
  ],
  benefits: [
    { title: "Nothing said out loud gets lost", description: "Every captured meeting gets a full transcript and a summary with the key decisions. What was agreed is written down without anyone taking notes by hand." },
    { title: "Action items that reach the right person", description: "Tasks are picked out with an owner and a due date and added to each teammate's list. Nobody has to chase follow-ups after the call." },
    { title: "Answers from past meetings, with a source", description: "The assistant answers questions across every past meeting and cites where the answer came from, so a claim can be checked against the original meeting." },
    { title: "No installs for the team", description: "The bot joins a Google Meet from a pasted link, so participants do not need to install anything for a meeting to be captured." },
  ],
  useCases: [
    { title: "Recurring project meetings", description: "On Premium, AI Project Manager turns recurring project meetings into live status, risks and blockers without anyone updating a tracker." },
    { title: "Client account history", description: "On Premium, Client Intelligence keeps a running history of client conversations, with promises made, the client's mood and open issues in one place." },
    { title: "Sales calls", description: "On Premium, Sales Intelligence picks out buying signals, objections and next steps from sales calls." },
    { title: "Hiring conversations", description: "On Premium, Recruitment Analyzer produces organised interview reports and candidate comparisons from hiring conversations." },
  ],
  faqs: [
    { question: "Which meeting platforms does MeetingMind work with?", answer: "The site states it works with Google Meet: you paste a Google Meet link and the bot joins. No other conferencing platform is named." },
    { question: "Does everyone in the meeting need to install something?", answer: "No. Capture is done by a bot that joins the call, so the rest of the team installs nothing. The site also lists a browser extension for capturing from any tab." },
    { question: "What do I get after a meeting?", answer: "A transcript showing who spoke and when, a summary with the key decisions, and action items with owners and due dates, all shown on your dashboard." },
    { question: "How does the assistant answer questions?", answer: "It searches across every past meeting in the workspace and cites the meeting its answer came from. The plans describe it as a RAG assistant, meaning it looks up your own meeting records before answering." },
    { question: "Are transcripts available in other languages?", answer: "Transcripts are produced in the meeting's own language. Multi-language support is listed as a Pro plan feature." },
    { question: "What are the Premium modules?", answer: "AI Project Manager, Client Intelligence, Sales Intelligence and Recruitment Analyzer. They use the meeting analysis for specific kinds of recurring meetings and are included on the Premium plan." },
    { question: "Is there a free option?", answer: "The site lists a Free plan for individuals with a limited number of meeting analyses a month, and says no credit card is required to start. Exact plan prices are set by the MeetingMind operator, so check the site for current terms." },
  ],
  featureCategories: [
    { slug: "features", name: "Features", description: "The core notetaker: the meeting bot, transcripts, AI summaries, assigned action items and an assistant that answers across past meetings." },
    { slug: "premium", name: "Premium specialist modules", description: "AI helpers for recurring meetings, on the Premium plan: project status, client history, sales signals and interview reports." },
  ],
  features: [
    {
      slug: "meeting-bot",
      name: "Meeting bot",
      summary: "A bot joins any Google Meet you send it to and captures the audio, so the meeting can be transcribed and analysed.",
      category: "features",
      body: [
        "MeetingMind captures meetings by sending a bot to the call. You paste a Google Meet link, the bot joins, and it records the audio so the meeting can be transcribed and analysed, with nothing for the rest of the team to install.",
      ],
      problem: "Someone in every meeting usually ends up taking notes instead of taking part, and what they miss is lost.",
      howItWorks: [
        "Create your workspace as the owner.",
        "Paste a Google Meet link to invite the bot.",
        "The bot joins the call and captures the audio.",
        "Summaries, decisions and action items appear on your dashboard.",
      ],
      capabilities: [
        "The bot works with Google Meet calls.",
        "It joins from a meeting link you paste into MeetingMind.",
        "It captures the meeting's audio for transcription and analysis.",
        "Other participants do not need to install anything.",
      ],
      faqs: [
        { question: "Does the bot work with Zoom or Microsoft Teams?", answer: "The site names only Google Meet." },
      ],
      relatedFeatures: ["transcripts", "meeting-summaries", "browser-extension"],
      sources: [`${MM}/`],
      highlight: true,
      hasPage: true,
    },
    {
      slug: "meeting-summaries",
      name: "AI summaries and decisions",
      summary: "Every analysed meeting becomes a clear summary, with the key decisions picked out automatically and shown on your dashboard.",
      category: "features",
      body: [
        "After each captured meeting, MeetingMind writes a clear summary and picks out the key decisions automatically, so what was agreed out loud is written down.",
        "Summaries, action items and decisions are included on every plan; the Pro plan adds multi-language support and follow-ups.",
      ],
      problem: "Decisions made in a meeting are easy to forget or remember differently when nobody writes them down.",
      howItWorks: [
        "The bot captures the meeting and a transcript is produced.",
        "MeetingMind writes a summary of the meeting.",
        "Key decisions are listed alongside the summary.",
        "The summary, decisions and action items appear on your dashboard.",
      ],
      capabilities: [
        "Every analysed meeting gets its own summary.",
        "Key decisions are picked out of the conversation automatically.",
        "Results are shown on the team dashboard.",
        "Multi-language support and follow-ups are added on the Pro plan.",
      ],
      relatedFeatures: ["projects-tasks", "meeting-assistant"],
      sources: [`${MM}/`],
      highlight: true,
      hasPage: true,
    },
    {
      slug: "projects-tasks",
      name: "Assigned action items",
      summary: "Tasks agreed in a meeting are picked out with owners and due dates and added to each teammate's task list.",
      category: "features",
      body: [
        "MeetingMind picks out the tasks agreed in a meeting, gives each one an owner and a due date, and sends it to that teammate's task list, so nobody has to chase action items after the call.",
      ],
      problem: "Action items agreed on a call often have no clear owner or deadline, so they slip until someone chases them.",
      howItWorks: [
        "The meeting is captured and analysed.",
        "Tasks agreed in the conversation are picked out.",
        "Each task gets an owner and a due date.",
        "Tasks are added to each teammate's list on their dashboard.",
      ],
      capabilities: ["Tasks picked out from the meeting", "Owner assigned to each task", "Due dates on tasks", "Tasks added to each teammate's list"],
      relatedFeatures: ["meeting-summaries", "team-workspace"],
      sources: [`${MM}/`],
      highlight: true,
      hasPage: true,
    },
    {
      slug: "meeting-assistant",
      name: "Ask your meetings",
      summary: "An assistant answers questions using every past meeting in the workspace and names the meeting each answer came from.",
      category: "features",
      body: [
        "The assistant lets anyone in the workspace ask a question (for example, what was decided on a topic) and get an answer drawn from every past meeting.",
        "MeetingMind describes it as grounded, meaning answers are based on your meetings and cite the meeting they came from. The plans call it a RAG assistant (one that looks up your records before answering), and it is included on the Free plan.",
      ],
      problem: "Finding what was said in an old meeting usually means asking around or rewatching recordings.",
      howItWorks: [
        "Ask a question in plain language, such as what was decided on a topic.",
        "The assistant searches across every past meeting in the workspace.",
        "It answers and cites the meeting the answer came from.",
      ],
      capabilities: ["Questions answered across every past meeting", "Answers cite their source", "Available to the whole team", "Included on the Free plan"],
      relatedFeatures: ["transcripts", "meeting-summaries"],
      sources: [`${MM}/`],
      highlight: true,
      hasPage: true,
    },
    {
      slug: "transcripts",
      name: "Searchable transcripts",
      summary: "Transcripts showing who spoke and when, in the meeting's language, that can be searched, exported and shared.",
      category: "features",
      body: [
        "Every captured meeting gets a full transcript, labelled by speaker and timestamped, in the language the meeting was held in.",
        "Transcripts can be searched, exported and shared across the team, and the site describes the transcript as live.",
      ],
      capabilities: ["Speaker labels", "Timestamps", "Transcript in the meeting's own language", "Search", "Export and sharing across the team"],
      relatedFeatures: ["speaker-analytics", "meeting-assistant"],
      sources: [`${MM}/`],
      hasPage: true,
    },
    { slug: "team-workspace", name: "Team workspace", summary: "Owners, managers and members share one company workspace, and what each person sees changes with their role.", category: "features", sources: [`${MM}/`], hasPage: false },
    { slug: "speaker-analytics", name: "Speaker analytics", summary: "Shows who spoke in a meeting and for how long, alongside the speaker-labelled transcript.", category: "features", sources: [`${MM}/`], hasPage: false },
    { slug: "browser-extension", name: "Browser extension", summary: "Listed on the site as a browser extension that captures meetings from any browser tab; no download link is published.", category: "features", sources: [`${MM}/`], hasPage: false },
    { slug: "calendar-sync", name: "Upcoming meetings", summary: "Upcoming meetings are synced from your calendar; the site does not say which calendar services are supported.", category: "features", sources: [`${MM}/`], hasPage: false },
    { slug: "ai-project-manager", name: "AI Project Manager", summary: "A Premium module that turns recurring project meetings into live status, risks and blockers without anyone updating a tracker.", category: "premium", sources: [`${MM}/`], hasPage: false },
    { slug: "client-intelligence", name: "Client Intelligence", summary: "A Premium module that keeps a running history of every client conversation, with promises made, the client's mood and open issues in one place.", category: "premium", sources: [`${MM}/`], hasPage: false },
    { slug: "sales-intelligence", name: "Sales Intelligence", summary: "A Premium module that picks out buying signals, objections and next steps from sales calls, so your sales pipeline stays realistic.", category: "premium", sources: [`${MM}/`], hasPage: false },
    { slug: "recruitment-analyzer", name: "Recruitment Analyzer", summary: "A Premium module that creates organised interview reports and candidate comparisons from hiring conversations.", category: "premium", sources: [`${MM}/`], hasPage: false },
  ],
  // Pricing deliberately omitted: the site says prices are "set by your MeetingMind operator" (template-like),
  // alongside placeholder testimonials. Open decision in docs/verification/README.md; add once confirmed.
  sources: [`${MM}/`],
  lastVerified: "2026-10-08",
};
