import type { Product } from "@/content/types";
import { featureSet, group } from "./_helpers";

export const sibu: Product = {
  id: "sibu",
  slug: "sibu",
  name: "Sibu",
  shortDescription:
    "A digital asset library for creative teams — every video, image and document indexed with AI, searchable and reviewable in one place.",
  longDescription:
    "Sibu ingests media from cloud drives, local servers and uploads, tags it with AI vision, and makes it searchable by objects, text inside documents and meaning. Teams comment directly on timelines, approve and version assets, and control access with folder-level permissions.",
  tagline: "The operating system for your creative library",
  category: "sales-marketing",
  subcategory: "creative-operations",
  primaryUseCase: "Organising and searching creative assets",
  audience: ["Video teams", "Marketing teams", "Agencies", "Brand teams"],
  platforms: ["web"],
  market: "Global",
  status: "live",
  verification: { relationship: "pending", publicSale: "confirmed" },
  featured: true,
  websiteUrl: "https://getsibu.com/",
  appUrl: "https://getsibu.com/signup",
  ...featureSet(
    group(
      "Core",
      [
        ["Auto-ingest from anywhere", "Bring in media from Drive, local servers and uploads."],
        ["AI-assisted tagging", "Assets are tagged automatically by what they contain."],
        ["Search by anything", "Find assets by filename, tag, text or meaning."],
        ["Comments in context", "Comment on the asset itself, pinned to the timeline for video."],
        ["Taxonomies that scale", "Structure your library as it grows."],
        ["Granular permissions", "Folder-scoped access from managers to teams."],
        ["Insightful analytics", "See what the library and team need attention on."],
        ["Multi-tenant by design", "Workspaces are isolated from each other."],
        ["Built for speed", "Designed for large libraries."],
      ],
      { highlight: 5 },
    ),
    group("AI", [
      ["Scene detection", "Find the moment you need inside a video."],
      ["Face grouping", "Group assets by the people in them."],
      ["OCR extraction", "Search the text inside images and documents."],
      ["Semantic search", "Search by meaning, not just keywords."],
      ["Duplicate detection", "Spot repeated assets."],
      ["Auto collections", "Collections assembled from tags automatically."],
    ]),
    group("Collaboration", [
      ["@-mentions", "Bring teammates into a conversation on an asset."],
      ["Approvals", "Review and approval workflows."],
      ["Versioning", "Keep every version of an asset."],
      ["Activity history", "A per-asset record of what happened."],
    ]),
    group("Developers", [
      ["REST API", "OpenAPI 3.1 documented API."],
      ["SDKs", "TypeScript, Python and Go."],
      ["Webhooks", "React to library events in your own systems."],
      ["CLI and API playground", "Try and script the API."],
    ]),
    group("Migration", [
      ["Bulk import", "Move an existing library in."],
      ["Metadata preserved", "Keep existing context when migrating."],
      ["Folder mapping", "Map your current folder structure."],
      ["Onboarding included", "Help getting the library set up."],
    ]),
    group("Security", [
      ["AES-256 at rest", "Stored assets are encrypted."],
      ["Audit logs everywhere", "Actions are logged across the library."],
      ["RBAC and tenant isolation", "Role-based access, isolated per workspace."],
      ["SSO and SCIM", "Single sign-on and user provisioning."],
      ["Default-deny access", "Nothing is shared until access is granted."],
      ["Backup redundancy", "Redundant backups of the library."],
    ]),
  ),
  howItWorks: [
    { title: "Connect", description: "Link your drives and storage." },
    { title: "Ingest", description: "Sibu scans and indexes every asset." },
    { title: "Organise", description: "AI tags and your taxonomies structure the library." },
    { title: "Collaborate", description: "Search, comment, approve and share." },
  ],
  integrations: ["google-drive", "dropbox", "onedrive", "aws-s3", "slack", "figma", "zapier", "frame-io", "adobe-premiere-pro", "adobe-after-effects"],
  pricing: {
    currency: "USD",
    unit: "month",
    trial: "3-day Pro trial, no card required",
    note: "Plans are billed monthly or annually. Live prices on Sibu's site may change.",
    asOf: "2026-10-07",
    sourceUrl: "https://getsibu.com/pricing",
    plans: [
      { name: "Free", price: "$0", description: "For makers exploring Sibu", features: ["5 GB storage", "3 seats", "Search & tags"], cta: { label: "Start free", href: "https://getsibu.com/signup" } },
      { name: "Pro", price: "$99", period: "month", description: "For growing creative teams", features: ["500 GB storage", "20 seats", "Google Drive sync", "Threaded comments + mentions"], cta: { label: "Start trial", href: "https://getsibu.com/signup" }, recommended: true },
      { name: "Business", price: "$299", period: "month", description: "For studios shipping at scale", features: ["2 TB storage", "100 seats", "SSO & SCIM", "Priority support"], cta: { label: "Talk to sales", href: "https://getsibu.com/contact" } },
    ],
  },
  supportUrl: "https://getsibu.com/contact",
  useCases: [
    { title: "Video teams", description: "Find the right moment with scene detection and leave comments pinned to the exact point on the timeline." },
    { title: "Marketing teams", description: "Find approved assets by what's in them, not by guessing filenames." },
    { title: "Agencies", description: "Keep each client's library isolated in its own workspace." },
    { title: "Brand teams", description: "Control what's used with approvals, versioning and folder-level permissions." },
  ],
  faqs: [
    { question: "Can Sibu be self-hosted?", answer: "Self-hosting is available on the Business and Enterprise plans." },
    { question: "Are AI features included?", answer: "AI features are included from the Pro plan; on Pro you connect your own OpenAI key." },
    { question: "How is Sibu billed?", answer: "Monthly or annually." },
  ],
  industries: ["media-creative-agencies"],
  sources: ["https://getsibu.com/", "https://getsibu.com/features", "https://getsibu.com/pricing"],
  lastVerified: "2026-10-07",
};
