import type { Feature, FeatureCategory, Product } from "@/content/types";

const HOME = "https://sigchanger.com/";
const FEATURES = "https://sigchanger.com/features";
const ABOUT = "https://sigchanger.com/about-us";
const PRIVACY = "https://sigchanger.com/privacy-policy";
const TERMS = "https://sigchanger.com/terms-of-service";
const PRICING = "https://sigchanger.com/pricing";

const featureCategories: FeatureCategory[] = [
  {
    slug: "core-capabilities",
    name: "Core Capabilities",
    description: "Every step of Gmail signature management, from user sync to one-click deployment.",
    body: [
      "SigChanger's core capabilities cover each step of managing Gmail signatures: importing users from Google Workspace, designing signatures visually, locking them to the brand, scheduling changes and deploying them to every mailbox.",
      "Credentials behind these steps are encrypted at rest, and each company works through its own Google Cloud service account.",
    ],
  },
  {
    slug: "automation-at-scale",
    name: "Automation At Scale",
    description: "SigChanger runs in the background so IT teams can get on with other work.",
    body: [
      "SigChanger describes this group as set-and-forget: once configured, it keeps running in the background so the IT team can focus on other work.",
      "Directory changes reach signatures within minutes, templates are assigned by group automatically, a template edit updates everyone who uses it, and alerts flag anything that fails.",
    ],
  },
  {
    slug: "full-control",
    name: "Full Control",
    description: "Tools that give IT teams visibility and control over every signature.",
    body: [
      "The full-control tools give IT teams visibility over every signature in the organisation: a central asset library, a real-time dashboard, audit logs, multi-company management and time-zone-aware rollouts.",
      "They sit on SigChanger's privacy-first architecture, in which each company keeps its own service account and is isolated from every other company.",
    ],
  },
];

const features: Feature[] = [
  {
    slug: "google-workspace-sync",
    name: "Google Workspace Sync",
    summary: "Import every user from your Google Workspace directory and keep them in sync automatically.",
    category: "core-capabilities",
    highlight: true,
    hasPage: true,
    body: [
      "SigChanger connects to your Google Workspace domain through a Google Cloud service account that your company provides. Once connected, it imports your whole user directory, so there is no list of employees to build by hand.",
      "After the first import the directory stays in sync: new hires are picked up from day one, role changes flow through to their signatures, and people who leave are handled automatically.",
      "The user attributes SigChanger reads (first and last name, email, job title, department and contact number) are used only to render and deploy signatures.",
    ],
    howItWorks: [
      "Link your Google Workspace domain using your own Google Cloud service account.",
      "SigChanger imports your entire user directory.",
      "Directory changes such as new hires, role changes and departures are synced to SigChanger automatically.",
      "Signatures are kept aligned with the current directory data.",
    ],
    capabilities: [
      "Automatic import of every user in the Workspace directory",
      "New hires picked up on day one; offboarding handled automatically",
      "Role and title changes reflected in signatures",
      "Reads name, email, title, department and phone to fill signature fields",
      "Reads delegated group membership where it is needed for targeting",
      "Auto-sync runs daily on the Basic plan and hourly on Professional and Enterprise",
      "Access can be revoked at any time by disconnecting Workspace or rotating the service-account key",
    ],
    benefits: [
      "No manual user lists to maintain",
      "Signatures stay accurate as people join, move and leave",
    ],
    audience: ["Google Workspace admins", "IT teams"],
    integrations: ["google-workspace"],
    relatedFeatures: ["real-time-sync", "visual-signature-builder", "privacy-first-security"],
    sources: [HOME, FEATURES, PRIVACY, TERMS, PRICING],
    faqs: [
      {
        question: "How does Google Workspace sync work?",
        answer: "SigChanger connects to your Workspace directory through a service account, imports your user data automatically and keeps signatures in sync as your team changes.",
      },
      {
        question: "Can I disconnect SigChanger from Google Workspace?",
        answer: "Yes. Disconnect Google Workspace in the SigChanger admin panel or rotate the service-account key in Google Cloud. Revocation is immediate, and the stored service-account credentials are deleted when you disconnect.",
      },
    ],
  },
  {
    slug: "visual-signature-builder",
    name: "Visual Signature Builder",
    summary: "A drag-and-drop editor with live preview, with no HTML required.",
    category: "core-capabilities",
    highlight: true,
    hasPage: true,
    body: [
      "The Visual Signature Builder is a drag-and-drop editor for designing Gmail signatures, with a live preview of the result as you build it. Nobody needs to write or edit HTML.",
      "Templates use dynamic fields, so one design works for everyone: each person's name, title, phone number and photo are filled in automatically from their user record.",
    ],
    capabilities: [
      "Drag-and-drop signature editor",
      "Live preview while designing",
      "Dynamic fields that auto-fill name, title, phone and photo per user",
      "No HTML knowledge required",
      "Included on every plan, including Free",
    ],
    audience: ["IT teams", "Brand and marketing teams"],
    relatedFeatures: ["brand-locked-templates", "multi-template-support", "asset-library"],
    sources: [HOME, FEATURES, PRICING],
  },
  {
    slug: "one-click-deployment",
    name: "One-Click Deployment",
    summary: "Push signatures to every mailbox, or to selected teams, in a single click.",
    category: "core-capabilities",
    highlight: true,
    hasPage: true,
    body: [
      "Once a signature is ready, SigChanger pushes it to the whole organisation or to selected teams with one click. Deployment runs server-side through the Gmail API, which updates each user's Gmail send-as signature settings directly.",
      "Employees don't have to copy, paste or install anything: no user action is involved.",
    ],
    problem:
      "Without central deployment, employees end up with inconsistent, outdated or missing signatures, and IT teams spend hours they don't have trying to fix it.",
    howItWorks: [
      "Choose the whole organisation or selected teams.",
      "Click to deploy.",
      "SigChanger updates each user's Gmail signature server-side through the Gmail API.",
    ],
    capabilities: [
      "Deploy to the entire organisation or selected teams",
      "Server-side updates through the Gmail API",
      "Writes Gmail send-as signature settings for users in your domain",
      "No copying or action needed from employees",
    ],
    benefits: ["Removes manual signature setup for every employee", "Brand-consistent signatures across every mailbox at once"],
    audience: ["Google Workspace admins", "IT teams"],
    integrations: ["google-workspace"],
    relatedFeatures: ["scheduled-rollouts", "instant-updates", "smart-notifications"],
    sources: [HOME, FEATURES, ABOUT, TERMS],
  },
  {
    slug: "scheduled-rollouts",
    name: "Scheduled Rollouts",
    summary: "Plan signature changes for specific dates and times, for rebrands, campaigns and compliance updates.",
    category: "core-capabilities",
    highlight: true,
    hasPage: true,
    body: [
      "Scheduled Rollouts let admins plan signature changes ahead of time instead of switching them by hand on the day. A rollout can be set for a specific date and time.",
      "SigChanger positions this for rebrands, seasonal campaigns, promotional pushes and compliance updates, including rollouts that need to land across multiple time zones.",
    ],
    howItWorks: [
      "Assign a template to teams, departments or individual users.",
      "Choose the date and time the rollout should happen.",
      "SigChanger deploys the signatures at the scheduled time.",
    ],
    capabilities: [
      "Schedule deployments for specific dates and times",
      "Target teams, departments or individual users",
      "Coordinate rollouts across multiple time zones",
    ],
    useCases: [
      { title: "Rebrands", description: "Switch every signature to the new brand when the rebrand goes live." },
      { title: "Seasonal and promotional campaigns", description: "Put a campaign into signatures on a planned date." },
      { title: "Compliance updates", description: "Roll out required changes across the organisation on schedule." },
    ],
    audience: ["IT teams", "Brand and marketing teams"],
    relatedFeatures: ["global-deployment", "one-click-deployment", "group-rules"],
    sources: [HOME, FEATURES],
    faqs: [
      {
        question: "Can I schedule signature deployments?",
        answer: "Yes. Rollouts can be scheduled for specific dates and times, for example for rebrands, seasonal campaigns or promotional pushes.",
      },
    ],
  },
  {
    slug: "aes-256-cbc-encryption",
    name: "AES-256-CBC Encryption",
    summary: "Credentials are encrypted at rest with AES-256-CBC, and data travels over TLS.",
    category: "core-capabilities",
    hasPage: true,
    body: [
      "SigChanger encrypts every credential at rest with AES-256-CBC. The most sensitive one is the private key of the Google Cloud service account each company connects: it is encrypted before it is written to storage and decrypted in memory only when SigChanger has to call the Gmail or Directory API.",
      "Sensitive fields are encrypted at rest too, all traffic travels over HTTPS/TLS, and administrator passwords are stored as bcrypt hashes rather than in readable form.",
    ],
    capabilities: [
      "The service account's private key is encrypted with AES-256-CBC before it is stored.",
      "The key is decrypted in memory only for the moment a Gmail or Directory API call needs it.",
      "Sensitive fields in SigChanger's databases are encrypted at rest.",
      "Data in transit is protected with HTTPS/TLS.",
      "Administrator passwords are stored as bcrypt hashes.",
      "Stored service-account credentials are deleted immediately when Google Workspace is disconnected.",
    ],
    audience: ["IT teams", "Google Workspace admins"],
    faqs: [
      { question: "Can SigChanger staff read our credentials?", answer: "SigChanger states that neither its staff nor the platform owner has direct access to decrypted credentials." },
      { question: "What happens to the encrypted key when we disconnect?", answer: "The stored service-account credentials are deleted immediately when Google Workspace is disconnected." },
    ],
    relatedFeatures: ["privacy-first-security", "google-workspace-sync", "audit-logs"],
    sources: [HOME, FEATURES, PRIVACY],
  },
  {
    slug: "brand-locked-templates",
    name: "Brand-Locked Templates",
    summary: "Colours, fonts, logos and layouts stay on-brand, and users can't accidentally break them.",
    category: "core-capabilities",
    hasPage: true,
    body: [
      "Brand-Locked Templates are how SigChanger enforces brand consistency across every signature. The template defines the colours, fonts, logos and layout, and employees can't accidentally break them.",
      "SigChanger lists brand-locked signatures that stay on-message among the commitments it makes to customers, and its setup starts with registering the company's brand colours alongside its domain and details.",
    ],
    capabilities: [
      "Colours locked to the brand",
      "Fonts locked to the brand",
      "Logos locked to the brand",
      "Layouts that users can't accidentally break",
    ],
    audience: ["Brand and marketing teams", "IT teams"],
    relatedFeatures: ["visual-signature-builder", "multi-template-support"],
    sources: [FEATURES, ABOUT],
  },
  {
    slug: "multi-template-support",
    name: "Multi-Template Support",
    summary: "Different signature templates for different teams or use cases.",
    category: "core-capabilities",
    hasPage: true,
    body: [
      "SigChanger is not limited to one company-wide signature. Admins can create different templates for different teams or use cases, and pick the right template for each user when their signature is generated.",
      "The template a person uses can be changed at any time, and templates can be assigned to whole departments, teams or roles rather than one user at a time.",
    ],
    capabilities: [
      "Multiple templates for different teams or use cases",
      "Choose the template per user when generating their signature",
      "Change a user's template at any time",
      "Assign templates by department, team or role",
      "Template allowance by plan: 2 (Free), 10 (Basic), 25 (Professional), 100 (Enterprise)",
    ],
    relatedFeatures: ["group-rules", "brand-locked-templates", "visual-signature-builder"],
    sources: [HOME, FEATURES, PRICING],
  },
  {
    slug: "real-time-sync",
    name: "Real-Time Sync",
    summary: "Directory changes reflect across all signatures within minutes.",
    category: "automation-at-scale",
    hasPage: true,
    body: [
      "Real-Time Sync keeps signatures in step with the Google Workspace directory. When someone joins, changes title or department, or leaves, SigChanger picks the change up and it is reflected across signatures within minutes.",
      "Automatic re-syncing depends on the plan: the Basic plan auto-syncs daily, while Professional and Enterprise auto-sync hourly.",
    ],
    capabilities: [
      "Directory changes are reflected across all signatures within minutes.",
      "New hires are picked up and get a signature from day one.",
      "Role and title changes flow through to the fields shown in signatures.",
      "Departures are handled automatically without editing a user list.",
      "Automatic sync runs daily on Basic and hourly on Professional and Enterprise.",
    ],
    audience: ["IT teams", "Google Workspace admins"],
    integrations: ["google-workspace"],
    relatedFeatures: ["google-workspace-sync", "instant-updates", "smart-notifications"],
    sources: [HOME, FEATURES, PRICING],
  },
  {
    slug: "group-rules",
    name: "Group Rules",
    summary: "Assign different templates by department, team or role automatically.",
    category: "automation-at-scale",
    hasPage: true,
    body: [
      "Group Rules let admins decide which signature template each part of the organisation uses without assigning it person by person. A template can be tied to a department, a team or a role, and SigChanger applies it automatically.",
      "To target groups, SigChanger reads delegated group membership from Google Workspace where it is needed; it can still assign a template to an individual user when one person needs something different.",
    ],
    capabilities: [
      "Templates are assigned automatically by department, team or role.",
      "Individual users can still be given their own template.",
      "Delegated Google Workspace group membership is read where targeting needs it.",
      "Group assignments combine with scheduled rollouts for dated changes.",
    ],
    audience: ["IT teams", "Google Workspace admins"],
    relatedFeatures: ["multi-template-support", "scheduled-rollouts", "google-workspace-sync"],
    sources: [HOME, FEATURES, TERMS],
  },
  {
    slug: "instant-updates",
    name: "Instant Updates",
    summary: "Change a template once and every employee's signature updates.",
    category: "automation-at-scale",
    hasPage: true,
    body: [
      "SigChanger is built so a signature change is made in one place. When a template is edited, every employee whose signature uses it is updated, rather than each person being changed one at a time.",
      "The same applies to brand assets and directory data: an updated logo or banner in the Asset Library rolls out without a re-deployment, and directory changes reach signatures within minutes.",
    ],
    capabilities: [
      "Edit a template once and every employee's signature using it updates",
      "Asset Library updates roll out across signatures with no re-deployment",
      "Directory changes reflected across signatures within minutes",
    ],
    relatedFeatures: ["asset-library", "real-time-sync", "one-click-deployment"],
    sources: [FEATURES],
  },
  {
    slug: "smart-notifications",
    name: "Smart Notifications",
    summary: "Alerts for failed deployments, sync issues and approaching plan limits.",
    category: "automation-at-scale",
    hasPage: true,
    body: [
      "Smart Notifications tell admins when something needs attention instead of leaving them to find it. SigChanger sends alerts for failed deployments, sync issues and approaching plan limits.",
      "Plan limits are a clear example: you are notified as you approach your user or template quota and can upgrade at any time, and existing data is never deleted because a limit was reached.",
    ],
    capabilities: [
      "Alerts for failed deployments",
      "Alerts for sync issues",
      "Alerts when approaching plan limits",
      "Transactional emails for billing, security alerts and ticket notifications",
    ],
    audience: ["IT teams", "Google Workspace admins"],
    relatedFeatures: ["admin-dashboard", "one-click-deployment", "google-workspace-sync"],
    sources: [HOME, FEATURES, PRIVACY, TERMS],
  },
  {
    slug: "asset-library",
    name: "Asset Library",
    summary: "Manage logos, banners, headshots, social icons and other images centrally: upload once, use everywhere.",
    category: "full-control",
    hasPage: true,
    body: [
      "The Asset Library is a central store for every brand asset that appears in signatures: company logos, email banners, employee headshots, social icons and other custom images.",
      "Each asset is uploaded once and referenced from templates wherever it's needed. When an asset is updated, the change rolls out across every signature that uses it, without a re-deployment.",
    ],
    capabilities: [
      "Central storage for logos, email banners, headshots, social icons and custom images",
      "Upload once, reference from any template",
      "Asset updates roll out across all signatures with no re-deployment",
      "Uploaded images and logos are kept in secure storage",
    ],
    audience: ["Brand and marketing teams", "IT teams"],
    relatedFeatures: ["visual-signature-builder", "instant-updates"],
    sources: [FEATURES, PRIVACY],
  },
  {
    slug: "privacy-first-security",
    name: "Privacy-First Security",
    summary: "Each company uses its own Google Cloud service account, and SigChanger can't access your data.",
    category: "full-control",
    hasPage: true,
    body: [
      "SigChanger is built so that your Google Workspace credentials stay under your control. Each company connects its own Google Cloud service account, and the architecture is designed so that neither SigChanger staff nor the platform owner can access customer data.",
      "The service account's private key is encrypted with AES-256-CBC before it is stored and is decrypted in memory only when SigChanger needs to call the Gmail or Directory API. Data is encrypted with TLS in transit.",
    ],
    capabilities: [
      "Your own Google Cloud service account per company",
      "AES-256-CBC encryption at rest; TLS in transit",
      "No staff or owner access to decrypted credentials",
      "Strict multi-tenant isolation between companies",
      "Role-based access (Super Admin, Company Admin, Employee) enforced at the API layer",
      "Short-lived JWT access tokens with rotating refresh tokens",
      "Rate limiting, request validation and audit logging on sensitive endpoints",
    ],
    benefits: ["You keep ownership of your credentials", "Access can be revoked at any time from your side"],
    audience: ["IT teams", "Google Workspace admins"],
    integrations: ["google-workspace"],
    relatedFeatures: ["aes-256-cbc-encryption", "audit-logs", "multi-company-support"],
    sources: [FEATURES, ABOUT, PRIVACY, TERMS],
    faqs: [
      {
        question: "How secure is my data?",
        answer: "All credentials are encrypted with AES-256-CBC, and each company uses its own Google Cloud service account, so SigChanger never stores or accesses your Workspace data directly.",
      },
    ],
  },
  {
    slug: "multi-company-support",
    name: "Multi-Company Support",
    summary: "Manage signatures for multiple domains and subsidiaries from one admin console.",
    category: "full-control",
    hasPage: true,
    body: [
      "Organisations with more than one domain or subsidiary can manage all of their signatures from a single SigChanger admin console.",
      "Each entity keeps its own branding, templates and users, and every company on the platform is isolated from the others: separate users, templates, signatures and encrypted credentials.",
    ],
    capabilities: [
      "Multiple domains and subsidiaries in one admin console",
      "Separate branding per entity",
      "Separate templates and users per entity",
      "Isolation between companies, including their encrypted credentials",
    ],
    useCases: [
      { title: "Groups of companies", description: "Run signatures for several domains or subsidiaries, each with its own brand." },
    ],
    relatedFeatures: ["admin-dashboard", "privacy-first-security"],
    sources: [FEATURES, ABOUT],
  },
  {
    slug: "admin-dashboard",
    name: "Admin Dashboard",
    summary: "A real-time overview of deployment status, sync health and signature compliance.",
    category: "full-control",
    hasPage: true,
    body: [
      "The Admin Dashboard is the single place admins use to see what is happening across their Google Workspace signatures.",
      "It shows deployment status, sync health and signature compliance across every user in real time, so usage can be tracked and problems spotted at a glance.",
    ],
    capabilities: [
      "Real-time deployment status",
      "Sync health overview",
      "Signature compliance across every user",
      "Usage tracking and issue identification",
    ],
    audience: ["Google Workspace admins", "IT teams"],
    relatedFeatures: ["smart-notifications", "audit-logs", "multi-company-support"],
    sources: [FEATURES, ABOUT],
  },
  {
    slug: "audit-logs",
    name: "Audit Logs",
    summary: "Every action logged (who changed what, when and where) for compliance and security audits.",
    category: "full-control",
    hasPage: true,
    body: [
      "SigChanger logs every action so admins can answer who changed what, when and where. It positions the log for compliance work, regulated industries and security audits.",
      "Audit logging also forms part of SigChanger's security practices: its privacy policy lists audit logging, rate limiting and request validation on every sensitive endpoint.",
    ],
    capabilities: [
      "Every action logged",
      "Records who changed what, when and where",
      "Audit logging on every sensitive endpoint",
      "Supports compliance reviews and security audits",
    ],
    audience: ["IT teams", "Google Workspace admins"],
    relatedFeatures: ["admin-dashboard", "privacy-first-security"],
    sources: [FEATURES, PRIVACY],
  },
  {
    slug: "global-deployment",
    name: "Global Deployment",
    summary: "Schedule rollouts to reach specific regions at the right local time.",
    category: "full-control",
    hasPage: true,
    body: [
      "Global Deployment is for organisations whose people sit in several time zones. Instead of one switch-over that lands at midnight for some offices and mid-afternoon for others, rollouts are coordinated across time zones.",
      "Deployments can be scheduled so that each region receives the new signature at the right local time, building on SigChanger's date-and-time scheduling.",
    ],
    capabilities: [
      "Signature rollouts are coordinated across multiple time zones.",
      "Deployments can be scheduled to reach specific regions at the right local time.",
      "Rollouts are set for a specific date and time in advance.",
      "Targets can be teams, departments or individual users.",
    ],
    useCases: [
      { title: "A rebrand across offices", description: "Switch every office to the new brand at the same local hour rather than at one global instant." },
    ],
    audience: ["IT teams", "Brand and marketing teams"],
    relatedFeatures: ["scheduled-rollouts", "one-click-deployment", "multi-company-support"],
    sources: [HOME, FEATURES],
  },
];

export const sigchanger: Product = {
  id: "sigchanger",
  slug: "sigchanger",
  name: "SigChanger",
  shortDescription:
    "Design Gmail signatures once and roll them out to everyone in your Google Workspace — consistent branding with no manual setup.",
  longDescription:
    "SigChanger connects to Google Workspace, imports your users, and lets admins design brand-locked signature templates in a visual builder. Signatures are assigned by group, scheduled for campaigns or rebrands, and deployed to every mailbox in one step — with audit logs and multi-company support for larger organisations.\n\nIt is built only for Gmail in Google Workspace. Each company connects its own Google Cloud service account; SigChanger reads the directory fields a signature needs — name, email, job title, department and phone — and writes each user's Gmail send-as signature on the server side, so employees don't copy or install anything.\n\nOnce set up it keeps running in the background: new hires, role changes and departures flow through from the directory, a template edit updates everyone who uses it, and alerts flag failed deployments, sync issues and approaching plan limits. A Free plan with no time limit covers up to 10 users and 2 templates; paid plans add users, templates and automatic sync.",
  tagline: "Turn Gmail Into Brand Ambassadors",
  category: "operations-it",
  subcategory: "it-administration",
  primaryUseCase: "Centrally managed Gmail signatures",
  audience: ["Google Workspace admins", "IT teams", "Brand & marketing teams"],
  platforms: ["web"],
  market: "Global",
  status: "live",
  verification: { relationship: "pending", publicSale: "confirmed" },
  featured: true,
  websiteUrl: "https://sigchanger.com/",
  appUrl: "https://sigchanger.com/signup",
  featureCategories,
  features,
  productIntegrations: [
    {
      slug: "google-workspace",
      name: "Google Workspace",
      summary: "SigChanger works through your own Google Cloud service account. It reads your Workspace directory and writes Gmail signatures for your domain.",
      connects:
        "SigChanger is built only for Google Workspace. It acts through a Google Cloud service account that your company provides, uses the Directory API to import and sync users, and uses the Gmail API to write each user's send-as signature on the server side.",
      body: [
        "The connection only grants the permissions needed to render and deploy signatures. Your company can revoke it at any time from its own side.",
      ],
      setup: [
        "Register your company with your domain, brand colours and company details.",
        "Connect your Google Workspace domain using your own Google Cloud service account.",
        "SigChanger imports your user directory, and the directory then stays in sync.",
      ],
      workflow: [
        "Reads the directory data a signature needs: name, email, job title, department and phone.",
        "Reads delegated group membership where it is needed for targeting.",
        "Writes and updates Gmail send-as signature settings for users in your domain.",
        "Encrypts the service account's private key with AES-256-CBC and decrypts it in memory only when it calls the Gmail or Directory API.",
      ],
      benefits: [
        "No manual user lists to keep up to date",
        "Employees don't have to do anything for signatures to reach their Gmail",
        "Credentials stay under your company's control",
      ],
      registry: "google-workspace",
      features: ["google-workspace-sync", "one-click-deployment", "privacy-first-security", "real-time-sync"],
      faqs: [
        {
          question: "Can I disconnect SigChanger from Google Workspace?",
          answer: "Yes. You can disconnect in the SigChanger admin panel or rotate the service-account key in Google Cloud. Revocation takes effect immediately and the stored credentials are deleted. Signatures that were already deployed stay in place unless you choose to clear them.",
        },
      ],
      sources: [HOME, PRIVACY, TERMS],
    },
  ],
  productSolutions: [
    {
      slug: "consistent-company-wide-branding",
      name: "Consistent company-wide email branding",
      summary: "Keep every Gmail signature in the organisation accurate, consistent and on-brand from one place.",
      problem:
        "SigChanger calls Gmail signatures the most overlooked branding touchpoint in an organisation: employees send emails every week with inconsistent, outdated or missing signatures.",
      body: [
        "SigChanger gives administrators one place to design, schedule and deploy brand-locked signatures across every mailbox, so each email the company sends carries the same brand.",
      ],
      approach: [
        "Register brand colours and company details when the company is set up.",
        "Design one template in the visual builder; dynamic fields fill each person's details.",
        "Lock colours, fonts, logos and layout so users can't break them.",
        "Keep logos, banners and headshots in the Asset Library and update them centrally.",
        "Deploy to every mailbox in one click through the Gmail API.",
      ],
      audience: ["Brand and marketing teams", "IT teams"],
      features: ["brand-locked-templates", "visual-signature-builder", "asset-library", "one-click-deployment", "instant-updates"],
      sources: [ABOUT, HOME, FEATURES],
    },
    {
      slug: "signature-management-for-it-teams",
      name: "Signature administration for IT teams",
      summary: "Remove the manual work of setting up and fixing employee signatures across Google Workspace.",
      problem:
        "SigChanger says IT teams spend hours they don't have fixing inconsistent, outdated or missing signatures.",
      body: [
        "SigChanger aims to remove every manual step between the user directory and the mailbox, so it runs in the background and IT teams can focus on other work.",
      ],
      approach: [
        "Import and sync users from Google Workspace, including new hires, role changes and departures.",
        "Assign templates by department, team or role.",
        "Deploy server-side through the Gmail API with no action from employees.",
        "Monitor deployment status, sync health and compliance on the Admin Dashboard.",
        "Get alerts for failed deployments, sync issues and approaching limits.",
        "Track who changed what in the audit logs.",
      ],
      audience: ["IT teams", "Google Workspace admins"],
      features: ["google-workspace-sync", "multi-template-support", "one-click-deployment", "admin-dashboard", "smart-notifications", "audit-logs"],
      sources: [ABOUT, FEATURES, HOME],
    },
  ],
  supportTopics: [
    {
      slug: "getting-started",
      name: "Getting started with SigChanger",
      summary: "How to go from registering your company to deploying signatures for the first time.",
      body: [
        "SigChanger describes its setup as six steps. The service account and the directory import do most of the work, so you don't have to set anyone up by hand.",
      ],
      steps: [
        "Register your company and add your domain, brand colours and company details.",
        "Connect Google Workspace using a secure service account.",
        "Let SigChanger import your employees. New hires and leavers are then handled automatically.",
        "Design a signature in the drag-and-drop builder, using dynamic fields for each person's details.",
        "Assign templates to teams, departments or individual users, and schedule rollouts if you need to.",
        "Deploy to everyone, or to the teams you select, with one click.",
      ],
      features: ["google-workspace-sync", "visual-signature-builder", "scheduled-rollouts", "one-click-deployment"],
      faqs: [
        {
          question: "Can I start for free?",
          answer: "Yes. The Free plan has no time limit and does not need a credit card. The Pricing page lists its current user and template limits.",
        },
      ],
      sources: [HOME, PRICING],
    },
    {
      slug: "revoking-workspace-access",
      name: "Revoking Google Workspace access",
      summary: "What happens when you disconnect Google Workspace or rotate your service-account key.",
      body: [
        "Your company stays in control of the connection between SigChanger and Google Workspace and can withdraw it at any time.",
      ],
      steps: [
        "Disconnect Google Workspace in the SigChanger admin panel, or rotate the service-account key in Google Cloud.",
        "Revocation takes effect immediately.",
        "When you disconnect, the stored service-account credentials are deleted immediately.",
        "Signatures that were already deployed stay in Gmail unless you choose to clear them.",
      ],
      features: ["google-workspace-sync", "privacy-first-security"],
      sources: [PRIVACY, TERMS],
    },
    {
      slug: "plan-limits",
      name: "Plan limits and upgrades",
      summary: "How user and template quotas work, and what happens when you reach one.",
      body: [
        "Each plan has quotas, such as the maximum number of users and templates. These are shown in the app and on the pricing page.",
      ],
      keyPoints: [
        "You're notified as you approach a limit.",
        "At the limit, you can't add new records beyond the quota until you upgrade.",
        "Existing data is never deleted because you reached a limit.",
        "You can upgrade at any time to get more users, templates and features.",
        "Fair use rules forbid getting around plan limits or putting unreasonable load on the service.",
      ],
      features: ["smart-notifications", "multi-template-support"],
      sources: [HOME, TERMS, PRICING],
    },
    {
      slug: "billing-and-cancellation",
      name: "Billing, cancellation and failed payments",
      summary: "How paid plans are billed and renewed, how to cancel, and what happens if a payment fails.",
      body: [
        "Paid plans are billed in advance, monthly or yearly. USD payments go through Stripe and INR payments go through Razorpay. SigChanger never sees or stores your full card number.",
      ],
      keyPoints: [
        "Your payment method is charged on each renewal until you cancel.",
        "You can cancel at any time from the billing page. Cancellation takes effect at the end of the current billing period.",
        "There are no refunds for partial billing periods, except where the law requires them.",
        "If a payment fails, the charge is retried and you're notified by email. If it isn't resolved within 14 days, paid features are suspended.",
      ],
      sources: [TERMS, PRIVACY, ABOUT],
    },
    {
      slug: "data-retention-and-deletion",
      name: "Data retention and account deletion",
      summary: "How long SigChanger keeps your data and how to exercise your data rights.",
      body: [
        "SigChanger keeps data for as long as your account is active. It collects only what it needs to run the service.",
      ],
      keyPoints: [
        "Service-account credentials are deleted immediately when you disconnect Google Workspace.",
        "When you close your account, company and user data is removed from production systems within 30 days.",
        "Limited records, such as invoices, may be kept where tax or legal obligations require it.",
        "You can ask to access, correct, export or delete your data from your account or through the Contact Us page. Verified requests are answered within 30 days.",
      ],
      features: ["privacy-first-security"],
      sources: [PRIVACY, TERMS],
    },
    {
      slug: "contacting-support",
      name: "Contacting SigChanger",
      summary: "How to reach the SigChanger team about features, setup, billing or enterprise plans.",
      body: [
        "The Contact Us form handles general enquiries, technical support, Enterprise plan requests, billing questions and partnerships. Priority support is included on the Professional and Enterprise plans.",
      ],
      keyPoints: [
        "Subjects on the form: general enquiry, technical support, Enterprise plan, billing question, partnership.",
        "Help with setting up Google Workspace is available through the form.",
        "SigChanger says it responds within one business day.",
        "Product walkthroughs and custom plans can be requested through the same form.",
      ],
      links: [{ label: "SigChanger Contact Us", href: "https://sigchanger.com/contact-us" }],
      sources: ["https://sigchanger.com/contact-us", PRICING],
    },
  ],
  benefits: [
    { title: "No signature work for employees", description: "Signatures are written server-side through the Gmail API, so nobody has to copy, paste or install anything. IT stops fixing individual signatures one mailbox at a time." },
    { title: "Signatures that follow the directory", description: "Because users are synced from Google Workspace, new hires get a signature from day one, title changes flow through, and departures are handled without a manual list." },
    { title: "Brand rules that can't be broken by accident", description: "Templates lock colours, fonts, logos and layout, and shared images live in one Asset Library, so a logo or banner change rolls out everywhere without a re-deployment." },
    { title: "Changes timed to the day they matter", description: "Rollouts can be scheduled for a specific date and time and coordinated across time zones, which suits rebrands, seasonal campaigns and compliance updates." },
    { title: "Credentials that stay yours", description: "Each company uses its own service account, its private key is stored encrypted with AES-256-CBC, and access can be revoked at any time by disconnecting or rotating the key." },
  ],
  howItWorks: [
    { title: "Register your company", description: "Create a company profile with your domain, brand colours and company details." },
    { title: "Connect Google Workspace", description: "Link your domain with a secure service account; your user directory is imported." },
    { title: "Import & sync users", description: "Employees are imported automatically; new hires and departures are handled for you." },
    { title: "Design your signature", description: "Build a template in the drag-and-drop builder with dynamic fields." },
    { title: "Assign & schedule", description: "Assign templates to teams, departments or users, and schedule rollouts for specific dates." },
    { title: "Deploy instantly", description: "Push signatures to everyone or selected teams with one click via the Gmail API." },
  ],
  security: [
    { title: "Encryption at rest and in transit", description: "Credentials and sensitive fields are encrypted with AES-256-CBC at rest; traffic uses HTTPS/TLS." },
    { title: "Your own service account", description: "Each company connects its own Google Cloud service account; its private key is stored encrypted and decrypted in memory only when calling Google APIs." },
    { title: "No access to your data", description: "Neither SigChanger staff nor the platform owner has direct access to decrypted credentials." },
    { title: "Multi-tenant isolation", description: "Each company's users, templates, signatures and credentials are kept separate from every other company." },
    { title: "Role-based access", description: "Super Admin, Company Admin and Employee roles are enforced at the API layer." },
    { title: "Session security", description: "Short-lived JWT access tokens with rotating refresh tokens; passwords are stored as bcrypt hashes." },
    { title: "Endpoint protection", description: "Rate limiting, request validation and audit logging on every sensitive endpoint." },
    { title: "Revocable access and deletion", description: "Disconnect Workspace or rotate the key at any time; credentials are deleted on disconnect, and account data is removed within 30 days of closure." },
  ],
  integrations: ["google-workspace"],
  pricing: {
    currency: "USD",
    unit: "month",
    trial: "Free plan with no time limit and no credit card required",
    note: "Basic and Professional are also offered in INR (₹999 and ₹2,999 per month). USD billing via Stripe, INR billing via Razorpay.",
    asOf: "2026-10-08",
    sourceUrl: "https://sigchanger.com/pricing",
    plans: [
      { name: "Free", price: "$0", period: "month", description: "Get started with basic signature management. Suits small teams of up to 10 people trying SigChanger with no time limit and no card.", features: ["Up to 10 users", "Up to 2 templates", "Google Workspace sync", "Visual template builder"], cta: { label: "Start free", href: "https://sigchanger.com/signup" } },
      { name: "Basic", price: "$29", period: "month", description: "For growing teams that need more control: up to 50 users and 10 templates, with the directory re-synced automatically once a day. Also offered at ₹999 per month.", features: ["Up to 50 users", "Up to 10 templates", "Google Workspace sync", "Visual template builder", "Auto-sync (daily)"], cta: { label: "Choose Basic", href: "https://sigchanger.com/pricing" } },
      { name: "Professional", price: "$79", period: "month", description: "For larger organisations with advanced needs: up to 200 users and 25 templates, hourly auto-sync and priority support. Also offered at ₹2,999 per month.", features: ["Up to 200 users", "Up to 25 templates", "Google Workspace sync", "Visual template builder", "Auto-sync (hourly)", "Priority support"], cta: { label: "Choose Professional", href: "https://sigchanger.com/pricing" }, recommended: true },
      { name: "Enterprise", price: "Custom", description: "Custom solutions for large-scale deployments of up to 10,000 users and 100 templates, adding custom integrations. Priced through the Contact Us form.", features: ["Up to 10,000 users", "Up to 100 templates", "Google Workspace sync", "Visual template builder", "Auto-sync (hourly)", "Priority support", "Custom integrations"], cta: { label: "Contact sales", href: "https://sigchanger.com/contact-us" } },
    ],
  },
  supportUrl: "https://sigchanger.com/contact-us",
  useCases: [
    { title: "Rebrands", description: "Change every signature in the organisation at once when the brand changes." },
    { title: "Seasonal campaigns", description: "Schedule a campaign signature to go live on a set date." },
    { title: "Compliance updates", description: "Roll out required changes to everyone consistently." },
    { title: "Groups of companies", description: "Manage signatures for more than one domain or subsidiary from one place." },
  ],
  faqs: [
    { question: "Which email platform does SigChanger work with?", answer: "Gmail in Google Workspace. It connects to your Workspace directory to import and sync users." },
    { question: "Is the free plan time-limited?", answer: "No. The Free plan has no time limit and needs no credit card." },
    { question: "Can I schedule changes in advance?", answer: "Yes. Rollouts can be scheduled for specific dates and times, and templates can be assigned by group." },
    { question: "What happens when I hit my plan limit?", answer: "You're notified as you approach the limit and can upgrade at any time. At the limit you can't add records beyond the quota until you upgrade, but existing data is never deleted because of a limit." },
    { question: "How does Google Workspace sync work?", answer: "SigChanger connects to your Workspace directory through a service account your company provides, imports user data automatically and keeps signatures in step as the team changes. Auto-sync runs daily on Basic and hourly on Professional and Enterprise." },
    { question: "How secure is my data?", answer: "Credentials are encrypted with AES-256-CBC at rest and traffic uses TLS. Each company connects its own Google Cloud service account, and neither SigChanger staff nor the platform owner has direct access to decrypted credentials." },
    { question: "Do employees need to do anything to get their signature?", answer: "No. Deployment runs server-side through the Gmail API, which updates each user's send-as signature settings directly, so no user action is involved." },
    { question: "How can we pay?", answer: "Paid plans are billed in advance, monthly or yearly. USD billing goes through Stripe (card, Google Pay, Apple Pay) and INR billing through Razorpay (UPI, net banking, card and wallets). SigChanger never sees your full card number." },
    { question: "What happens to our data if we leave?", answer: "Disconnecting Google Workspace deletes the stored service-account credentials immediately. If you close the account, company and user data is removed from production systems within 30 days, apart from records such as invoices kept for tax or legal reasons." },
    { question: "Will signatures look identical in every email client?", answer: "SigChanger's terms say it does not warrant identical rendering across every email client, device or Gmail mobile version, because rendering depends on third-party systems." },
  ],
  solutions: ["run-a-well-organised-office"],
  sources: [HOME, FEATURES, PRICING, ABOUT, PRIVACY, TERMS],
  lastVerified: "2026-10-08",
};
