import type { Product } from "@/content/types";

export const sizoru: Product = {
  id: "sizoru",
  slug: "sizoru",
  name: "Sizoru",
  shortDescription:
    "Market-size reports for founders and investors: total, reachable and winnable market (TAM, SAM, SOM) worked out two ways, with every source cited.",
  longDescription:
    "Sizoru produces TAM / SAM / SOM market-sizing reports (the total market, the part you can serve, and the share you can realistically win) for founders, consultants and investors. Every market is sized twice, top-down from a population and bottom-up from a single customer, and the two results are compared before any number is published.\n\nA simple rule decides the outcome: a gap under 15% fixes a single TAM, 15 to 40% gives a cited range, and over 40% delivers both numbers with an explanation of which assumption is not holding up. Every TAM → SAM → SOM filter is labelled with its percentage, and every SOM comes as bull, base and bear (optimistic, realistic and cautious) scenarios.\n\nFor Indian markets, the India 1/2/3 framework narrows the SAM to the segment you actually sell to. Each citation carries a Tier 1, 2 or 3 badge showing how reliable it is, with estimates from market-research publishers used only as a cross-check.\n\nYou fill in seven fields and the report is built in about three minutes, ending in a print-ready PDF with every figure tied to its source. Sizoru is a product of Stolvix and charges ₹4,999 per report with no subscription.",
  tagline: "A defensible TAM, in three minutes, not three weeks.",
  category: "insights-research",
  secondaryCategories: ["sales-marketing"],
  subcategory: "market-research",
  primaryUseCase: "Market sizing for fundraising",
  audience: ["Founders (pre-seed to Series A)", "Consultants & advisors", "VCs & accelerators"],
  platforms: ["web"],
  market: "India",
  status: "live",
  verification: { relationship: "pending", publicSale: "confirmed" },
  websiteUrl: "https://sizoru.com/",
  appUrl: "https://sizoru.com/sign-in?mode=signup",
  publisher: { name: "Stolvix" },
  featureCategories: [
    {
      slug: "methodology",
      name: "Methodology",
      description:
        "How every Sizoru report is built: two methods, a check that they agree, India split into segments, graded sources, visible filters and scenarios.",
      body: [
        "Sizoru's methodology page explains how every report is put together: the two sizing methods it runs, the test that fixes the result, the framework it uses for India, and the limits it states openly.",
        "Its starting point is that a market sized by one method is an opinion, while a market sized by two methods that agree is a case you can defend.",
      ],
    },
    {
      slug: "the-report",
      name: "The report",
      description: "What you receive and the terms around it.",
      body: [
        "Every Sizoru run ends in a print-ready PDF with every figure tied to its source: a finished analysis built around one clear argument, rather than an editable draft or chat text.",
        "The report is sold per report with no subscription. You see a preview before paying, and each report includes three free revisions within 30 days.",
      ],
    },
  ],
  features: [
    {
      slug: "dual-method-convergence-test",
      name: "Dual-method convergence test",
      summary: "Every report works out the market top-down and bottom-up, and compares the two before fixing a number.",
      category: "methodology",
      highlight: true,
      hasPage: true,
      body: [
        "Sizoru sizes every market twice. Top-down analysis starts from a population (total spend, total addressable users or total industry revenue) and narrows it step by step down to your segment. Bottom-up analysis starts from a unit (what one customer is worth) and multiplies by the realistically reachable customer count.",
        "Sizoru describes the two methods as flawed in opposite directions: top-down inherits the assumptions of whoever published the population figure, bottom-up inherits the optimism of whoever sized the unit. Rather than picking a winner, Sizoru compares them and uses the gap between them to show where the assumptions are weakest.",
        "A tiered rule then decides what the report delivers: a single fixed TAM, a cited range, or both numbers with an explanation of which assumption is not holding up.",
      ],
      problem:
        "Most market sizing is a single number stated with confidence and backed by vague reasoning; a figure built with only one method is easy to knock down.",
      howItWorks: [
        "Top-down: start from the largest defensible number (industry revenue, population or category spend) and narrow it step by step to reach the addressable market.",
        "Bottom-up: start from one customer's value (average revenue per user, or ARPU, retention and how long they stay) and multiply by the realistic maximum number of customers.",
        "Compare the two results and measure the gap between them.",
        "Apply the agreement rule and deliver the matching result.",
      ],
      capabilities: [
        "Gap under 15% (Locked): both methods agree, so a single TAM is given with high confidence.",
        "Gap of 15 to 40% (Range): the methods roughly agree, so a TAM range is given with both ends cited.",
        "Gap over 40% (Diagnostic): both numbers are given, with an explanation of which assumption differs and why.",
        "Each step of both methods shows how reliable its source is (its tier).",
      ],
      benefits: [
        "A number both methods agree on gives investors confidence; a clearly flagged gap with honest reasoning shows nothing was hidden.",
        "Founders can defend their numbers with both methods on show.",
      ],
      relatedFeatures: ["tier-rated-source-provenance", "visible-filter-chain", "india-1-2-3-framework"],
      sources: ["https://sizoru.com/methodology", "https://sizoru.com/"],
      faqs: [
        {
          question: "What happens if the two methods don't agree?",
          answer:
            "If they are more than 15% apart, Sizoru shows the gap and says which assumption is not holding up instead of hiding it. Above a 40% gap, the report includes both numbers plus a detailed explanation.",
        },
      ],
    },
    {
      slug: "top-down-analysis",
      name: "Top-down analysis",
      summary: "Sizing from the big picture inward: start from the largest defensible number and narrow it step by step to your segment.",
      category: "methodology",
      hasPage: true,
      body: [
        "Top-down is the first of the two methods Sizoru runs on every report. It begins with the largest defensible figure, such as total industry revenue, total addressable population or total category spend, and narrows it step by step until what remains is the market you can address.",
        "Sizoru is open about the method's weakness: a top-down number inherits the assumptions of whoever published the population figure. That is why the top-down result is treated as a first estimate and is always compared with a bottom-up estimate.",
      ],
      howItWorks: [
        "Start from a population figure, such as total registered businesses or total category spend.",
        "Filter to the relevant part of that population, for example digitally active businesses.",
        "Filter further to your sub-vertical and to those willing to pay.",
        "Multiply by a typical average revenue per user (ARPU) to reach the top-down TAM.",
      ],
      capabilities: [
        "Each step shows the reliability tier of its source",
        "Filters are applied in order and shown in the report",
        "The result is a first estimate that is checked against the bottom-up number",
      ],
      relatedFeatures: ["bottom-up-analysis", "dual-method-convergence-test", "visible-filter-chain"],
      sources: ["https://sizoru.com/methodology"],
    },
    {
      slug: "bottom-up-analysis",
      name: "Bottom-up analysis",
      summary: "Sizing from one customer outward: start from what one customer is worth and multiply by the number of customers you can realistically reach.",
      category: "methodology",
      hasPage: true,
      body: [
        "Bottom-up is the second method in every Sizoru report. It starts from a single unit, such as annual contract value, transaction frequency or lifetime spend, and multiplies it by the number of customers you can realistically reach.",
        "Sizoru says this method fails in the opposite direction to top-down: it inherits the optimism of whoever sized the unit. Comparing the two is what shows where the assumptions are weakest.",
      ],
      howItWorks: [
        "Work out average revenue per customer from similar companies.",
        "Apply a typical yearly retention rate (the share of customers who stay).",
        "Estimate the realistic maximum number of customers over five years.",
        "Work out how long an average customer stays, from retention, and calculate the bottom-up TAM.",
      ],
      capabilities: [
        "Each part shows the reliability tier of its source",
        "Uses per-customer figures such as ARPU (average revenue per user), retention and customer lifetime",
        "The result is compared with the top-down number to check they agree",
      ],
      relatedFeatures: ["top-down-analysis", "dual-method-convergence-test"],
      sources: ["https://sizoru.com/methodology"],
    },
    {
      slug: "india-1-2-3-framework",
      name: "India 1/2/3 framework",
      summary: "India is split into three markets so the SAM (the part of the market you can serve) reflects who you actually sell to.",
      category: "methodology",
      highlight: true,
      hasPage: true,
      body: [
        "Sizoru argues that many reports treat India as one block of 1.4 billion consumers and apply the same filters to all of them, producing a number that is technically defensible but useless in practice.",
        "Every Sizoru report covering India applies the India 1/2/3 split and asks which of the three segments you are actually selling to; the SAM is then narrowed to that segment. Sizoru states that this changes the SAM by 40 to 70% in most cases.",
      ],
      problem:
        "Treating India as a single market lumps together very different buyers, producing sizes that look impressive in a pitch deck but fall apart when investors look closely.",
      capabilities: [
        "India 1 (~120 million people): tier-1 metro and English-comfortable, with per-capita spend comparable to Mexico or Brazil; home to most premium SaaS, fintech and D2C.",
        "India 2 (~300 million people): the aspiring, mostly online middle class in tier-2/3 cities, who prefer local languages; home to most quick-commerce, gaming and EdTech.",
        "India 3 (~1 billion people): the rural and urban informal economy, with limited spending beyond essentials; home to most subsidised and essential-service products.",
        "Applied on every report covering India, with the SAM narrowed to the chosen segment.",
      ],
      relatedFeatures: ["visible-filter-chain", "dual-method-convergence-test"],
      benefits: [
        "A SaaS startup selling to India 1 sees a SAM of around 120 million addressable users rather than 1.4 billion.",
        "The report shows how the SAM splits across the three segments, so an investor can see where the market actually sits.",
      ],
      audience: ["Founders selling into India", "VCs & accelerators"],
      faqs: [
        { question: "Does every report use India 1/2/3?", answer: "It is applied on every report covering India. The report asks which of the three segments you sell to and narrows the SAM to it." },
        { question: "How much does it change the result?", answer: "Sizoru states that this split changes the SAM by 40 to 70% in most cases." },
      ],
      sources: ["https://sizoru.com/methodology", "https://sizoru.com/"],
    },
    {
      slug: "tier-rated-source-provenance",
      name: "Tier-rated source provenance",
      summary: "Every cited source is graded into one of three reliability tiers, badged in the report and given weight to match.",
      category: "methodology",
      highlight: true,
      hasPage: true,
      body: [
        "Sizoru does not treat all sources as equal: a government statistic and a forecast from a paid research publisher are not the same thing, even when they appear side by side. Every cited source is graded into one of three tiers, marked with a visible badge in the report and given weight to match in the calculations.",
        "Each figure carries its tier badge in the source footnote, so if a number you plan to put in an investor deck rests on a weaker source, you know before the investor does.",
      ],
      problem:
        "Free AI tools can produce believable numbers with no sources you can trace, and reports often mix official figures with paid research estimates without telling them apart.",
      capabilities: [
        "Tier 1: Authoritative (e.g. RBI, SEBI, MoSPI, NSO, Census of India, NPCI, regulator filings, World Bank, IMF): used as primary inputs.",
        "Tier 2: Reputable (e.g. consulting-firm industry papers, NASSCOM, FICCI/CII white papers, comparable filings, peer-reviewed research): used as supporting inputs with the publisher shown.",
        "Tier 3: Caution (estimates from paid market-research publishers and generic third-party PR): used only as a cross-check, never as the only source, and marked with a caution badge.",
        "A number that comes only from Tier 3 is flagged as a research estimate rather than a measurement.",
        "Tier badges appear in every source footnote.",
      ],
      relatedFeatures: ["dual-method-convergence-test", "print-ready-pdf-report"],
      sources: ["https://sizoru.com/methodology", "https://sizoru.com/"],
    },
    {
      slug: "visible-filter-chain",
      name: "Visible filter chain",
      summary: "Every TAM → SAM → SOM step is shown, with each filter labelled, given its percentage and explained in a footnote.",
      category: "methodology",
      highlight: true,
      hasPage: true,
      body: [
        "A typical market-sizing slide simply states TAM, SAM and SOM. Sizoru's view is that when the steps between them are hidden, the numbers are just decoration: nobody can see why most of the TAM disappeared or why the SOM is the share of the SAM it is.",
        "Every Sizoru report includes every filter from TAM to SAM to SOM (such as geography, segment, niche, which channels can reach buyers, pricing fit and team capacity), so readers see the thinking behind the numbers. Sizoru's homepage also lets you change sample assumptions and watch the SOM move, using the same logic as the report.",
      ],
      problem:
        "When the filters between TAM, SAM and SOM are hidden, investors stop trusting the numbers and brush them aside.",
      capabilities: [
        "Each filter is labelled.",
        "Each percentage reduction is shown.",
        "Each rationale is footnoted.",
        "Covers both the TAM → SAM and SAM → SOM steps.",
      ],
      benefits: [
        "Investor objections become specific (\"I disagree with Filter 4\") rather than vague (\"the numbers seem high\").",
      ],
      relatedFeatures: ["india-1-2-3-framework", "bull-base-and-bear-scenarios"],
      sources: ["https://sizoru.com/methodology", "https://sizoru.com/"],
    },
    {
      slug: "bull-base-and-bear-scenarios",
      name: "Bull, base and bear scenarios",
      summary: "Every SOM (the share of the market you can realistically win) comes as three scenarios, each with its table of assumptions.",
      category: "methodology",
      hasPage: true,
      body: [
        "Sizoru delivers every SOM as three scenarios, bull (optimistic), base (realistic) and bear (cautious), together with the table of assumptions behind each one.",
        "Sizoru's reasoning is that no argument holds up on a single number, and that a careful worst case is an underrated way to earn trust when pitching.",
      ],
      capabilities: [
        "Base case: the realistic five-year projection.",
        "Bull case: the upside if execution and market timing both go well.",
        "Bear case: the outcome if growth assumptions shrink by 30 to 50%.",
        "An assumption table for each scenario, covering figures such as five-year CAGR (yearly growth rate), growth in CAC (cost to win a customer) and net revenue retention.",
      ],
      relatedFeatures: ["visible-filter-chain"],
      problem: "A single SOM figure gives investors nothing to test against, and hides how much the outcome depends on growth assumptions.",
      faqs: [
        { question: "What does the bear case assume?", answer: "The bear case shows the outcome if growth assumptions shrink by 30 to 50%, with its own assumption table." },
        { question: "Which scenario is the headline number?", answer: "The base case, which Sizoru defines as the realistic five-year projection." },
      ],
      sources: ["https://sizoru.com/methodology", "https://sizoru.com/"],
    },
    {
      slug: "print-ready-pdf-report",
      name: "Print-ready PDF report",
      summary: "A finished PDF, with every figure tied to its source, that is yours to keep and download again.",
      category: "the-report",
      hasPage: true,
      body: [
        "You receive a print-ready PDF with every figure tied to its source. It is a finished analysis rather than an editable draft, around one argument backed up at every step. It is yours to keep and can be downloaded again.",
        "You fill in seven fields and the report is built in about three minutes. An investor deck (.pptx) and an editable model (.xlsx) are listed as coming soon.",
      ],
      howItWorks: [
        "Sign up with a six-digit code sent to your email, with no password or demo call.",
        "Fill in seven fields: company, industry, model, geography, customer, stage and description, with Indian defaults pre-filled.",
        "Sizoru runs six AI-checked steps covering live web research, the two-method maths, source grading, India 1/2/3 filters and scenario forecasts.",
        "Download the PDF.",
      ],
      capabilities: [
        "Executive summary with the top-down and bottom-up TAM, the gap between them, the five-year SOM and whether the number is locked.",
        "India 1/2/3 SAM breakdown, source provenance listing and scenario pages.",
        "Footnoted citations carrying tier badges.",
      ],
      relatedFeatures: ["dual-method-convergence-test", "tier-rated-source-provenance", "bull-base-and-bear-scenarios"],
      sources: ["https://sizoru.com/", "https://sizoru.com/methodology"],
      faqs: [
        {
          question: "How is this different from ChatGPT or free AI tools?",
          answer:
            "Sizoru always uses two methods, grades every citation by how reliable it is, applies the India 1/2/3 framework and delivers a finished PDF report rather than chat text.",
        },
      ],
    },
    {
      slug: "3-free-revisions-in-30-days",
      name: "3 free revisions in 30 days",
      summary: "If an investor pushes back on a number, Sizoru redoes that section, up to three times within 30 days.",
      category: "the-report",
      hasPage: true,
      body: [
        "Every Sizoru report comes with three free revisions within 30 days of purchase. The revisions are aimed at the moment a report meets an investor: if a VC questions a number, Sizoru redoes that section.",
        "Beyond section revisions, Sizoru offers a pass-investor-review promise: if the report fails investor review, it says it will redo the whole report free or refund it.",
      ],
      problem: "A one-off report bought before a pitch is of little use if a single challenged assumption can't be reworked afterwards.",
      capabilities: [
        "Three free revisions per report, usable within 30 days.",
        "Section-level redo when an investor pushes back on a specific number.",
        "A full redo or refund if the report fails investor review.",
        "Automatic refund if the system fails to produce the report.",
      ],
      audience: ["Founders (pre-seed to Series A)", "Consultants & advisors"],
      relatedFeatures: ["pay-after-the-preview", "visible-filter-chain", "print-ready-pdf-report"],
      sources: ["https://sizoru.com/"],
    },
    {
      slug: "pay-after-the-preview",
      name: "Pay after the preview",
      summary: "See a preview of the report before paying the ₹4,999 per-report price, with an automatic refund if report generation fails.",
      category: "the-report",
    },
  ],
  productSolutions: [
    {
      slug: "market-sizing-for-founders",
      name: "Market sizing for founders raising capital",
      summary: "A TAM slide that shows its working, for founders from pre-seed to Series A.",
      problem:
        "Sizoru says the market-size slide is where most pitch decks fail: a bare TAM, SAM and SOM with hidden steps gets polite nods from investors but loses their trust.",
      body: [
        "Sizoru is built first for founders between pre-seed and Series A. It gives them a report in which both sizing methods, every filter and every source are visible, so the market number can be defended in the meeting.",
      ],
      approach: [
        "Size the market both top-down and bottom-up, then give a single number, a range or an explanation of the gap.",
        "Show every TAM to SAM to SOM filter so objections become specific rather than vague.",
        "Narrow Indian markets to the India 1, 2 or 3 segment you actually sell to.",
        "Badge every source by reliability tier so weak figures are known before an investor finds them.",
        "Deliver bull, base and bear scenarios, since Sizoru sees a careful worst case as an underrated way to earn trust.",
      ],
      audience: ["Founders (pre-seed to Series A)"],
      features: ["dual-method-convergence-test", "visible-filter-chain", "india-1-2-3-framework", "tier-rated-source-provenance", "bull-base-and-bear-scenarios"],
      sources: ["https://sizoru.com/", "https://sizoru.com/methodology"],
    },
  ],
  productComparisons: [
    {
      slug: "sizoru-vs-chatgpt-and-free-ai",
      name: "Sizoru vs ChatGPT and free AI tools",
      competitor: "ChatGPT / free AI tools",
      summary: "How Sizoru's 'alternatives' section compares it with sizing a market using a general-purpose AI chat tool.",
      body: [
        "Sizoru names free AI tools as one of three ways founders size markets today, and says this approach \"falls apart in the room\". Its argument is that free tools produce believable-sounding numbers with no sources you can trace. Sizoru instead always uses two methods, gives every citation a reliability tier, and delivers a PDF report rather than chat text.",
        "The rows below are Sizoru's own comparison as published on its homepage.",
      ],
      rows: [
        { criterion: "Methodology", product: "Dual-method, locked on convergence", competitor: "None (as stated by Sizoru)" },
        { criterion: "Source provenance", product: "Tier 1/2/3, traced", competitor: "Sizoru says sources can be hallucinated" },
        { criterion: "India 1/2/3 segmentation", product: "Built in", competitor: "No" },
        { criterion: "Time to deliver", product: "About 3 minutes", competitor: "About an hour, which Sizoru says then breaks under scrutiny" },
        { criterion: "Price", product: "₹4,999 per report", competitor: "Free" },
      ],
      features: ["dual-method-convergence-test", "tier-rated-source-provenance", "india-1-2-3-framework", "print-ready-pdf-report"],
      sources: ["https://sizoru.com/"],
    },
    {
      slug: "sizoru-vs-agency-consultants",
      name: "Sizoru vs agency consultants",
      competitor: "Agency consultants",
      summary: "Sizoru's published comparison with hiring a consultant or agency to size a market.",
      body: [
        "Sizoru lists agency consultants as an alternative that \"burns runway and trust\". It presents itself as giving founders the kind of professional sizing method that usually needs an expensive consultant, at a per-report price.",
        "The rows below are Sizoru's own comparison as published on its homepage.",
      ],
      rows: [
        { criterion: "Methodology", product: "Dual-method, locked on convergence", competitor: "Varies" },
        { criterion: "Source provenance", product: "Tier 1/2/3, traced", competitor: "Inconsistent" },
        { criterion: "India 1/2/3 segmentation", product: "Built in", competitor: "Maybe" },
        { criterion: "Time to deliver", product: "About 3 minutes", competitor: "About 3 weeks" },
        { criterion: "Price", product: "₹4,999 per report", competitor: "₹50K to ₹2L (Sizoru's estimate)" },
      ],
      features: ["dual-method-convergence-test", "tier-rated-source-provenance", "india-1-2-3-framework"],
      sources: ["https://sizoru.com/", "https://sizoru.com/methodology"],
    },
    {
      slug: "sizoru-vs-syndicated-research-reports",
      name: "Sizoru vs syndicated research reports",
      competitor: "Mordor Intelligence / IBISWorld",
      summary: "Sizoru's published comparison with buying a ready-made market-research report.",
      body: [
        "Sizoru describes market-research publishers such as Mordor Intelligence and IBISWorld as \"thorough, generic, expensive\". It says it offers the same rigour, often more for India because of its India framework, without the yearly licences, minimum seat counts or sales calls that come with big research subscriptions.",
        "Sizoru's methodology puts estimates from these research publishers in its Tier 3 (caution) source tier. They are used only as a cross-check and never as the only source.",
      ],
      rows: [
        { criterion: "Methodology", product: "Dual-method, locked on convergence", competitor: "Generic global" },
        { criterion: "Source provenance", product: "Tier 1/2/3, traced", competitor: "Yes" },
        { criterion: "India 1/2/3 segmentation", product: "Built in", competitor: "No" },
        { criterion: "Time to deliver", product: "About 3 minutes", competitor: "About 5 days" },
        { criterion: "Price", product: "₹4,999 per report", competitor: "₹3L+ (Sizoru's estimate)" },
      ],
      faqs: [
        {
          question: "Why is Sizoru so much cheaper than Mordor or IBISWorld?",
          answer: "Sizoru says it is built for founders rather than procurement teams, so there is no annual licence, no seat minimum and no sales call.",
        },
      ],
      features: ["tier-rated-source-provenance", "india-1-2-3-framework", "dual-method-convergence-test"],
      sources: ["https://sizoru.com/", "https://sizoru.com/methodology"],
    },
  ],
  productResources: [
    {
      slug: "sizoru-methodology",
      name: "The Sizoru methodology",
      type: "documentation",
      summary: "Sizoru's published account of how every report is built, and the limits it acknowledges.",
      body: [
        "Sizoru's methodology page explains the Sizoru Market Sizing Framework that Stolvix applies to every report. It walks through an example of a software startup selling to Indian small and mid-sized businesses (SMEs), sized both top-down and bottom-up, and then explains the gap between the two results.",
        "The page also has a section on what Sizoru is not. It sets clear limits on what a generated report should be trusted for.",
      ],
      keyPoints: [
        "Two methods: top-down from a population, and bottom-up from a single unit.",
        "A check on how far apart the two methods are, which fixes the TAM, gives a range, or explains the gap, depending on its size.",
        "India 1/2/3 segments for any report covering India.",
        "Three tiers of sources, with a visible badge on each citation.",
        "A visible TAM to SAM to SOM filter chain.",
        "Bull, base and bear scenarios, each with its assumption table.",
        "Stated limits: Sizoru does not predict the future, replace primary research, size markets with no comparable, or promise the AI is always right.",
      ],
      features: ["dual-method-convergence-test", "india-1-2-3-framework", "tier-rated-source-provenance", "visible-filter-chain", "bull-base-and-bear-scenarios"],
      sources: ["https://sizoru.com/methodology"],
    },
  ],
  supportTopics: [
    {
      slug: "generating-your-first-report",
      name: "Generating your first report",
      summary: "The four steps from signing up to downloading a Sizoru report.",
      body: [
        "Sizoru has no password and no demo call. You sign in with an emailed code, describe your company, and Sizoru does the rest.",
      ],
      steps: [
        "Sign up with a six-digit code sent to your email.",
        "Fill in the seven-field brief: company, industry, model, geography, customer, stage and description. Indian defaults are pre-filled.",
        "Let Sizoru run its six AI-checked steps: live web research, the two-method maths, source grading, India 1/2/3 filters and scenario forecasts.",
        "Download the print-ready PDF. It stays yours and you can download it again.",
      ],
      features: ["print-ready-pdf-report"],
      sources: ["https://sizoru.com/"],
    },
    {
      slug: "revisions-and-refunds",
      name: "Revisions, redos and refunds",
      summary: "What Sizoru offers if a report needs changing or doesn't hold up.",
      body: [
        "Sizoru charges per report, with no subscription. It backs each report with free revisions and a promise to redo the work if the report doesn't pass investor review.",
      ],
      keyPoints: [
        "Each report includes three free revisions within 30 days.",
        "If an investor pushes back on a number, Sizoru redoes that section.",
        "If the report fails investor review, Sizoru says it will redo the whole report free or give a refund.",
        "If report generation fails, you're refunded automatically.",
        "You see a preview of the report before you pay.",
      ],
      features: ["3-free-revisions-in-30-days", "pay-after-the-preview"],
      sources: ["https://sizoru.com/", "https://sizoru.com/methodology"],
    },
    {
      slug: "what-sizoru-cannot-do",
      name: "What Sizoru can't do",
      summary: "The limits Sizoru states for its own reports.",
      body: [
        "Sizoru's methodology lists situations where its reports should not be relied on alone. These help you decide whether a report fits what you need.",
      ],
      keyPoints: [
        "It sizes markets as they are and projects under stated assumptions. It does not predict the future.",
        "It does not replace primary research such as customer surveys.",
        "It needs at least one comparable industry or a reasonable equivalent, and will say when a market can't be sized.",
        "Reports are checked against figures from named sources and any inconsistencies are shown, but the AI is not presented as always right.",
        "The report is evidence for your case. It is not a substitute for understanding your market.",
      ],
      features: ["dual-method-convergence-test"],
      sources: ["https://sizoru.com/methodology"],
    },
  ],
  howItWorks: [
    { title: "Sign up", description: "Enter your email and sign in with a six-digit code, with no password and no demo call. Sizoru puts this step at about 60 seconds." },
    { title: "Describe your company", description: "Fill in seven fields: company, industry, model, geography, customer, stage and description. Indian defaults are pre-filled, and the brief takes about 90 seconds." },
    { title: "Report is built", description: "Six AI-checked steps run in about three minutes: live web research, the two-method maths, source grading, India 1/2/3 filters and scenario forecasts." },
    { title: "Preview, then pay", description: "You see a preview of the report before paying ₹4,999. If report generation fails, the charge is refunded automatically." },
    { title: "Download", description: "Get the print-ready PDF, with every figure tied to its source. It is yours to keep and can be downloaded again, with three free revisions available within 30 days." },
  ],
  benefits: [
    { title: "A number that survives investor questions", description: "Two independent methods are compared, and the result is a single number, a range or an explanation of the gap. A VC sees either agreement or an honest explanation, rather than one unsupported figure." },
    { title: "Every source graded", description: "Each citation carries a Tier 1, 2 or 3 reliability badge, and Tier 3 research-publisher estimates are never used as the only source. You learn that a number is weak before an investor points it out." },
    { title: "India sized as three markets", description: "The India 1/2/3 framework narrows the SAM to metro, tier-2/3 or informal-economy buyers. Sizoru says this changes the SAM by 40 to 70% in most cases." },
    { title: "Objections become specific", description: "Every filter between TAM, SAM and SOM is labelled with its percentage and a footnoted reason. Disagreements land on a particular filter instead of \"the numbers seem high\"." },
    { title: "Minutes and a fixed price", description: "A report takes about three minutes at ₹4,999. Sizoru contrasts this with roughly three weeks for agency consultants and about five days for ready-made research reports." },
  ],
  pricing: {
    currency: "INR",
    unit: "report",
    note: "One price, no subscription. Also $59 USD per report.",
    asOf: "2026-10-07",
    sourceUrl: "https://sizoru.com/#pricing",
    plans: [
      {
        name: "Single report",
        price: "₹4,999",
        period: "report",
        description: "One investor-ready report with no commitment ($59 USD). Suits founders sizing a market for a raise, advisors producing one for a client, and investors sizing markets one at a time.",
        features: ["Full dual-method TAM / SAM / SOM", "India 1/2/3 framework", "Three scenarios: bull, base and bear", "Tier 1/2/3 source provenance", "Print-ready PDF with every figure sourced", "3 free revisions within 30 days", "Pay after you see the preview", "Automatic refund if generation fails"],
        cta: { label: "Generate a report", href: "https://sizoru.com/sign-in?mode=signup" },
        recommended: true,
      },
    ],
  },
  docsUrl: "https://sizoru.com/methodology",
  useCases: [
    { title: "Founders preparing to raise", description: "A pre-seed to Series A founder replaces a bare TAM slide with a report that shows both methods, every filter and three scenarios, so the market number holds up in the pitch." },
    { title: "Consultants and advisors", description: "Strategy, banking and fundraising advisors create a cited sizing report in minutes, spending their billable time on advice rather than calculation." },
    { title: "VCs and accelerators", description: "Investors size markets for an investment idea or across a batch of startups with the same method each time; Sizoru gives the example of sizing 12 markets a month at ₹4,999 each." },
  ],
  faqs: [
    { question: "How is this different from ChatGPT or free AI tools?", answer: "Free tools can produce believable numbers with no sources you can trace. Sizoru always uses two methods, grades every citation by reliability, applies the India 1/2/3 framework and delivers a PDF with every figure tied to its source, rather than chat text." },
    { question: "Why is it so much cheaper than Mordor or IBISWorld?", answer: "Sizoru says it is built for founders rather than procurement teams. There is no annual licence, no seat minimum and no sales call, and it claims the same rigour, often more for India." },
    { question: "Is Sizoru a subscription?", answer: "No. You pay ₹4,999 ($59) per report, only when you generate one, so there is nothing to cancel. Team and Studio plans are described as returning with the full Sizoru suite." },
    { question: "Can I revise a report?", answer: "Each report includes three free revisions within 30 days. If an investor pushes back on a number, Sizoru redoes that section." },
    { question: "What if the report doesn't pass investor review?", answer: "Sizoru says it will redo the whole report free, or refund it. If report generation itself fails, the payment is refunded automatically." },
    { question: "Do I pay before seeing anything?", answer: "No. You see a preview of the report before you pay." },
    { question: "What format is the report?", answer: "A print-ready PDF, with every figure tied to its source, that is yours to keep and download again. Sizoru lists a PowerPoint investor deck and an editable Excel model as coming soon." },
    { question: "Do you actually understand my industry?", answer: "Sizoru relies on Tier 1 sources such as RBI, SEBI, MoSPI, NPCI and regulator filings, plus checking every result with two methods. If the methods are more than 15% apart, the report shows the gap and names the assumption that is not holding up." },
    { question: "Can Sizoru size any market?", answer: "It needs at least one comparable industry or a reasonable equivalent. For a market with no comparables, Sizoru says it will tell you it can't size it." },
    { question: "How long does a report take?", answer: "About three minutes to build the report, after a sign-up of roughly a minute and a seven-field brief of about 90 seconds." },
  ],
  solutions: ["prepare-for-launch-and-fundraising"],
  industries: ["startups-and-investors"],
  sources: ["https://sizoru.com/", "https://sizoru.com/methodology"],
  lastVerified: "2026-10-08",
};
