import type { Feature, FeatureCategory, Product } from "@/content/types";

const HOME = "https://trackysuite.com/";
const ABOUT = "https://trackysuite.com/about";
const PRIVACY = "https://trackysuite.com/privacy";
const SIGNUP = "https://trackysuite.com/signup";
const LOGIN = "https://trackysuite.com/login";

const featureCategories: FeatureCategory[] = [
  {
    slug: "modules",
    name: "Modules",
    description: "Ten modules, one system.",
    body: [
      "TrackySuite describes itself as ten modules in one system: clients, compliance, tasks, documents, reminders, reports, team and the client portal, alongside the practice dashboard and audit trail.",
      "Every module is linked to the same central system, so a client's registrations set the compliance calendar, the calendar sets tasks and reminders, and each action is recorded in the audit trail.",
    ],
  },
];

const features: Feature[] = [
  {
    slug: "compliance-calendar",
    name: "Compliance Calendar",
    summary: "Statutory deadlines placed automatically for every client from their registrations.",
    category: "modules",
    highlight: true,
    hasPage: true,
    body: [
      "The Compliance Calendar holds a firm's whole statutory calendar in one place: GST, TDS and TCS, income tax, ROC/MCA, PF and ESI, and professional tax. The due dates come built in, kept up to date by TrackySuite and set up as rules rather than typed in.",
      "Nobody builds the calendar by hand. Each client's registrations (GSTIN, TAN, PAN, CIN, LLPIN, PTRC, PTEC) decide which returns that client owes and from when. A client without a GSTIN is never scheduled a GST return, and a registration issued in July does not produce an April period.",
      "For any client and any financial year, TrackySuite can show a compliance position listing every obligation, its status, and the reason when an obligation does not apply.",
    ],
    problem:
      "Practices carrying dozens to hundreds of clients track deadlines in spreadsheets, where a missed date costs the client a penalty and the firm its reputation.",
    howItWorks: [
      "Add a client, or import them from Excel.",
      "Tick the client's registrations (GSTIN, TAN, PAN, CIN, LLPIN, PTRC, PTEC).",
      "The client's statutory calendar fills in instantly, with each obligation starting from the right period.",
      "Tasks are scheduled automatically for each client, and reminders go out 14, 7, 3 and 1 day before every scheduled filing.",
    ],
    capabilities: [
      "110 statutory filings kept up to date by TrackySuite",
      "8 entity types, from individual and HUF to public limited, plus trusts, societies and Section 8 companies",
      "Covers GST (GSTR-1/3B/9), TDS quarterly returns, ROC/MCA annual filings, PF/ESI monthly, income tax and FEMA/RBI heads",
      "Scheduling based on registrations, so only the returns a client owes are added",
      "Compliance position for each client and financial year, with reasons when an obligation doesn't apply",
    ],
    benefits: ["No hand-typed deadline lists", "Every client's calendar is correct from day one"],
    audience: ["Chartered accountant (CA) firms", "Company secretary (CS) firms", "Tax practices"],
    relatedFeatures: ["client-management", "deadline-reminders", "task-workflow"],
    sources: [HOME, ABOUT, SIGNUP],
    faqs: [
      {
        question: "Does TrackySuite cover all Indian statutory deadlines?",
        answer: "GST (GSTR-1/3B/9), TDS quarterly returns, ROC/MCA annual filings, PF/ESI monthly and income-tax dates come built in, and tasks are scheduled automatically for each client based on their registrations.",
      },
    ],
  },
  {
    slug: "task-workflow",
    name: "Task & Workflow",
    summary: "Prepare → review → file, with an owner at every stage.",
    category: "modules",
    highlight: true,
    hasPage: true,
    body: [
      "Every filing moves through set stages (prepare, review, file) with an owner named at each stage, shown on a task board.",
      "There are four stages, and duties are kept separate: the person who prepared a return cannot be the person who signs it off. Approved work is counted separately from filed work, so the numbers are accurate.",
    ],
    howItWorks: [
      "Tasks are created for each client's scheduled filings.",
      "A team member prepares the return.",
      "A different team member reviews and approves it.",
      "The return is filed, and every step is written to the audit trail.",
    ],
    capabilities: [
      "Task board across to do, review and filed",
      "An owner at every stage",
      "Preparer cannot also sign off the same return",
      "Approved counted separately from filed",
    ],
    problem:
      "When the same person prepares and files a return, errors reach the tax department unchecked, and partners cannot tell what is only approved from what has actually been filed.",
    benefits: [
      "Nothing is filed without a second person reviewing it.",
      "Every filing has a named owner, so accountability is clear when a deadline is at risk.",
      "Dashboard counts stay accurate because approved and filed are tracked separately.",
    ],
    audience: ["Practices with a review chain", "Partners and managers"],
    useCases: [
      { title: "Monthly GST returns", description: "A senior prepares a client's GSTR-3B, a manager reviews and approves it, and the return is then marked filed, with each step recorded in the audit trail." },
    ],
    faqs: [
      { question: "Can the preparer approve their own return?", answer: "No. TrackySuite's review process is built so that the person who prepared a return cannot be the person who signs it off." },
      { question: "Is approved the same as filed?", answer: "No. Approved work is counted separately from filed work on the dashboard, so the filed figure only includes returns that have actually been filed." },
    ],
    relatedFeatures: ["team-management", "audit-trail", "practice-dashboard"],
    sources: [HOME, ABOUT, SIGNUP],
  },
  {
    slug: "deadline-reminders",
    name: "Deadline Reminders",
    summary: "Reminders 14, 7, 3 and 1 day before each due date, passed up to a manager automatically if work is still open.",
    category: "modules",
    highlight: true,
    hasPage: true,
    body: [
      "Deadline Reminders follow a fixed schedule on every scheduled filing: reminders go out 14, 7, 3 and 1 day before the due date.",
      "Reminders step up on their own. Early reminders go out by email; three days before, anything still open is passed to a manager, and the day before brings a final notice.",
    ],
    howItWorks: [
      "14 days before: a reminder email is sent.",
      "7 days before: another reminder goes out.",
      "3 days before: anything still open is passed to a manager.",
      "1 day before: a final notice goes out.",
    ],
    capabilities: [
      "Runs automatically on every scheduled filing",
      "Open items passed up to a manager",
      "Can be sent from the firm's own email domain once the firm sets up its own verified mail server (SMTP)",
      "Clients receive automatic reminders, so staff no longer send one per compliance by hand",
    ],
    problem:
      "Sending a reminder for every compliance of every client by hand takes staff time, and a reminder that is never sent leaves a filing at risk of a penalty.",
    benefits: [
      "Reminders go out on every scheduled filing without anyone remembering to send them.",
      "Open items reach a manager three days before the due date, while there is still time to act.",
    ],
    audience: ["CA, CS and tax firms", "Managers"],
    faqs: [
      { question: "When do reminders go out?", answer: "At 14, 7, 3 and 1 day before each due date. Three days before, anything still open is passed to a manager, and the day before brings a final notice." },
      { question: "Whose email address do reminders come from?", answer: "From the firm's own domain if it has set up its own verified mail server (SMTP); otherwise from TrackySuite's standard sending address." },
    ],
    relatedFeatures: ["compliance-calendar", "task-workflow"],
    sources: [HOME, LOGIN, PRIVACY],
  },
  {
    slug: "client-portal",
    name: "Client Portal",
    summary: "Clients see their status, upload documents and raise tickets themselves.",
    category: "modules",
    highlight: true,
    hasPage: true,
    body: [
      "Every client of the firm gets portal access. In the portal they see their own compliance status, upload documents into their own vault and download what the firm has filed for them.",
      "Instead of calling for updates, clients raise support tickets in the portal. The firm controls what each client can see.",
    ],
    problem: "Clients repeatedly call the firm asking for updates on their filings.",
    capabilities: [
      "Clients see only their own compliance status",
      "Clients upload documents into their own vault",
      "Clients download returns the firm has filed",
      "Support tickets instead of phone calls",
      "The firm decides what each client can see",
    ],
    howItWorks: [
      "The firm gives each client portal access.",
      "The client logs in and sees their own compliance status, such as which returns are filed.",
      "The client uploads requested documents into their own vault, where the firm sees them awaiting review.",
      "The client downloads filed returns or raises a support ticket instead of phoning.",
    ],
    benefits: [
      "Fewer status calls, because clients can check progress themselves.",
      "Documents arrive in one place rather than scattered across WhatsApp and email.",
    ],
    audience: ["Firms' clients", "CA, CS and tax firms"],
    relatedFeatures: ["document-vault", "client-management"],
    sources: [HOME, SIGNUP],
    faqs: [
      {
        question: "Can my clients see their own filings and documents?",
        answer: "Yes. Each client gets portal access to see their compliance status, upload documents, download what you've filed and raise support tickets. You control what's visible.",
      },
    ],
  },
  {
    slug: "document-vault",
    name: "Document Vault",
    summary: "A separate, encrypted vault for each client, with access by role and every view logged.",
    category: "modules",
    highlight: true,
    hasPage: true,
    body: [
      "Each client has its own document vault in TrackySuite. Stored documents are encrypted, and access depends on each person's role, enforced record by record in the database (row-level security).",
      "Every time a document is opened it is logged, separately from the general audit trail, and the vault shows which documents the client still needs to upload.",
    ],
    capabilities: [
      "Separate vault for each client",
      "Stored documents encrypted",
      "Access by role, with row-level security",
      "Every document view logged",
      "Clients upload directly through the portal",
      "Shows documents the client still needs to upload",
    ],
    problem: "Client documents arrive through WhatsApp and email and end up scattered, with no record of who opened what.",
    audience: ["CA, CS and tax firms", "Firms' clients"],
    faqs: [
      { question: "Are documents encrypted?", answer: "Yes. Stored documents are encrypted, access depends on each person's role (with row-level security), and documents are shown only to authorised users." },
      { question: "Is opening a document logged?", answer: "Yes. Every document view is logged, separately from the audit log of other actions." },
    ],
    relatedFeatures: ["client-portal", "audit-trail"],
    sources: [HOME, PRIVACY],
  },
  {
    slug: "practice-dashboard",
    name: "Practice Dashboard",
    summary: "Due, in review, filed and overdue across all your clients.",
    category: "modules",
    highlight: true,
    hasPage: true,
    body: [
      "The Practice Dashboard is the partner's view of the whole practice: what is due, what is in review, what has been filed and what is overdue, across every client.",
      "TrackySuite presents it as the view that replaces the Monday status meeting.",
    ],
    capabilities: [
      "Due, in review, filed and overdue counts across all clients",
      "Approved counted separately from filed",
      "A view of all clients for partners",
      "Live counts of tracked filings, filings due this week, filings in review and filings completed",
    ],
    problem: "Partners otherwise rely on a weekly status meeting to learn what is due, stuck in review or overdue.",
    audience: ["Partners"],
    relatedFeatures: ["reports-analytics", "task-workflow"],
    sources: [HOME],
  },
  {
    slug: "client-management",
    name: "Client Management",
    summary: "One main record per client; its registrations set all the scheduling.",
    category: "modules",
    hasPage: true,
    body: [
      "Client Management keeps one main record for each client, and that record's registrations set everything else: the statutory calendar, tasks and reminders.",
      "An existing client list can be brought in from Excel, up to 500 clients at a time, or clients can be added one by one in the app.",
    ],
    howItWorks: [
      "Download the Excel template; a filled-in example row and dropdowns keep the format right.",
      "Fill in your clients (up to 500 per import).",
      "A test run checks every row before anything is created.",
      "Once a client's registrations are ticked, their full statutory calendar fills in.",
    ],
    capabilities: [
      "One main record per client",
      "Bulk import from Excel, up to 500 clients at once",
      "Add clients one at a time in the app",
    ],
    relatedFeatures: ["compliance-calendar", "client-portal"],
    sources: [HOME, SIGNUP],
    faqs: [
      {
        question: "How do we move our existing client list in?",
        answer: "Fill in the Excel template with up to 500 clients; a test run checks every row before anything is created. You can also add clients one at a time.",
      },
    ],
  },
  {
    slug: "team-management",
    name: "Team Management",
    summary: "Roles, workloads and accountability per team member.",
    category: "modules",
    hasPage: true,
    body: [
      "Team Management covers the people who do the work. Each member of the firm has a role, a workload and accountability for what they own, from partners to managers and senior staff.",
      "Firm owners and administrators invite team members and assign their roles, and they are responsible for the people they invite. Roles also decide what each person can open, because document access depends on role.",
    ],
    howItWorks: [
      "Create the firm workspace.",
      "Invite your team and assign each member a role.",
      "Work moves through the prepare, review and file stages, with an owner at every stage.",
      "Each member's workload shows up in reports.",
    ],
    capabilities: [
      "A role for each team member, such as partner, manager and senior",
      "Workload tracked for each member",
      "An owner named at each stage of a filing",
      "Document access by role, with row-level security",
      "Two-factor authentication, mandatory for firm owners",
    ],
    audience: ["Partners", "Managers", "Firm administrators"],
    relatedFeatures: ["task-workflow", "reports-analytics", "audit-trail"],
    sources: [HOME, SIGNUP, "https://trackysuite.com/terms"],
  },
  {
    slug: "audit-trail",
    name: "Audit Trail",
    summary: "Who did what, to which record, and when, written down permanently.",
    category: "modules",
    hasPage: true,
    body: [
      "TrackySuite records every action in a permanent audit trail: who did what, to which record, and when. The trail is written by the database itself rather than relying on people to remember.",
    ],
    capabilities: [
      "Every action logged permanently",
      "Records the person, action, record and time",
      "Written by the database itself",
      "Document views logged separately",
      "Powers Reports & Analytics, so every reported number links back to a logged action",
    ],
    problem: "Without a permanent record, who filed, approved or downloaded something depends on people's memory.",
    audience: ["Partners", "Firm administrators"],
    faqs: [
      { question: "Can audit entries be edited?", answer: "TrackySuite describes the trail as permanent and written by the database itself, so actions are recorded as they happen rather than entered by staff." },
    ],
    relatedFeatures: ["document-vault", "reports-analytics"],
    sources: [HOME, ABOUT],
  },
  {
    slug: "reports-analytics",
    name: "Reports & Analytics",
    summary: "Filings by status, workload by member and deadlines ahead, each number traceable to a logged action.",
    category: "modules",
    hasPage: true,
    body: [
      "Reports & Analytics shows how the firm is doing in charts. It shows filings by status, workload by team member and the deadlines coming up.",
      "Every number in a report traces back to a logged action in the audit trail, so the figures reflect what actually happened rather than what someone typed in.",
    ],
    capabilities: [
      "Filings broken down by status",
      "Workload by team member",
      "Deadlines ahead",
      "Every number traceable to a logged action",
    ],
    relatedFeatures: ["practice-dashboard", "audit-trail", "compliance-position"],
    sources: [HOME],
  },
  {
    slug: "compliance-position",
    name: "Compliance Position",
    summary: "For any client and financial year: every obligation, its status, and why an obligation does not apply.",
    category: "modules",
    hasPage: true,
    body: [
      "The compliance position is a view of one client for a chosen financial year. It lists every statutory obligation for that client together with its current status.",
      "Where an obligation does not apply, the position gives the reason, for example a client with no GSTIN, or a registration issued part-way through the year. It comes from the calendar built from the client's registrations, not from a list kept by hand.",
    ],
    capabilities: [
      "Available for any client and any financial year",
      "Lists every obligation for the client",
      "Shows the status of each obligation",
      "States the reason when an obligation does not apply",
    ],
    relatedFeatures: ["compliance-calendar", "client-management", "reports-analytics"],
    sources: [ABOUT],
  },
];

export const trackysuite: Product = {
  id: "trackysuite",
  slug: "trackysuite",
  name: "TrackySuite",
  shortDescription:
    "Practice management for Indian CA, CS and tax firms: every client's statutory deadlines, tasks, documents and reminders in one system.",
  longDescription:
    "TrackySuite is software for running Indian chartered accountancy, company secretary and tax practices. It keeps one main record per client, and the registrations on that record (GSTIN, TAN, PAN, CIN, LLPIN, PTRC, PTEC) decide which returns the client owes and from which period, so the statutory calendar is never typed in by hand.\n\nThe list of compliances is kept up to date by TrackySuite: 110 statutory filings across 8 entity types, covering GST, TDS and TCS, income tax, ROC/MCA, PF and ESI, professional tax and FEMA/RBI. Every scheduled filing gets reminders 14, 7, 3 and 1 day before it is due, passed to a manager if work is still open.\n\nWork moves through four stages in which the person who prepared a return cannot sign it off, and the database writes a permanent audit trail of every action. Partners see due, in-review, filed and overdue counts on one dashboard, while clients follow their own status, upload documents and raise tickets through a client portal.\n\nTrackySuite is built and operated by Stolvix Softwares with practising chartered accountants, whose review notes shape what gets built next.",
  tagline: "Your entire practice, in orbit around one system.",
  category: "finance-compliance",
  secondaryCategories: ["operations-it"],
  subcategory: "practice-management",
  primaryUseCase: "Compliance tracking for accounting practices",
  audience: ["Chartered accountant (CA) firms", "Company secretary (CS) firms", "Tax practices"],
  platforms: ["web"],
  market: "India",
  status: "live",
  verification: { relationship: "pending", publicSale: "confirmed" },
  featured: true,
  websiteUrl: "https://trackysuite.com/",
  appUrl: "https://trackysuite.com/signup",
  publisher: { name: "Stolvix Softwares" },
  featureCategories,
  features,
  howItWorks: [
    { title: "Create your firm", description: "Set up the firm workspace with the firm name, your name, email and a password, then pick a plan. The free trial includes everything in the chosen plan and needs no card." },
    { title: "Bring in clients", description: "Import up to 500 clients from the Excel template, where a dry run checks every row before anything is created, or add clients one at a time in the app." },
    { title: "Tick registrations", description: "Each client's GSTIN, TAN, PAN, CIN, LLPIN, PTRC and PTEC decide which returns they owe and from when. Their statutory calendar fills in as soon as the registrations are ticked." },
    { title: "Run the work", description: "Invite your team and assign roles. Filings move through prepare, review and file with an owner at each stage, while reminders go out 14, 7, 3 and 1 day before every scheduled filing." },
    { title: "Open the portal to clients", description: "Clients log in to see their compliance status, upload documents into their own vault, download filed returns and raise tickets, while partners track every client on the Practice Dashboard." },
  ],
  productIndustries: [
    {
      slug: "ca-cs-tax-practices",
      name: "CA, CS and tax practices in India",
      summary: "Built for Indian chartered accountancy, company secretary and tax firms that handle statutory work for dozens to hundreds of clients.",
      body: [
        "TrackySuite is designed for practices where a missed deadline means a penalty for the client and damage to the firm's reputation. It is built with practising chartered accountants, and their review notes shape what gets built next.",
        "The statutory catalogue covers GST, TDS and TCS, income tax, ROC/MCA, PF and ESI, professional tax and FEMA/RBI. It applies to entity types from individuals and HUFs to partnerships, LLPs, OPCs, private and public limited companies, and trusts, societies and Section 8 companies.",
      ],
      challenges: [
        "Tracking statutory deadlines for many clients in spreadsheets",
        "Making sure each client is scheduled only for the returns their registrations actually require",
        "Keeping the person who prepares a return separate from the person who signs it off",
        "Clients calling for updates and sending documents over WhatsApp or email",
      ],
      howItHelps: [
        "Each client's registrations (GSTIN, TAN, PAN, CIN, LLPIN, PTRC, PTEC) decide which returns they owe and from which period.",
        "A four-stage review process stops the person who prepared a return from also approving it.",
        "Reminders 14, 7, 3 and 1 day before each due date pass any filing that is still open up to a manager.",
        "A client portal lets clients check their status, upload documents and raise tickets.",
        "For any client and financial year, a compliance position shows every obligation, its status, and why an obligation does not apply where that is the case.",
      ],
      features: ["compliance-calendar", "task-workflow", "deadline-reminders", "client-portal", "client-management", "audit-trail"],
      sources: [HOME, ABOUT],
    },
  ],
  supportTopics: [
    {
      slug: "getting-started",
      name: "Setting up your firm",
      summary: "How a firm starts on TrackySuite, from creating a workspace to having a live compliance calendar.",
      body: [
        "You create the firm workspace first and choose a plan after that. Once clients are in and their registrations are ticked, the statutory calendar builds itself, so there is no separate data-entry project.",
      ],
      steps: [
        "Create your firm with the firm name, your name, email and a password.",
        "Pick a plan. New firms start on a free trial with no card required.",
        "Import your client list from Excel (with a test run first) or add clients one at a time.",
        "Tick each client's registrations so their statutory calendar fills in.",
        "Invite your team, assign roles and work through the prepare, review and file stages.",
      ],
      features: ["client-management", "compliance-calendar", "task-workflow"],
      faqs: [
        {
          question: "What support do we get?",
          answer: "Founding firms are set up directly by the TrackySuite team. After that, you can raise support tickets from inside the app, and a help library has a guide for every screen.",
        },
      ],
      sources: [HOME, SIGNUP],
    },
    {
      slug: "trial-and-billing",
      name: "Trial, billing and cancellation",
      summary: "How the trial, billing cycles, plan changes and cancellation work.",
      body: [
        "Paid plans are billed in advance, monthly or yearly, through TrackySuite's payment provider. Prices exclude GST. 18% GST is added at checkout, and a registered firm can claim it as input credit.",
      ],
      keyPoints: [
        "The trial includes everything in the plan you choose and needs no card. If you don't continue, nothing is charged.",
        "If a trial or paid period ends without an active subscription, the workspace becomes read-only until billing is restored.",
        "Plan changes take effect at the end of the current billing cycle unless stated otherwise.",
        "Cancelling stops future renewals. You keep access until the end of the paid period.",
        "Annual billing costs less than paying monthly.",
      ],
      sources: [HOME, "https://trackysuite.com/terms"],
    },
    {
      slug: "your-data",
      name: "Data ownership, export and deletion",
      summary: "Who owns the data a firm enters into TrackySuite and how to get it out.",
      body: [
        "Your firm owns the data it enters. TrackySuite processes that data only to provide the service, and it does not sell data or use client compliance data for advertising.",
      ],
      keyPoints: [
        "You can export your data at any time, including during the trial.",
        "If you don't continue after the trial, TrackySuite will hand your data over on request.",
        "Firms can ask for their data to be exported or deleted, subject to applicable law and statutory record-keeping rules.",
        "Data is kept while the account is active and for as long as legal obligations require.",
        "Your firm remains responsible for the accuracy of its compliance data and for meeting its own statutory deadlines. TrackySuite does not replace professional judgement.",
      ],
      sources: [HOME, SIGNUP, PRIVACY, "https://trackysuite.com/terms"],
    },
    {
      slug: "email-delivery",
      name: "How TrackySuite sends email",
      summary: "Which emails TrackySuite sends, and how a firm can send them from its own domain.",
      body: [
        "Service emails are an essential part of the product, not marketing. They cover invitations, filing reminders, billing notices and support updates.",
      ],
      keyPoints: [
        "If a firm sets up its own verified mail server (SMTP), email to its team and clients is sent from the firm's own domain.",
        "Without that, email is sent from TrackySuite's standard sending address.",
        "A firm's email login details are stored encrypted.",
        "Reminder emails go out 14, 7, 3 and 1 day before each due date.",
      ],
      features: ["deadline-reminders"],
      sources: [PRIVACY, HOME],
    },
    {
      slug: "contacting-trackysuite",
      name: "Contacting TrackySuite",
      summary: "How to book a demo or reach TrackySuite about sales, support or security.",
      body: [
        "The contact page handles demo bookings, sales and pricing questions, and anything else. A demo covers the compliance calendar, client onboarding and how the whole practice runs in one system.",
      ],
      keyPoints: [
        "General email: info@trackysuite.com",
        "Support and security reports: support@trackysuite.com. Security reports are read first.",
        "Enterprise enquiries get a response within one business day.",
        "Existing customers can raise support tickets inside the app.",
      ],
      links: [{ label: "TrackySuite contact page", href: "https://trackysuite.com/contact" }],
      sources: ["https://trackysuite.com/contact", ABOUT, HOME],
    },
  ],
  benefits: [
    { title: "Statutory coverage built in", description: "110 statutory filings across GST, income tax, ROC/MCA, labour and FEMA/RBI come built in for 8 entity types, from individuals and HUFs to public limited companies. Due dates are set up as rules kept current by TrackySuite, so the firm doesn't keep its own deadline list." },
    { title: "Only the returns a client actually owes", description: "Scheduling follows each client's registrations: a client without a GSTIN never gets a GST return, and a registration issued in July doesn't create an April period. The calendar is correct for each client from the moment registrations are ticked." },
    { title: "Review before filing", description: "Filings move through four stages with an owner at each stage, and the person who prepared a return cannot also sign it off. Approved work is counted separately from filed work, so dashboard numbers are accurate." },
    { title: "Fewer \"any update?\" calls", description: "Each client gets a portal showing their own compliance status, with document upload, downloads of filed returns and support tickets. The firm controls what each client can see." },
    { title: "A permanent record of who did what", description: "Every action is written to an audit trail by the database itself, and document views are logged separately. Reports link each number back to a logged action." },
    { title: "Quick setup", description: "An existing client list comes in from an Excel template of up to 500 clients, with dropdowns and a filled-in example row. A test run checks every row before anything is created." },
  ],
  security: [
    { title: "Encrypted documents", description: "Documents stored in each client's vault are encrypted. Sensitive details, such as a firm's email server (SMTP) login, are also stored encrypted." },
    { title: "Access by role", description: "Access to documents depends on each person's role and is enforced record by record in the database (row-level security), and documents are shown only to authorised users. Clients see only their own records in the portal, with the firm controlling what is visible." },
    { title: "Each firm's data kept separate", description: "Each firm's data is kept separate in the database, and TrackySuite enforces access controls between firms. It states that it does not sell data or use client compliance data for advertising." },
    { title: "Permanent audit log", description: "Every action is written to a permanent audit log by the database itself, recording who did what, to which record and when. Every document view is logged separately." },
    { title: "Two-factor authentication", description: "Two-factor authentication is mandatory for firm owners, who control the firm's workspace and invite its team." },
    { title: "Export and deletion", description: "Firms can request export or deletion of their data, subject to applicable law and statutory record-keeping. Security reports go to support@trackysuite.com and are read first." },
  ],
  pricing: {
    currency: "INR",
    unit: "month",
    trial: "Free trial available, no card required",
    note: "Prices shown are the per-month rate on annual billing; monthly billing costs more (Solo ₹1,000, Practice ₹2,000, Firm ₹4,000, Multi-Partner ₹7,500). TrackySuite says annual billing saves up to 11%. All prices exclude 18% GST, claimable as input credit by a registered firm.",
    asOf: "2026-10-07",
    sourceUrl: "https://trackysuite.com/#pricing",
    plans: [
      { name: "Solo", price: "₹900", period: "month", description: "For proprietors running a small book of clients: up to 25 clients and 5 staff seats. ₹1,000 billed monthly, or ₹900 a month on annual billing.", features: ["Up to 25 clients", "5 staff seats", "Free trial, no card required"], cta: { label: "Start free trial", href: "https://trackysuite.com/signup" } },
      { name: "Practice", price: "₹1,800", period: "month", description: "For growing practices that need a review chain between preparer and approver: up to 60 clients and 15 staff seats. ₹2,000 billed monthly, or ₹1,800 a month on annual billing.", features: ["Up to 60 clients", "15 staff seats", "Free trial, no card required"], cta: { label: "Start free trial", href: "https://trackysuite.com/signup" } },
      { name: "Firm", price: "₹3,600", period: "month", description: "For multi-office firms running a full compliance calendar, and the plan TrackySuite marks as most chosen: up to 150 clients and 40 staff seats. ₹4,000 billed monthly, or ₹3,600 a month on annual billing.", features: ["Up to 150 clients", "40 staff seats", "Free trial, no card required"], cta: { label: "Start free trial", href: "https://trackysuite.com/signup" }, recommended: true },
      { name: "Multi-Partner", price: "₹6,750", period: "month", description: "For firms with 6 to 10 partners: up to 400 clients with unlimited staff seats. ₹7,500 billed monthly, or ₹6,750 a month on annual billing.", features: ["Up to 400 clients", "Unlimited staff seats", "Free trial, no card required"], cta: { label: "Start free trial", href: "https://trackysuite.com/signup" } },
      { name: "Enterprise", price: "Custom", description: "For practices above 400 clients, priced per practice and billed yearly, with a response to enquiries within one business day.", features: ["Unlimited clients and seats", "Dedicated success manager", "Custom integrations on request", "Billed yearly, plus 18% GST"], cta: { label: "Contact sales", href: "/contact-us?type=sales&product=trackysuite" } },
    ],
  },
  supportUrl: "https://trackysuite.com/contact",
  useCases: [
    { title: "Never missing a statutory deadline", description: "A practice with a few hundred clients ticks each client's registrations once; GST, TDS, ROC, PF/ESI and income-tax dates are then added automatically, and reminders go out 14, 7, 3 and 1 day before each one is due." },
    { title: "Review before anything is filed", description: "A senior prepares a GSTR-3B, a manager reviews and approves it, and only then is it filed; the preparer cannot sign off their own return and every step is logged." },
    { title: "Collecting documents from clients", description: "Instead of documents arriving scattered across WhatsApp and email, clients upload them into their own vault through the portal, and the firm sees which documents are still to come." },
    { title: "Replacing the Monday status meeting", description: "Partners open the Practice Dashboard to see what is due, in review, filed and overdue across every client, with workload by member in Reports & Analytics." },
    { title: "Answering \"is this client compliant for the year?\"", description: "The compliance position for a client and financial year lists every obligation and its status, and explains why an obligation does not apply where that is the case." },
  ],
  faqs: [
    { question: "Does TrackySuite cover all Indian statutory deadlines?", answer: "GST (GSTR-1/3B/9), TDS quarterly returns, ROC/MCA annual filings, PF/ESI monthly returns and income-tax dates come built in. TrackySuite keeps a list of 110 statutory filings across 8 entity types up to date, and tasks are scheduled automatically for each client based on their registrations." },
    { question: "Can I bring in my existing clients?", answer: "Yes. Download the Excel template, fill in up to 500 clients per import, and a test run checks every row before anything is created. You can also add clients one at a time in the app." },
    { question: "Can my clients see their own filings and documents?", answer: "Every client gets portal access to see their own compliance status, upload documents into their vault, download what the firm has filed for them and raise support tickets. The firm controls what is visible to each client." },
    { question: "Is our data secure?", answer: "Stored documents are encrypted, access depends on each person's role (with row-level security), and each firm's data is kept separate in the database. Every action goes into a permanent audit log, and every document view is logged separately." },
    { question: "How are accounts secured?", answer: "Two-factor authentication is mandatory for firm owners. Roles decide what each team member can open." },
    { question: "Do prices include GST?", answer: "No. Prices exclude GST, and 18% GST is added at checkout. A registered firm can claim it as input credit." },
    { question: "What does the free trial include?", answer: "Everything in the plan you choose, with no card required, so you can add real clients and run real filings. If you don't continue, nothing is charged and TrackySuite will hand your data over on request." },
    { question: "Can email go out from our own domain?", answer: "Yes, if the firm sets up its own verified mail server (SMTP); mail to its team and clients is then sent from the firm's domain. Otherwise email goes from TrackySuite's standard sending address, and a firm's email login details are stored encrypted." },
    { question: "What support do we get?", answer: "Founding firms are set up directly by the TrackySuite team. After that, support tickets are raised from inside the app and answered by the team, and a help library written for Indian practice workflows has a guide for every screen." },
    { question: "Who builds TrackySuite?", answer: "TrackySuite is built and operated by Stolvix Softwares, together with practising chartered accountants whose review notes shape what gets built next." },
  ],
  industries: ["accounting-tax-practices"],
  sources: [HOME, ABOUT, PRIVACY, SIGNUP, LOGIN, "https://trackysuite.com/terms"],
  lastVerified: "2026-10-08",
};
