import type { Product } from "@/content/types";

const Z = "https://zorfly.com";

export const zorfly: Product = {
  id: "zorfly",
  slug: "zorfly",
  name: "Zorfly",
  shortDescription:
    "Five-minute daily communication and grammar training for teams, with AI feedback and team analytics.",
  longDescription:
    "Zorfly is AI-based in-house training and testing for communication, grammar and brand quality. Each person completes one short mission a day, a few questions on a single concept such as softening hard requests, sized to fit into about five minutes.\n\nThe content is a fixed core curriculum of around 250 selected questions across eight grammar areas (domains), starting with a short test of each learner's starting level (a baseline diagnostic) when they join. When a learner gets something wrong, an AI explanation generated with Anthropic Claude explains why, alongside personalised recommendations.\n\nLearners level up by earning XP, keeping a daily streak and unlocking badges while their weakness profile shrinks. On the Hive Pro plan, managers get team analytics across departments, weakness reports, monthly domain evaluations and per-role question variations.\n\nThe Solo Bee plan is free forever, Hive Pro is priced per seat with a 7-day trial, and Queen Bee adds volume pricing, SSO / SAML (single sign-on) on request and a custom DPA (data processing agreement) for larger organisations.",
  tagline: "Five minutes a day. Sharper comms forever.",
  category: "hr-people",
  subcategory: "learning-development",
  primaryUseCase: "Improving team writing and communication",
  audience: ["Teams", "People managers", "L&D owners"],
  platforms: ["web"],
  market: "Global",
  status: "live",
  verification: { relationship: "pending", publicSale: "confirmed" },
  websiteUrl: `${Z}/`,
  appUrl: `${Z}/signup`,
  // Zorfly's public site is short. Only features whose details are stated across
  // the home, pricing, sign-up and privacy pages get their own page.
  featureCategories: [
    { slug: "your-daily-buzz", name: "Your daily buzz", description: "Quick, bite-sized challenges to sharpen written communication." },
    { slug: "level-up", name: "Level up", description: "XP, streaks, badges and a curriculum that shows each learner how their weakness profile shrinks, session by session." },
    { slug: "for-teams", name: "For teams", description: "Hive Pro features for managers: monthly domain evaluations, per-role question variations and owner, admin and member roles." },
  ],
  features: [
    {
      slug: "five-minute-lessons",
      name: "Five-minute daily missions",
      summary: "Bite-sized concepts you can finish in a coffee break: one short mission a day.",
      category: "your-daily-buzz",
      body: [
        "Zorfly is built around one short mission a day. Each mission covers a single communication concept and is sized to fit into a coffee break, so training fits into the workday rather than taking place in a classroom.",
        "Missions feed the learner's progress: completing them earns XP and keeps the daily streak going.",
      ],
      howItWorks: [
        "Open Zorfly to see today's mission, with its topic, number of questions and estimated time.",
        "Answer the short set of questions.",
        "Read the AI explanation for any wrong answer.",
        "Earn XP and extend the daily streak.",
      ],
      capabilities: ["One mission a day", "Bite-sized concepts finishable in a few minutes", "XP and streak credit for completed missions"],
      problem: "Communication training delivered as classroom sessions competes with the workday and is easy to skip.",
      audience: ["Individual learners", "Teams"],
      faqs: [
        { question: "How long does a mission take?", answer: "Missions are designed to fit a coffee break. Zorfly's example mission, \"Softening hard requests\", has five questions and takes about four minutes." },
        { question: "How many missions are there per day?", answer: "Zorfly is built around one short mission a day; completing it earns XP and keeps the daily streak going." },
      ],
      relatedFeatures: ["ai-coaching", "xp-streaks-and-badges", "eight-grammar-domains"],
      sources: [`${Z}/`],
      highlight: true,
      hasPage: true,
    },
    {
      slug: "ai-coaching",
      name: "AI coaching",
      summary: "Wrong-answer explanations designed to teach rather than scold.",
      category: "your-daily-buzz",
      body: [
        "When a learner gets a question wrong, Zorfly explains why. Zorfly describes these explanations as meant to teach, never to scold, and pairs them with personalised recommendations.",
        "Zorfly's privacy policy states that AI feedback is generated with Anthropic Claude, and that learner answers are sent to Anthropic for processing under Anthropic's data-processing terms.",
      ],
      capabilities: [
        "AI explanations for wrong answers, on every plan including the free Solo Bee",
        "Personalised recommendations alongside explanations",
        "Up to 500 AI calls per seat per month on Hive Pro",
        "Higher AI quotas on the Queen Bee plan",
      ],
      problem: "A bare right-or-wrong mark tells a learner they slipped but not why, so the same mistake comes back.",
      audience: ["Individual learners", "Teams"],
      faqs: [
        { question: "Which AI does Zorfly use?", answer: "Zorfly's privacy policy says AI feedback is generated with Anthropic Claude, and learner answers are sent to Anthropic for processing under Anthropic's data-processing terms." },
        { question: "Is AI coaching on the free plan?", answer: "Yes. AI wrong-answer explanations and personalised recommendations are included on Solo Bee. Hive Pro allows up to 500 AI calls per seat per month, and Queen Bee offers higher quotas." },
      ],
      relatedFeatures: ["five-minute-lessons", "weakness-reports", "personalized-recommendations"],
      sources: [`${Z}/`, `${Z}/pricing`, `${Z}/signup`, `${Z}/legal/privacy`],
      highlight: true,
      hasPage: true,
    },
    {
      slug: "weakness-reports",
      name: "Weakness reports",
      summary: "Find the patterns behind recurring mistakes so they can be fixed on purpose, rather than correcting the same slip-ups one at a time.",
      category: "your-daily-buzz",
      highlight: true,
      hasPage: true,
      body: [
        "Weakness reports look across a learner's answers for the patterns behind repeated mistakes, so they can be fixed on purpose rather than one error at a time.",
        "Each learner has a weakness profile, which starts from the onboarding baseline diagnostic and shrinks session by session as daily missions are completed. Weakness reports are included with team analytics on the Hive Pro plan.",
      ],
      problem: "Correcting individual errors as they happen doesn't show which grammar or communication habits keep causing them.",
      capabilities: [
        "Shows the patterns behind a learner's recurring mistakes.",
        "Maintains a weakness profile that shrinks as training progresses.",
        "Starts from the baseline diagnostic taken at onboarding.",
        "Included with team analytics on Hive Pro.",
      ],
      audience: ["People managers", "L&D owners", "Teams"],
      relatedFeatures: ["team-analytics", "onboarding-baseline-diagnostic", "ai-coaching"],
      sources: [`${Z}/`, `${Z}/pricing`],
    },
    {
      slug: "team-analytics",
      name: "Team analytics",
      summary: "Organisation-wide trends so managers see what teams need next.",
      category: "your-daily-buzz",
      body: [
        "Team analytics give managers organisation-wide trends across departments, so they can see what each team needs to work on next.",
        "They come with weakness reports, which show the patterns behind recurring mistakes so they can be fixed on purpose. Both are part of the Hive Pro plan.",
      ],
      capabilities: [
        "Trends across the whole organisation",
        "Analytics across departments",
        "Weakness reports showing the patterns behind repeated mistakes",
        "Monthly domain evaluations on Hive Pro",
      ],
      audience: ["People managers", "Teams"],
      problem: "Without a view across the organisation, managers can't tell which teams or departments need communication training next.",
      faqs: [
        { question: "Which plan includes team analytics?", answer: "Team analytics and weakness reports are part of Hive Pro at $9.99 per seat per month, which starts with a 7-day trial. They are not on the free Solo Bee plan." },
      ],
      relatedFeatures: ["weakness-reports", "monthly-domain-evaluations", "owner-admin-and-member-roles"],
      sources: [`${Z}/`, `${Z}/pricing`, `${Z}/signup`],
      highlight: true,
      hasPage: true,
    },
    {
      slug: "xp-streaks-and-badges",
      name: "Progress dashboard: XP, streaks and badges",
      summary: "Earn XP, keep a daily streak and unlock badges as you train.",
      category: "level-up",
      body: [
        "Each learner has a dashboard that shows how their training is going: the current daily streak, total XP, badges unlocked and their level, next to today's mission.",
        "Zorfly frames this as levelling up: earning XP and badges while the learner's weakness profile shrinks session by session.",
      ],
      capabilities: [
        "Current daily streak",
        "Total XP earned",
        "Badges unlocked out of the available set, such as a seven-day-streak badge",
        "Learner level",
        "Today's mission shown on the dashboard",
      ],
      relatedFeatures: ["five-minute-lessons", "weakness-reports"],
      sources: [`${Z}/`, `${Z}/pricing`],
      hasPage: true,
    },
    {
      slug: "eight-grammar-domains",
      name: "Curriculum and assessments",
      summary: "A fixed core curriculum of around 250 selected questions across eight grammar domains.",
      category: "level-up",
      body: [
        "Zorfly's content is a fixed core curriculum of around 250 selected questions spread across eight grammar domains. The full curriculum is included on the free Solo Bee plan.",
        "Learners start with a baseline diagnostic at onboarding, and teams on Hive Pro add monthly evaluations by domain and question variations tailored to each role.",
      ],
      capabilities: [
        "Eight grammar domains",
        "Around 250 selected questions",
        "Onboarding baseline diagnostic",
        "Monthly domain evaluations (Hive Pro)",
        "Per-role question variations (Hive Pro)",
      ],
      relatedFeatures: ["onboarding-baseline-diagnostic", "monthly-domain-evaluations", "per-role-question-variations"],
      sources: [`${Z}/pricing`, `${Z}/signup`],
      hasPage: true,
    },
    { slug: "onboarding-baseline-diagnostic", name: "Onboarding baseline diagnostic", summary: "A diagnostic taken when a learner joins establishes their starting point across the grammar domains; it is included on the free Solo Bee plan.", category: "level-up" },
    { slug: "personalized-recommendations", name: "Personalized recommendations", summary: "AI recommendations delivered alongside wrong-answer explanations, pointing each learner to what to work on next; included on every plan.", category: "level-up" },
    { slug: "monthly-domain-evaluations", name: "Monthly domain evaluations", summary: "A monthly evaluation for each grammar domain lets teams on Hive Pro measure progress over time rather than mission by mission.", category: "for-teams" },
    { slug: "per-role-question-variations", name: "Per-role question variations", summary: "On Hive Pro, questions are varied by role, so different roles in a team practise with versions suited to their work.", category: "for-teams" },
    { slug: "owner-admin-and-member-roles", name: "Owner, admin and member roles", summary: "Hive Pro workspaces separate owners, admins and members; Queen Bee adds SSO / SAML on request for larger organisations.", category: "for-teams" },
  ],
  security: [
    { title: "Limited data collection", description: "Zorfly's privacy policy states that it collects account information (name and email), training-progress data and standard web logs. Privacy questions go to privacy@zorfly.com." },
    { title: "AI processing disclosed", description: "AI feedback is generated with Anthropic Claude; learner answers are sent to Anthropic for processing under Anthropic's data-processing terms." },
    { title: "No sale of personal data", description: "Zorfly states that it does not sell personal data." },
    { title: "Role-based workspace access", description: "Hive Pro workspaces have owner, admin and member roles, so not every member has administrative control." },
    { title: "Enterprise options on request", description: "The Queen Bee plan lists SSO / SAML on request and a custom DPA (data processing agreement) / security review for buyers with formal purchasing processes." },
    { title: "Policies still being finalised", description: "Zorfly's privacy policy and terms (last updated 30 May 2026) state they are being finalised; for pilot customers, the signed pilot agreement governs." },
  ],
  pricing: {
    currency: "USD",
    unit: "seat",
    trial: "7-day trial on Hive Pro",
    note: "Zorfly states that final pricing is still being confirmed.",
    asOf: "2026-10-08",
    sourceUrl: `${Z}/pricing`,
    plans: [
      { name: "Solo Bee", price: "$0", description: "Free forever, for curious learners who want to try a few sessions. Includes the full curriculum and AI explanations, but not team analytics.", features: ["Full curriculum (8 domains)", "Baseline diagnostic", "AI explanations", "XP, streaks, badges", "Personalized recommendations"], cta: { label: "Start free", href: `${Z}/signup` } },
      { name: "Hive Pro", price: "$9.99", period: "seat / month", description: "Per seat, for teams who care about lasting communication quality. Adds manager analytics, monthly evaluations and workspace roles; starts with a 7-day trial.", features: ["Everything in Solo Bee", "Team analytics + weakness reports", "Monthly domain evaluations", "Per-role question variations", "Up to 500 AI calls per seat per month", "Owner / admin / member roles"], cta: { label: "Start 7-day trial", href: `${Z}/signup` }, recommended: true },
      { name: "Queen Bee", price: "Custom", description: "Custom pricing for larger organisations and buyers with formal purchasing processes, adding volume seats, security review and SSO on request.", features: ["Everything in Hive Pro", "Volume seat pricing", "Higher AI quotas", "SSO / SAML on request", "Priority support", "Custom DPA / security review"], cta: { label: "Contact sales", href: "/contact-us?type=sales&product=zorfly" } },
    ],
  },
  useCases: [
    { title: "Raising writing quality across departments", description: "A company gives every team member one five-minute mission a day, then uses Hive Pro's team analytics to see trends by department and decide what each team should work on next." },
    { title: "Finding where to start", description: "New learners take a baseline diagnostic at onboarding, which sets their starting weakness profile across the eight grammar domains before daily missions begin." },
    { title: "Trying it as an individual", description: "A curious learner uses the free Solo Bee plan to work through the full curriculum with AI explanations, XP, streaks and badges, with no team set up." },
    { title: "Measuring progress month to month", description: "Teams on Hive Pro use monthly domain evaluations to check how each grammar domain is improving over time, alongside weakness reports." },
  ],
  benefits: [
    { title: "Training that fits the workday", description: "One mission a day of a few questions, about four or five minutes, replaces classroom sessions. Learners finish it in a coffee break." },
    { title: "Explanations, not just marks", description: "Every wrong answer gets an AI explanation meant to teach rather than scold, plus personalised recommendations. This is included on the free plan." },
    { title: "Reasons to come back", description: "XP, a daily streak, badges and levels make progress visible. The weakness profile shrinks session by session as missions are completed." },
    { title: "Visibility for managers", description: "Hive Pro gives organisation-wide trends across departments and weakness reports. Managers can see what each team needs next." },
  ],
  howItWorks: [
    { title: "Start your hive", description: "Sign up with your company name, name, work email and password, then select \"Create my organization\"." },
    { title: "Invite your team", description: "Bring team members into the workspace. On Hive Pro, owner, admin and member roles separate who manages the hive." },
    { title: "Take the baseline diagnostic", description: "Each learner starts with an onboarding diagnostic that shows their weak areas across the eight grammar domains." },
    { title: "Complete one mission a day", description: "Answer a short set of questions, read the AI explanation for anything missed, and earn XP and streak credit." },
    { title: "Review progress", description: "Learners watch their weakness profile shrink, and managers on Hive Pro use team analytics, weakness reports and monthly domain evaluations." },
  ],
  faqs: [
    { question: "What does the curriculum cover?", answer: "A fixed core curriculum of around 250 selected questions across eight grammar domains. The full curriculum is included on the free Solo Bee plan." },
    { question: "Is there a free plan?", answer: "Yes. Solo Bee is free forever and includes the full curriculum, the baseline diagnostic, AI explanations, XP, streaks, badges and personalised recommendations. Team features are on Hive Pro." },
    { question: "How much does Hive Pro cost?", answer: "$9.99 per seat per month, starting with a 7-day trial. It adds team analytics, weakness reports, monthly domain evaluations, per-role question variations, up to 500 AI calls per seat per month, and owner, admin and member roles." },
    { question: "Is the pricing final?", answer: "No. Zorfly states that final pricing is still being confirmed, and invites teams to email billing@zorfly.com to lock a price for a pilot." },
    { question: "How long does training take each day?", answer: "Zorfly is built around one short mission a day, sized for a coffee break. Its example mission has five questions and takes about four minutes." },
    { question: "How is AI used?", answer: "AI explains wrong answers and powers personalised recommendations. Zorfly's privacy policy says this feedback is generated with Anthropic Claude, which processes learner answers under its data-processing terms." },
    { question: "Does Zorfly support single sign-on?", answer: "SSO / SAML is listed on request for the custom-priced Queen Bee plan, together with a custom DPA / security review and priority support." },
    { question: "What data does Zorfly collect?", answer: "According to its privacy policy, account information (name and email), training-progress data and standard web logs. Zorfly states that it does not sell personal data." },
    { question: "Can I cancel?", answer: "Zorfly's pricing page says you can cancel anytime. For pilot customers, terms are governed by the signed pilot agreement." },
  ],
  supportTopics: [
    {
      slug: "create-your-workspace",
      name: "Creating your Zorfly workspace",
      summary: "How to start a Zorfly workspace for your company and bring your team in.",
      body: ["A Zorfly workspace (a \"hive\") is created for a company; the person who signs up then invites the team to start training."],
      steps: [
        "Open the sign-up page and enter your company name.",
        "Add your name, work email and a password.",
        "Select \"Create my organization\".",
        "Invite your team to start training.",
      ],
      keyPoints: [
        "Solo Bee is free; Hive Pro starts with a 7-day trial",
        "Owner, admin and member roles are available on Hive Pro",
        "Pricing questions for a pilot go to billing@zorfly.com",
        "Privacy questions go to privacy@zorfly.com and terms questions to legal@zorfly.com",
      ],
      links: [
        { label: "Sign up", href: `${Z}/signup` },
        { label: "Pricing", href: `${Z}/pricing` },
      ],
      features: ["owner-admin-and-member-roles", "onboarding-baseline-diagnostic"],
      sources: [`${Z}/signup`, `${Z}/pricing`, `${Z}/legal/privacy`, `${Z}/legal/terms`],
    },
  ],
  solutions: ["manage-your-people-from-hire-to-growth"],
  sources: [`${Z}/`, `${Z}/pricing`, `${Z}/signup`, `${Z}/legal/privacy`, `${Z}/legal/terms`],
  lastVerified: "2026-10-08",
};
