import type { Feature, FeatureCategory, Product } from "@/content/types";

const HOME = "https://usezuzu.com/";
const TRIAL = "https://usezuzu.com/trial";

const featureCategories: FeatureCategory[] = [
  {
    slug: "capture",
    name: "Capture",
    description: "What the Windows agent records on the device, and how private content is protected.",
    body: [
      "Capture in ZUZU happens on the employee's Windows machine. The agent checks which application and window are active, records attendance and idle time, and takes periodic screenshots, painting out private content on the device before anything is written or uploaded.",
      "ZUZU states its limits openly: the agent is Windows-only, policy is set per organisation, and on personal laptops capture can be restricted to the hours between punch-in and punch-out.",
    ],
  },
  {
    slug: "reporting",
    name: "Reporting",
    description: "Reports, insights and exports produced from the day's activity.",
    body: [
      "ZUZU treats capture as only half the job. Its reporting engine reads each day's activity, writes a report per employee on a schedule, and delivers digests to admins and managers with the evidence attached so a conclusion can be challenged.",
      "Beyond the daily report, Insights looks across the whole workforce record, behaviour-change detection flags when someone's work changes from their own usual pattern, and exports cover CSV, Excel and PDF.",
    ],
  },
  {
    slug: "oversight",
    name: "Oversight",
    description: "People, permissions and the audit trail for admins and managers.",
    body: [
      "ZUZU describes monitoring people as a responsibility, not just a setting to switch on. Admins run the organisation from one portal, managers work in a version of it limited to their own people, and access is given through specific permissions rather than by job title.",
      "Significant events, from employee and team changes to payments and live capture, land in an audit trail that can be filtered by severity, viewed as a timeline and exported.",
    ],
  },
];

const features: Feature[] = [
  /* Capture --------------------------------------------------------- */
  {
    slug: "windows-desktop-agent",
    name: "Windows desktop agent",
    summary: "Installed once per machine and activated with a code; it runs from the system tray and looks after itself.",
    category: "capture",
    highlight: true,
    hasPage: true,
    body: [
      "Employees run a small ZUZU agent on their Windows computer. It is installed once per machine, activated with a code issued by the organisation's administrator, and then runs from the system tray without needing day-to-day attention.",
      "The agent starts with Windows, captures on the schedule the organisation has set, keeps captures queued locally if the network drops, and updates itself from the organisation's own release feed. It ships for Windows only; there is no macOS or Linux build today.",
    ],
    howItWorks: [
      "Download the 64-bit Windows installer (about 80 MB).",
      "Run it; on a new build Windows SmartScreen may warn about an unrecognised publisher.",
      "Setup adds ZUZU to the Start Menu and registers it to start with Windows for the current user.",
      "Paste the 16-character activation code from the administrator's email, entered once, on first launch.",
      "Leave it running in the system tray; it captures on schedule and updates itself.",
    ],
    capabilities: [
      "Starts with Windows and runs in the background",
      "Runs from the system tray with no window to keep open",
      "Queues captures while offline and uploads on reconnect",
      "Self-updates from the organisation's release feed",
      "One-time activation with a code issued from the Employees page",
    ],
    audience: ["Employees", "Admins"],
    faqs: [
      { question: "Which platforms does the desktop agent support?", answer: "Windows only. There is no macOS or Linux build today, and the portal will not offer one until it exists." },
      { question: "What happens when a laptop goes offline?", answer: "The agent keeps captures in a local queue and uploads them when the network returns." },
    ],
    relatedFeatures: ["on-device-privacy-redaction", "activity-monitoring", "consent-gated-tracking-on-personal-laptops"],
    sources: [HOME],
  },
  {
    slug: "on-device-privacy-redaction",
    name: "Screenshots with on-device privacy redaction",
    summary: "Regular screenshots at an interval you set, with private content painted out on the device before anything is saved or uploaded.",
    category: "capture",
    highlight: true,
    hasPage: true,
    body: [
      "ZUZU takes periodic screenshots at an interval the organisation chooses: anywhere from 1 to 15 minutes, or a custom interval. Before an image is written to disk or uploaded, private content is painted out on the employee's own machine, so those pixels never leave it.",
      "Redaction covers password boxes, passwords typed into documents, private windows such as messaging, banking, webmail and password managers, and desktop notifications. Admins decide how long screenshots are kept and can download or delete a single day's captures.",
    ],
    capabilities: [
      "Capture interval from 1 to 15 minutes, or custom",
      "Redaction of password fields and passwords typed into documents",
      "Redaction of private windows: messaging, banking, webmail and password managers",
      "Redaction of desktop notifications",
      "Retention of 30, 90 or 180 days, one year, or indefinitely",
      "Download or delete a single day's captures as a ZIP from the employee record",
    ],
    faqs: [
      { question: "How often are screenshots captured?", answer: "At an interval the organisation sets: 1 to 15 minutes, or a custom interval." },
      { question: "What stops sensitive content from being captured?", answer: "Passwords, private windows such as messaging, banking, webmail and password managers, and desktop notifications are painted out on the device before the image is written or uploaded." },
      { question: "How long are screenshots kept?", answer: "For 30, 90 or 180 days, one year, or indefinitely; the organisation decides." },
    ],
    relatedFeatures: ["windows-desktop-agent", "consent-gated-tracking-on-personal-laptops"],
    sources: [HOME],
  },
  {
    slug: "time-and-attendance",
    name: "Time & attendance",
    summary: "Tracked hours per day, a team attendance roster, and idle or screen-off time reported separately.",
    category: "capture",
    hasPage: true,
    body: [
      "ZUZU records how many hours each employee tracked on a given day and keeps an attendance roster across the whole team, so admins and managers can see who is working without asking.",
      "Idle and screen-off periods are reported separately from active time. ZUZU's point is that a long day and a busy day should not show up as the same number.",
    ],
    capabilities: [
      "Tracked hours per employee per day",
      "Attendance roster across the team",
      "Idle periods reported separately",
      "Screen-off periods reported separately",
    ],
    howItWorks: [
      "The Windows agent starts with the machine and records tracked time on the organisation's schedule.",
      "Idle periods and screen-off periods are logged separately from active time.",
      "Tracked hours roll up per employee per day and into the team attendance roster in the portal.",
      "The figures feed each person's AI daily report and the digests sent to admins and managers.",
    ],
    faqs: [
      { question: "Does idle time count as tracked work?", answer: "ZUZU reports idle and screen-off periods separately from active time, so a long day and a busy day do not show up as the same number." },
      { question: "Who can see the attendance roster?", answer: "Admins see the roster for the organisation. Managers see it only for the people and teams assigned to them." },
    ],
    audience: ["Admins", "Team managers"],
    relatedFeatures: ["activity-monitoring", "consent-gated-tracking-on-personal-laptops", "ai-daily-reports"],
    sources: [HOME],
  },
  {
    slug: "activity-monitoring",
    name: "Activity monitoring",
    summary: "The agent checks which application and window title are active and adds it up into time per application.",
    category: "capture",
    hasPage: true,
    body: [
      "The ZUZU agent regularly checks which application and window are active and turns that into a picture of where the working day goes: time per application, the top applications, and the working rhythm across the day.",
      "Alongside this, ZUZU tracks hours per day and keeps an attendance roster for the team, reporting idle and screen-off periods separately, so a long day and a busy day are not counted as the same thing.",
    ],
    capabilities: [
      "Regular checks of the active application and window title",
      "Per-application time and top applications",
      "Tracked hours per day",
      "Team attendance roster",
      "Idle and screen-off periods reported separately",
    ],
    relatedFeatures: ["time-and-attendance", "ai-daily-reports", "windows-desktop-agent"],
    sources: [HOME],
  },
  {
    slug: "consent-gated-tracking-on-personal-laptops",
    name: "Consent-gated tracking on personal laptops",
    summary: "Employees set to session-only tracking are captured only between punch-in and punch-out.",
    category: "capture",
    hasPage: true,
    body: [
      "For people working on their own laptops, ZUZU can limit tracking to a work session. Employees set up this way are captured only between punch-in and punch-out.",
      "The permission to capture is a short-lived lease (a temporary pass) that the agent has to keep renewing. If the laptop goes offline, the lease simply runs out on its own.",
    ],
    capabilities: [
      "Capture limited to the time between punch-in and punch-out",
      "Permission held as a short-lived lease the agent must renew",
      "Lease expires automatically if the laptop goes offline",
    ],
    faqs: [
      { question: "Can people be monitored on their own laptops?", answer: "Employees set to session-only tracking are captured only between punch-in and punch-out, under a short-lived permission that expires on its own if the laptop goes offline." },
    ],
    howItWorks: [
      "The employee punches in to start a work session, and capture begins.",
      "The agent keeps renewing a short-lived lease for as long as the session runs.",
      "At punch-out, or if the laptop goes offline and the lease lapses, capture stops.",
    ],
    audience: ["Admins", "Employees"],
    relatedFeatures: ["windows-desktop-agent", "on-device-privacy-redaction"],
    sources: [HOME],
  },

  /* Reporting ------------------------------------------------------- */
  {
    slug: "ai-daily-reports",
    name: "AI daily reports",
    summary: "A report per employee per day, written on a schedule, downloadable as a PDF and emailed as a digest.",
    category: "reporting",
    highlight: true,
    hasPage: true,
    body: [
      "ZUZU reads each day's activity and writes a report for every employee. Reports are generated on a schedule rather than on request, so by the time someone opens the report browser (at year, month or day level), the day is already there.",
      "Reports are pushed to the people who need them: an organisation-wide digest goes to admins and a team digest to each manager, in the organisation's timezone, with the PDF attached. Managers can confirm or correct what the engine concluded, and the evidence is attached so a conclusion can be challenged.",
    ],
    problem: "Capturing activity is only half the job; someone still has to turn it into a report before the meeting starts.",
    howItWorks: [
      "The engine reads the day's activity for each employee.",
      "It writes a per-employee report on a schedule.",
      "Digests are emailed (organisation-wide to admins, one per team to each manager) in the organisation's timezone, with the PDF attached.",
      "Managers review the report and confirm or correct its conclusions; corrections feed back into scoring.",
    ],
    capabilities: [
      "One report per employee per day",
      "Browsable by year, month and day",
      "PDF download",
      "Organisation-wide and per-manager email digests",
      "Manager review action with confirm or correct",
      "Reporting on how often reviewers agreed",
    ],
    audience: ["Admins", "Team managers"],
    useCases: [
      { title: "Daily reporting without writing reports", description: "Managers open a report that has already been written for each person, instead of chasing status updates." },
    ],
    relatedFeatures: ["workforce-insights", "behaviour-change-detection", "reports-and-exports"],
    sources: [HOME],
  },
  {
    slug: "workforce-insights",
    name: "Workforce insights",
    summary: "Organisation health, executive highlights, department comparisons, burnout risk and recommendations.",
    category: "reporting",
    hasPage: true,
    body: [
      "Insights is where ZUZU looks across the whole workforce record rather than a single day. It covers organisation health, executive highlights, comparisons between departments, and burnout risk shown as weeks-to-risk (an estimate of how many weeks until someone is at risk).",
      "Recommendations name the observation behind them, and the Insights page includes a question box for asking about the workforce record, alongside standing highlights and notable days. Managers see insights for their own team only.",
    ],
    capabilities: [
      "Organisation health overview",
      "AI executive summary and highlights",
      "Department comparisons",
      "Burnout risk with weeks-to-risk",
      "Recommendations that cite the underlying observation",
      "Question box for the workforce record",
      "Notable days",
    ],
    faqs: [
      { question: "How is burnout risk shown?", answer: "Insights expresses burnout risk as weeks-to-risk rather than as a bare score." },
      { question: "Do managers see organisation-wide insights?", answer: "No. Managers see insights for their own team only; the organisation-wide view is for admins." },
      { question: "Why should I trust a recommendation?", answer: "Each recommendation names the observation behind it, so the reader can check the underlying data instead of taking the conclusion on faith." },
    ],
    audience: ["Admins", "Team managers"],
    relatedFeatures: ["ai-executive-summary", "ask-in-plain-language", "behaviour-change-detection"],
    sources: [HOME],
  },
  {
    slug: "ai-executive-summary",
    name: "AI executive summary",
    summary: "A short AI-written summary on the admin dashboard describing how the day went and pointing out people trending below their own baseline.",
    category: "reporting",
    hasPage: false,
    sources: [HOME],
  },
  {
    slug: "ask-in-plain-language",
    name: "Ask in plain language",
    summary: "A question box on the Insights page for asking about the workforce record, alongside standing highlights, notable days and department benchmarking.",
    category: "reporting",
    hasPage: false,
    sources: [HOME],
  },
  {
    slug: "behaviour-change-detection",
    name: "Behaviour-change detection",
    summary: "Flags when a person's work changes from their own usual pattern and sends it to a review queue.",
    category: "reporting",
    hasPage: true,
    body: [
      "Rather than applying a fixed rule about a job title, ZUZU compares each person's work with their own baseline (how they normally work) and flags when it changes. Flagged items go to a review queue in the portal.",
      "The queue learns from every correction reviewers make. Admins review unusual changes (anomalies) across the organisation; managers see anomalies for their own team only.",
    ],
    capabilities: [
      "Detection against each person's own baseline",
      "Review queue for flagged changes",
      "Learning from reviewer corrections",
      "Anomaly review limited to a manager's own team",
    ],
    howItWorks: [
      "ZUZU compares each person's work with that person's own baseline.",
      "When the work moves away from the baseline, the change is flagged.",
      "Flagged items land in a review queue in the portal: organisation-wide for admins, team-only for managers.",
      "Reviewers confirm or correct each flag, and the queue learns from every correction.",
    ],
    problem: "A fixed rule tied to a job title treats everyone in a role the same; ZUZU instead measures change against how each individual normally works.",
    faqs: [
      { question: "Is behaviour-change detection based on job role?", answer: "No. ZUZU compares each person with their own baseline rather than with a rule about their job title." },
      { question: "What happens to a flag after review?", answer: "Reviewers confirm or correct it, and the review queue learns from every correction it receives." },
    ],
    audience: ["Admins", "Team managers"],
    relatedFeatures: ["ai-daily-reports", "workforce-insights", "manager-workspace"],
    sources: [HOME],
  },
  {
    slug: "team-summary-emails",
    name: "Team summary emails",
    summary: "Weekly report emails and a team daily digest, sent alongside organisation-wide and per-manager digests in the organisation's timezone.",
    category: "reporting",
    hasPage: false,
    sources: [HOME],
  },
  {
    slug: "reports-and-exports",
    name: "Reports & exports",
    summary: "CSV, Excel and PDF exports, weekly report emails, a team daily digest and a full organisation export.",
    category: "reporting",
    hasPage: true,
    body: [
      "ZUZU lets admins and managers take data out of the portal in the format they need: CSV, Excel and PDF exports, with each employee's AI daily report also downloadable as a PDF.",
      "Reports also go out by email: weekly report emails, a team daily digest, and organisation-wide or per-manager digests in the organisation's timezone. When everything is needed in one file, a full organisation export is available.",
    ],
    capabilities: [
      "CSV, Excel and PDF exports",
      "Per-employee daily report as a PDF download",
      "Weekly report emails",
      "Team daily digest",
      "Organisation-wide and per-manager digests in the organisation's timezone",
      "Full organisation export",
      "Audit trail export",
    ],
    audience: ["Admins", "Team managers"],
    relatedFeatures: ["ai-daily-reports", "team-summary-emails", "audit-trail"],
    sources: [HOME],
  },

  /* Oversight ------------------------------------------------------- */
  {
    slug: "manager-workspace",
    name: "Manager workspace",
    summary: "The same portal, limited so managers only reach the people assigned to them.",
    category: "oversight",
    hasPage: true,
    body: [
      "ZUZU has three parts that share the same data: the agent employees run, the admin portal for the organisation, and a manager workspace. The manager workspace is the same portal, limited to the people assigned to that manager; they cannot reach anyone outside that assignment.",
      "Access is based on specific permissions rather than role names, and a manager never has more permissions than an admin.",
    ],
    capabilities: [
      "Team dashboard, employees and reports",
      "Daily AI reports with a review action",
      "Insights and anomalies for the manager's own team only",
      "Email digest for each manager, covering only their team",
      "Permissions that never go beyond an admin's",
    ],
    audience: ["Team managers"],
    faqs: [
      { question: "Can managers see the whole organisation?", answer: "No. Managers only reach the people and teams assigned to them, and their permissions never go beyond an admin's." },
    ],
    relatedFeatures: ["admin-portal", "ai-daily-reports", "audit-trail"],
    sources: [HOME],
  },
  {
    slug: "admin-portal",
    name: "Admin portal",
    summary: "The central place to run the organisation: people, monitoring policy, reporting and the audit trail.",
    category: "oversight",
    hasPage: true,
    body: [
      "The admin portal is where an organisation is run. Admins manage employees, managers and teams, set the monitoring policy, read reports and insights, and review the audit trail, all in one workspace.",
      "Admins add employees, each of whom is emailed a 16-character activation code, and invite managers limited to the teams they own. One sign-in can hold different roles at different companies and switch between them.",
    ],
    capabilities: [
      "Dashboard, employees, managers, teams and settings",
      "Reports, AI reports, insights and anomaly review",
      "Audit logs, API key usage and organisation policy",
      "Activation codes emailed to employees",
      "One sign-in with different roles across companies",
      "Plan, expiry and seat changes from Settings",
    ],
    audience: ["Admins"],
    relatedFeatures: ["manager-workspace", "audit-trail", "windows-desktop-agent"],
    sources: [HOME],
  },
  {
    slug: "people-and-organisation",
    name: "People & organisation",
    summary: "Employees with activation codes, teams, and managers limited to the people they own, with one sign-in across companies.",
    category: "oversight",
    hasPage: true,
    body: [
      "ZUZU's people management lives in the admin portal. Admins add employees, group them into teams and invite managers, each limited to the teams they own and unable to reach anyone outside that assignment.",
      "Adding an employee emails them a 16-character activation code for the desktop agent. A single sign-in can hold different roles at different companies and switch between them.",
    ],
    howItWorks: [
      "Add employees from the portal; each is emailed a 16-character activation code.",
      "Organise employees into teams.",
      "Invite managers and limit them to the teams they own.",
    ],
    capabilities: [
      "Employee records with activation codes",
      "Teams",
      "Managers limited to the people assigned to them",
      "One sign-in holding different roles at different companies, with switching",
      "Seats changed later from Settings",
    ],
    audience: ["Admins"],
    relatedFeatures: ["admin-portal", "manager-workspace", "access-control-and-sign-in"],
    sources: [HOME],
  },
  {
    slug: "access-control-and-sign-in",
    name: "Permissions & two-factor sign-in",
    summary: "Access based on specific permissions rather than job title, with two-factor codes from an authenticator app on admin and manager sign-in.",
    category: "oversight",
    hasPage: true,
    body: [
      "ZUZU checks specific permissions, not role names, before allowing any action. A manager's permissions are always a subset of an admin's and only ever reaches the teams assigned to them.",
      "Admin and manager sign-in supports two-factor codes from an authenticator app (a second check after the password) alongside Google sign-in, and new organisations sign up with a one-time passcode (OTP) check.",
    ],
    capabilities: [
      "Permissions set per action, not by role name",
      "Managers get only part of what admins can do",
      "Managers limited to their assigned teams",
      "Authenticator-app two-factor codes on admin and manager sign-in",
      "Google sign-in",
      "One-time passcode (OTP) check at signup for new organisations",
    ],
    audience: ["Admins", "Team managers"],
    relatedFeatures: ["manager-workspace", "admin-portal", "audit-trail"],
    sources: [HOME],
  },
  {
    slug: "audit-trail",
    name: "Audit trail",
    summary: "Organisation events filterable by severity, viewable as a table or timeline, and exportable.",
    category: "oversight",
    hasPage: true,
    body: [
      "ZUZU keeps an audit trail meant to answer questions about who did what. It records events across employees, teams, managers, shifts, leave, reports, payments, live capture and the organisation itself.",
      "Events can be filtered by severity, viewed as a table or a timeline, and exported.",
    ],
    capabilities: [
      "Events for employees, teams, managers, shifts, leave, reports, payments, live capture and organisation settings",
      "Severity filtering",
      "Table and timeline views",
      "Export",
    ],
    faqs: [
      { question: "Which events does the audit trail record?", answer: "Employee, team, manager, shift, leave, report, payment, live-capture and organisation events." },
      { question: "Can the audit trail be taken out of ZUZU?", answer: "Yes. Events can be filtered by severity, viewed as a table or a timeline, and exported." },
    ],
    audience: ["Admins"],
    relatedFeatures: ["admin-portal", "access-control-and-sign-in", "reports-and-exports"],
    sources: [HOME],
  },
];

export const zuzu: Product = {
  id: "zuzu",
  slug: "zuzu",
  name: "ZUZU",
  shortDescription:
    "Time tracking and activity insight for teams on Windows: a desktop agent captures the workday privately, and AI writes the reports.",
  longDescription:
    "ZUZU pairs a Windows desktop agent with an admin and manager portal. Activity is captured on the device with private content painted out before anything leaves it, and each day reaches the portal already summarised: attendance, focus, applications and an AI report per person, shown according to each person's permissions.\n\nThe product has three parts that share one record: the agent employees install once and activate with a code, the admin portal that holds people, monitoring policy, reporting and the audit trail, and a manager workspace that is the same portal limited to the people a manager is assigned.\n\nReporting runs on a schedule rather than on request. A report is written for every employee each day, digests go out in the organisation's timezone with the PDF attached, and managers can confirm or correct what the engine concluded. ZUZU states its limits up front: the agent is Windows-only, and policy such as screenshot frequency and how long screenshots are kept is set per organisation.",
  tagline: "Know how the workday actually went.",
  category: "hr-people",
  secondaryCategories: ["insights-research"],
  subcategory: "workforce-analytics",
  primaryUseCase: "Understanding how team time is spent",
  audience: ["Admins", "Team managers"],
  platforms: ["windows", "web"],
  market: "India",
  status: "live",
  verification: { relationship: "pending", publicSale: "confirmed" },
  websiteUrl: "https://usezuzu.com/",
  appUrl: TRIAL,
  publisher: { name: "Bizzfly Business Automation" },
  featureCategories,
  features,
  howItWorks: [
    { title: "Create the workspace", description: "Sign up with a verified email; a 7-day trial organisation for up to 10 employees is set up immediately, with no card. Paid organisations activate straight after checkout instead." },
    { title: "Add people, send codes", description: "Add employees from the portal and each is emailed a 16-character activation code. Invite managers and limit them to the teams they own." },
    { title: "Install the agent", description: "Employees run the roughly 80 MB Windows installer and paste their code once. The agent then runs from the system tray, starts with Windows and keeps itself up to date." },
    { title: "Read the day", description: "Activity, screenshots and attendance flow into the portal, and reports, insights and digests are produced on a schedule, so nobody has to remember to generate them. ZUZU says there is no integration project or agent configuration to write." },
  ],
  benefits: [
    { title: "Reports that are already written", description: "The engine writes a report per employee per day on a schedule. By the time a manager opens the report browser, the day is there, and the digest has already arrived with the PDF attached." },
    { title: "Private content stays on the machine", description: "Passwords, private windows and desktop notifications are painted out on the employee's device before a screenshot is written or uploaded, so those pixels never leave it." },
    { title: "Conclusions a person can challenge", description: "Each report carries its evidence, managers confirm or correct the engine's conclusions, and those corrections feed back into scoring. The portal also reports how often reviewers agreed." },
    { title: "Managers see only their own people", description: "Access is based on specific permissions, and the manager workspace is limited to assigned teams, so a manager cannot reach anyone outside that assignment." },
    { title: "A rollout measured in an afternoon", description: "Setup is four steps (workspace, people, agent, read the day), and the trial lets you see a full day of activity, attendance and reporting before you decide anything." },
  ],
  security: [
    { title: "On-device redaction", description: "Passwords, private windows such as messaging, banking, webmail and password managers, and desktop notifications are painted out before the image is written to disk or uploaded." },
    { title: "Retention you decide", description: "Screenshots are kept for 30, 90 or 180 days, one year, or indefinitely; admins can download or delete a single day's captures." },
    { title: "Permission-based access", description: "Every action is checked against specific permissions, not role names; managers get only part of what admins can do and only reach their assigned teams." },
    { title: "Two-factor authentication", description: "Authenticator-app codes on admin and manager sign-in, alongside Google sign-in and OTP-verified signup for new organisations." },
    { title: "Audit trail", description: "Organisation events filterable by severity, viewable as a table or timeline, and exportable." },
    { title: "Consent-gated tracking on personal laptops", description: "Employees set to session-only tracking are captured only between punch-in and punch-out, under a short-lived lease that expires if the laptop goes offline." },
  ],
  pricing: {
    unit: "employee",
    trial: "7-day free trial for up to 10 employees, no card required",
    note: "Pricing is per employee and confirmed at checkout against the headcount entered; no prices are published on the site.",
    asOf: "2026-10-08",
    sourceUrl: "https://usezuzu.com/#plans",
    plans: [
      { name: "Free trial", price: "Free", period: "7 days", description: "The full platform (agent, reports, AI daily reports, insights and audit) for teams that want to see a real day of data before buying. Set up instantly after email verification.", features: ["7 days of the full platform", "Up to 10 employees", "No card required to start", "One live trial per account"], cta: { label: "Start free trial", href: TRIAL } },
      { name: "Paid plan", price: "Per employee", description: "For organisations ready to roll out, or needing more than 10 employees from the start. Buy for your headcount; the organisation activates as soon as payment settles, with no approval queue.", features: ["Priced per employee, confirmed at checkout", "Email and mobile verification during signup", "Coupon codes applied before payment", "Seats and plan changed later from Settings"], cta: { label: "Buy a plan", href: "https://usezuzu.com/apply" }, recommended: true },
    ],
  },
  supportUrl: "mailto:support@bizzfly.com",
  connections: [{ product: "hrmagix", description: "ZUZU lists an attendance sync with HRMagix." }],
  useCases: [
    { title: "Daily reporting without writing reports", description: "Managers get an AI-written report per person per day, delivered as a digest before the meeting starts." },
    { title: "Spotting change early", description: "Behaviour-change detection flags work that drifts from a person's own baseline and routes it to review." },
    { title: "Monitoring with real limits", description: "On-device redaction, retention settings and session-only capture on personal laptops keep monitoring within stated bounds." },
    { title: "Seeing where the working day goes", description: "Per-application time, top applications and the hour-by-hour working rhythm show how a team's day is split, with idle and screen-off time reported separately from active time." },
    { title: "Team-only oversight for managers", description: "Each manager works in a workspace limited to their own team's dashboard, daily reports, insights and anomalies, and receives a digest covering only that team." },
  ],
  faqs: [
    { question: "Which computers does ZUZU support?", answer: "The desktop agent runs on Windows only and ships as a 64-bit installer of about 80 MB. There is no macOS or Linux build today, and ZUZU says the portal will not offer one until it exists." },
    { question: "How does ZUZU handle private content?", answer: "Password boxes, passwords typed into documents, private windows such as messaging, banking, webmail and password managers, and desktop notifications are painted out on the device. This happens before the image is written to disk or uploaded, so those pixels never leave the machine." },
    { question: "Can managers see the whole organisation?", answer: "No. Managers work in a limited version of the portal and only reach the people and teams assigned to them. Their permissions never go beyond an admin's." },
    { question: "How often are screenshots captured?", answer: "At an interval the organisation sets: anywhere from 1 to 15 minutes, or a custom interval. The setting is part of the organisation's monitoring policy." },
    { question: "How long are screenshots kept?", answer: "The organisation chooses 30, 90 or 180 days, one year, or indefinitely. Admins can also download or delete a single day's captures as a ZIP from the employee record." },
    { question: "What happens when a laptop goes offline?", answer: "The agent keeps captures in a local queue and uploads them when the network returns. For employees on personal laptops with session-only tracking, the capture permission is a short-lived lease, so it expires on its own while the laptop is offline." },
    { question: "Can people be monitored on their own laptops?", answer: "Employees set to session-only tracking are captured only between punch-in and punch-out. The agent has to keep renewing a short-lived lease to keep capturing, and that lease runs out if the laptop goes offline." },
    { question: "How are reports delivered?", answer: "Reports are generated on a schedule, not on demand. An organisation-wide digest reaches admins and each manager gets a digest for their own team, in the organisation's timezone, with the PDF attached." },
    { question: "Is there a free trial?", answer: "Yes, a 7-day trial of the full platform for up to 10 employees, with no card required." },
    { question: "What happens when the trial ends?", answer: "The workspace stays yours to sign in to, and you upgrade from inside the portal; Settings shows the plan, expiry date and upgrade path. Each account can hold one live trial at a time." },
  ],
  supportTopics: [
    {
      slug: "install-and-activate-the-desktop-agent",
      name: "Install and activate the desktop agent",
      summary: "How employees install the ZUZU Windows agent and activate it with the code from their administrator.",
      body: [
        "The ZUZU agent ships as a 64-bit Windows installer of roughly 80 MB. Each employee needs a 16-character activation code, which the organisation's administrator issues from the Employees page and which arrives by email.",
        "The code is entered once, on first launch. After that the agent runs from the system tray, starts with Windows and updates itself from the organisation's release feed.",
      ],
      steps: [
        "Download ZUZU-Windows-latest-Setup.exe from the ZUZU site; the link serves the current build.",
        "Run the installer. If Windows SmartScreen warns about an unrecognised publisher on a new build, choose More info → Run anyway when your organisation expects this download.",
        "Finish setup: ZUZU is added to the Start Menu and registered to start with Windows for the current user.",
        "Paste the 16-character activation code from your administrator's email.",
        "Leave the agent running in the system tray; it captures on your organisation's schedule.",
      ],
      keyPoints: [
        "Windows only; there is no macOS or Linux build today",
        "No window needs to stay open; the agent lives in the system tray",
        "Captures queue locally while offline and upload when the network returns",
        "Updates arrive from your organisation's own release feed",
      ],
      faqs: [
        { question: "Where does the activation code come from?", answer: "Your organisation's administrator issues it from the Employees page; it is emailed to you when you are added." },
        { question: "What happens when a laptop goes offline?", answer: "The agent keeps captures in a local queue and uploads them when the network returns." },
      ],
      features: ["windows-desktop-agent", "admin-portal"],
      sources: [HOME],
    },
    {
      slug: "start-a-free-trial",
      name: "Start a free trial",
      summary: "Create a 7-day ZUZU trial workspace for up to 10 employees, with no card required.",
      body: [
        "ZUZU's trial is the full platform (desktop agent, reports, AI daily reports, insights and the audit trail), not a cut-down build. The trial workspace is set up as soon as your email is verified; nothing waits in an approval queue.",
        "When the trial ends the workspace stays yours to sign in to, and you upgrade from inside the portal, where Settings shows the plan, the expiry date and the upgrade path.",
      ],
      steps: [
        "Organisation: enter the organisation name, type, country and size (website and address are optional).",
        "Contact: provide your contact details.",
        "Verify: confirm your email address.",
        "Use case: tell ZUZU how you plan to use it.",
        "Review: check the details and create the workspace.",
      ],
      keyPoints: [
        "7 days of the full platform, starting immediately",
        "Up to 10 employees",
        "No card required to start",
        "One live trial per account at a time",
        "Need more than 10 employees or a paid plan straight away? Buy a plan instead",
      ],
      faqs: [
        { question: "What happens when the trial ends?", answer: "The workspace stays yours to sign in to, and you upgrade from inside the portal; Settings shows the plan, the expiry date and the upgrade path." },
      ],
      features: ["windows-desktop-agent", "ai-daily-reports", "workforce-insights", "audit-trail"],
      sources: [HOME, TRIAL],
    },
    {
      slug: "buy-a-plan",
      name: "Buy a plan",
      summary: "Purchase ZUZU for your headcount and have the organisation activate as soon as payment settles.",
      body: [
        "ZUZU is priced per employee, and the price is confirmed during checkout against the headcount you enter. The purchase flow verifies both your email and mobile number before you pay, and the organisation activates as soon as payment settles; there is no approval queue.",
        "If you have already applied, you can check on your application from the status page by entering the work email you applied with.",
      ],
      steps: [
        "Organisation: enter the organisation's name, type, country and size.",
        "Contact: provide contact details.",
        "Verify: confirm your email and mobile number.",
        "Use case: describe how you will use ZUZU.",
        "Review and pay securely; coupon codes are applied before payment.",
      ],
      keyPoints: [
        "Priced per employee, confirmed at checkout",
        "Activation as soon as payment settles",
        "Seats and plan can be changed later from Settings",
        "Application status can be checked with your work email",
      ],
      links: [
        { label: "Buy a plan", href: "https://usezuzu.com/apply" },
        { label: "Check application status", href: "https://usezuzu.com/apply/status" },
      ],
      features: ["admin-portal"],
      sources: [HOME, "https://usezuzu.com/apply", "https://usezuzu.com/apply/status"],
    },
  ],
  solutions: ["manage-people-from-hire-to-growth"],
  sources: [HOME, TRIAL, "https://usezuzu.com/apply", "https://usezuzu.com/apply/status"],
  lastVerified: "2026-10-08",
};
