// node scripts/faq-report.mjs <audit.json> <out.md> — writes the FAQ audit report table
import { readFileSync, writeFileSync } from "node:fs";
const [inp = "scripts/.ref/faq-after.json", out = "docs/TOYOAPPS_FAQ_AUDIT.md"] = process.argv.slice(2);
const rows = JSON.parse(readFileSync(inp, "utf8"));
const type = (r) => {
  if (r === "/") return "Homepage";
  const m = r.match(/^\/products\/[^/]+(\/.*)?$/);
  if (r === "/products") return "Product catalog";
  if (r.startsWith("/products/category/")) return "Category";
  if (m && r.split("/")[2] !== "category") {
    const rest = m[1] ?? "";
    if (!rest) return "Product overview";
    if (rest === "/features") return "Feature hub";
    if (rest.startsWith("/features/group/")) return "Feature group";
    if (rest.startsWith("/features/")) return "Feature detail";
    const seg = rest.split("/").filter(Boolean);
    if (seg.length === 1) return `Product ${seg[0]} page`;
    return `Product ${seg[0].replace(/s$/, "")} detail`;
  }
  const first = r.split("/")[1];
  const map = { solutions: "Solution", industries: "Industry", integrations: "Integration", resources: "Resource", compare: "Comparison", legal: "Legal" };
  if (map[first]) return r.split("/").length > 2 ? `${map[first]} page` : `${map[first]} hub`;
  return `Company: ${first}`;
};
const pass = (x) => x.count === 8 && !x.dup && x.sets === 1 && x.ldMatch;
const lines = [
  "# ToyoApps — FAQ audit",
  "",
  `Generated by \`scripts/faq-audit.mjs\` + \`scripts/faq-report.mjs\` against the running site (${rows.length} public routes from the sitemap).`,
  "",
  "## How FAQs are produced",
  "",
  "- Every page renders its FAQs through `FaqList` (one accordion, native `<details>`/`<summary>`, keyboard accessible) with matching `FAQPage` JSON-LD generated from the same items.",
  "- Questions come from `src/lib/faqs.ts`: hand-written FAQs from the content files first, then questions composed **only from verified fields already in `src/content`** (summaries, steps, capabilities, problems, audiences, plans, security measures, linked products, published dates). A question is offered only when the data to answer it exists, so nothing is invented.",
  "- Each page type draws on its own subject first, then its parent (feature → group → product → category → site) to reach exactly 8.",
  "- Duplicate questions, and duplicate answers, are removed per page. Generated answers are at least 10 words; hand-written answers are kept as written.",
  "",
  "## Checks",
  "",
  "| Check | Result |",
  "|---|---|",
  `| Routes audited | ${rows.length} |`,
  `| Exactly 8 rendered FAQ items | ${rows.filter((x) => x.count === 8).length} / ${rows.length} |`,
  `| Duplicate questions on a page | ${rows.filter((x) => x.dup).length} pages |`,
  `| More than one FAQ list on a page | ${rows.filter((x) => x.sets > 1).length} pages |`,
  `| FAQPage JSON-LD matches visible items | ${rows.filter((x) => x.ldMatch).length} / ${rows.length} |`,
  `| Pages with a concise (< 12 word) answer | ${rows.filter((x) => x.short).length} — mostly hand-written answers that answer directly (e.g. "No. Whisper coaching goes only into the rep's headset."), plus a few short generated facts of 10–11 words (e.g. which platforms a product runs on) |`,
  `| Render errors | ${rows.filter((x) => x.error).length} |`,
  "",
  "Answers verified: composed answers quote the page's own content fields (see `src/lib/faqs.ts`); hand-written answers come from the product content files, which record their official sources and last-verified date.",
  "",
  "## Per-page results",
  "",
  "| Page URL | Page Type | FAQ Count | Unique Questions | Answers Verified | Status |",
  "| -------- | --------- | --------: | ---------------- | ---------------- | ------ |",
  ...rows.map((x) => `| \`${x.route}\` | ${type(x.route)} | ${x.count ?? "—"} | ${x.dup ? "No" : "Yes"} | From page content | ${pass(x) ? "✅ Pass" : "❌ Check"} |`),
  "",
];
writeFileSync(out, lines.join("\n"));
console.log("wrote", out, rows.length, "rows, pass", rows.filter(pass).length);
