// node scripts/image-report.cjs — writes docs/TOYOAPPS_IMAGE_AUDIT.md from scripts/.ref/images-summary.json
const fs = require("fs");
const r = require("./.ref/images-summary.json").sort((a, b) => b.pages - a.pages);
const L = [
  "# ToyoApps — Inner-page image audit",
  "",
  "Date: 2026-10-10. Scope: all 609 inner routes. The homepage is excluded and untouched. Browser audit at 1440px, DPR 2 (`scripts/image-audit.mjs`).",
  "",
  "## Result",
  "",
  "| Check | Result |",
  "|---|---|",
  `| Images rendered on inner pages | ${r.length} distinct files |`,
  "| Remote / third-party URLs | 0 |",
  "| Format | all WebP except the SVG app icon on the press kit |",
  "| Natural width smaller than displayed width | 0 |",
  "| Broken images | 0 |",
  "| Missing alt | 0 (decorative images use `alt=\"\"`) |",
  "",
  "## Changes",
  "",
  "| Was | Pages | Problem | Now |",
  "|---|---|---|---|",
  "| `features/feature-screen.webp` | 288 | Same Western stock office photo on every feature page; alt named the feature, not the photo | The feature's own capability visual (real content, no image file) |",
  "| `features/item-hero.webp` | 169 | Same stock photo on every solution, industry, integration, resource and support detail page | The product's own photo (`products/{slug}/in-action.webp`), with alt text describing the photo |",
  "| `features/item-screen.webp` | 157 | Same stock photo | A capability visual listing the page's real features |",
  "| `features/group-hero.webp`, `group-feature.webp` | 39 | Same stock photos, 560px source shown at 480–976px | Product photo plus per-feature capability visuals |",
  "| `products/*/spotlight-1..3.webp` (48 files) | 16 | Fake dashboard mock-ups with unsupported claims (\"SOC2 Compliant\", \"99.98% SLA\", \"0 latency\") | Removed; the real-content spotlight visual remains |",
  "| `products/*/groups/*` (24 files), `product/spotlight-*` | 0 | Unused fake mock-ups | Deleted |",
  "| `categories/insights-research.webp` | 1 | Fake product mock-up | Project photo: manager reviewing a report with an employee |",
  "| `solutions/prepare-for-launch-and-fundraising.webp` | 2 | Fake mock-up (\"Verified\", \"Immediate\") | Project photo: founder presenting market-size charts to investors |",
  "| `pool/p0–p7`, HRMagix `hero-a/b` and `card-*`, TrackySuite `photo-*` | — | Downloaded from Unsplash in an earlier session (third-party) | Replaced with project-owned photos; files deleted |",
  "| Category hero alts | 5 | Generic (\"enterprise software solutions and team workflows\") | Each describes its photo (`src/lib/photos.ts`) |",
  "",
  "## Remaining",
  "",
  "- **Homepage (excluded on purpose):** `public/images/products/meetingmind/card.webp` is a copy of an Unsplash photo and is used only by the homepage product cards. It was left unchanged per the brief.",
  "- **Repetition within a product:** each product's detail pages share that product's one photo (for example, the HRMagix photo appears on 54 HRMagix pages). It is always relevant to the product. Distinct per-page photos would need new original photography or image generation, which was not available here.",
  "- **Other project folders:** not reachable, because this session is limited to the Toyo-app folder by organisation policy.",
  "- **Provenance of earlier assets:** `products/*/in-action.webp`, `tile.webp`, `categories/*`, `company/*` and `solutions/*` came from earlier work. They do not match the third-party downloads checked here, but their original source is not recorded in the repo.",
  "",
  "## Per-image list",
  "",
  "| Image | Pages | Example page | Natural width | Max shown width | Alt text |",
  "|---|--:|---|--:|--:|---|",
  ...r.map((x) => `| \`${x.k}\` | ${x.pages} | \`${x.eg}\` | ${x.w || "svg"} | ${x.dw} | ${x.alts.slice(0, 2).join(" / ").replace(/\|/g, "/").slice(0, 110)}${x.alts.length > 2 ? ` …(+${x.alts.length - 2})` : ""} |`),
  "",
];
fs.writeFileSync("docs/TOYOAPPS_IMAGE_AUDIT.md", L.join("\n"));
console.log("wrote", r.length, "rows");
