/**
 * A placed image, positioned where Zoho places artwork (hero visuals, feature
 * screenshots, section illustrations). Each slot points at its own file under
 * /public/images — replace that file (same name) to swap in real artwork.
 * Placeholders are generated by scripts/make-placeholders.mjs.
 */
export function ImageSlot({
  src,
  alt,
  width,
  height,
  priority = false,
  className,
}: {
  /** Public path, e.g. "/images/home/hero.svg". */
  src: string;
  alt: string;
  width: number;
  height: number;
  /** Above-the-fold images load eagerly; everything else lazy-loads (as Zoho does). */
  priority?: boolean;
  className?: string;
}) {
  return (
    // eslint-disable-next-line @next/next/no-img-element -- plain img so files can be swapped (svg/png/webp) without config
    <img
      src={src}
      alt={alt}
      width={width}
      height={height}
      loading={priority ? "eager" : "lazy"}
      decoding="async"
      className={["image-slot", className].filter(Boolean).join(" ")}
      style={{ aspectRatio: `${width} / ${height}` }}
    />
  );
}
